### ISSUE TITLE
When viewing a product: Call to a member function getListingThumbnailImage() on a non-object

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#100]
I upgraded Community Store from 0.9.7.7 to 0.9.8.7 and I'm getting this error when trying to edit just 2 products in the dashboard, the other 12 are fine.
One of the products has 2 images, the other has 1 and both products can be viewed ok on the front-end, neither has a description.
Using C5 v5.7.5.8.

Error is:
/­home/­streamhygienemad/­public_html/­packages/­community_store/­single_pages/­dashboard/­store/­products.php379

Call to a member function getListingThumbnailImage() on a non-object

**Comment by Mesuva** [comment]
I've made a commit that should fix the problem (just needed a bit more checking I think)
You might want to just try manually changing the few lines of code to see if that resolves the problem.

**Comment by madesimplemedia** [comment]
Yes works great thanks! :)

**Comment by Mesuva** [comment]
Awesome, thanks for confirmation,
