### ISSUE TITLE
Doctrine error when cloning product

### ISSUE THREAD

**Issue by lvanstrijland** [concrete5-community-store/community_store#101]
When I tried to duplicate a product I received the following error:

`A new entity was found through the relationship 'Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariation#options' that was not configured to cascade persist operations for entity: Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariationOptionItem@0000000077b38f8100007f9d3248c02e. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariationOptionItem#__toString()' to get a clue.`

It has something to do with the te Product Option values.
When I'm not using different prices for different options, the clone doesn't return an error.
But when te prices are filled in, it returns the doctrine error.

**Comment by Mesuva** [comment]
I've not seen this one before.
I did do some work on duplicating products the other day, and I've just done a final merge of that work.
Perhaps try updating your codebase and triggering off an upgrade for the package.

With this latest version I can successfully a product with variations that have seperate prices.

**Comment by lvanstrijland** [comment]
On a fresh install I still receive this error:

![schermafbeelding 2016-10-10 om 09 25 51](https://cloud.githubusercontent.com/assets/22031710/19229163/bc77a480-8ecb-11e6-8679-4c7dedda50ef.png)

**Comment by Mesuva** [comment]
I can replicate this - will work on a fix

**Comment by Mesuva** [comment]
I've pushed up to master a fix for this. I've given it a good test but please let me know your results.

**Comment by lvanstrijland** [comment]
That fixed the problem! Thanks!
