### ISSUE TITLE
Error on Product Page

### ISSUE THREAD

**Issue by krebbi** [concrete5-community-store/community_store#103]
After pulling ba5c066..b702e2b I got this error when trying to visit a product detail page:

![bildschirmfoto 2016-10-10 um 17 47 32](https://cloud.githubusercontent.com/assets/3884521/19242097/fd161f76-8f11-11e6-9c8b-46315ba959ea.png)

Any hints are highly appreciated. 

thx

**Comment by Mesuva** [comment]
This one is sort of more a concrete5 issue. What happens is that when you uninstall the store, the Product page type also gets remove. The existing product pages in the site then end up pointing at a page type that no longer exists, resulting in this error.

If you go to the sitemap, find a product page, bring up it's menu and select 'Design & Type', you can then set the page to use a page type again (i.e. the Product page type again).  I don't think there is a way to do this in bulk through the interface.

What I don't know at this point is if this is something that concrete5 itself should handle (should it fall back to a different page type), or is it something that community store should handle. 

For community store to handle it, it either has to delete all the existing products and their pages on uninstall, or do something else to correct the existing page types when it's reinstalled - it would have to keep track of the pages in some other way. Quite complicated really!

**Comment by krebbi** [comment]
perfect, thanks! 

I think this isn't something that should be handled by community store. In case of a productive shop it might be the fastest to alter the DB directly. 

I just uninstalled and installed the store because of a mysql error while updating.
