### ISSUE TITLE
Product categorization

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#105]
When creating a new product I have the option to categorize it under a certain page (or multiple pages). I was wondering why the page for the product is still created directly under the 'Products' page and not 'Products -> Category 1' for example. I suppose that's the intended behavior? Is there an easy way to modify this?

**Comment by Mesuva** [comment]
There's a few reasons for this:

- When you've got a product that appears in multiple categories, it can become a bit of a mess, especially to decide what is the 'main' category that a product should appear under. If you start trying to use page aliases or page copies, you end up with possible duplicate content pages.
- If you have the product page itself under a category page If you recategorise a product, you're then changing the slug/path to that product. By keeping the product page location simpler, you've always got the same path to it, regardless of how you manage its categorisation
- There's also a bit of a danger of having too long a page path if the products are nested. Although there can be value in having the category name keywords in the url, there's nothing stopping you from customising the product page slug itself to include such words (and it gives you more flexibility)

That all being said, there's nothing stopping you from moving the newly created product page from beneath the products page somewhere else, to create the nesting that you want.

The main thing is that in Community Store, the categorisation of the product and the location of the product page itself just aren't actually related. You actually don't even _have_ to use product pages as such, they're just an automatic creation of a page that includes a product block configured to show that product.

**Comment by jakob-fuchs** [comment]
Thanks for your reply. I'll have to write a product import routine anyway, so I can probably address that there. But actually I don't care too much about the location in the sitemap tree, but it allows me to create breadcrumb and category navs/page lists. I assume you could query the categories created by community store to achive the same (e.g category breadcrumb nav etc.)?

**Comment by Mesuva** [comment]
Fetching the categories that are mapped to a product should be very straightforward, there's a ProductLocation entity you could look to use, but it's just a simple database table to query.

If you wanted to do it a bit more with the API of community store, you could
- Find the product that is associated with the current page, via $product->Product::getByCollectionID($id);
- Then you could fetch for the product the pages: $pages = $product->getLocationPages();
- You'll get back a list of ProductLocation objects. You could take the first one and do getCollectionID() on it to get the ID of the page.
- You could then go Page::getByID() to get that page object
- Then you could either look to hardcode an autonav block (I think you can set a parent page directly), or you could use the navigation helper to fetch the list of breadcrumb items:

$nh = Loader::helper('navigation');
$collectionTrail = $nh->getTrailToCollection(Page::getCurrentPage());

So I think you'd need to hardcode something into a template or create a block for this.

**Comment by jakob-fuchs** [comment]
Thanks for the suggestions. I am not yet sure what the best approach is for my use case. 

Categories, e.g. Groups are flat, so they work more like 'tags'.

Since I need some sort of hierarchy (why is this word so hard to spell?), it would make sense to me to do this with the sitemap tree (using your approach above) or alternatively with a Topic attribute (not sure if topics allow for selection of multiple nodes).

**Comment by Mesuva** [comment]
I think that if you're looking to provide breadcrumbs to your categories, those are going to be pages so it naturally means you'd use the sitemap tree to manage it.

There's still nothing stopping you from moving the product page in the sitemap, that's going to allow a normal autonav breadcrumb block to work. Perhaps it's about creating a little feature (either in Community Store or an add-on) that makes it easy to move the product pages?

**Comment by jakob-fuchs** [comment]
Moving the product page below the category page would definitely be something that I need. Not sure what complexities that will bring with it when having multiple category (parent) pages. If I create something useful I can share it here.

**Comment by Mesuva** [comment]
Back in 5.6 ecommerce I did achieve multiple categories through a bit of hack and the use of page aliases. The big problem with this though is ending up with duplicate content for search engines. 

I think this is a case of picking a 'primary' category for the product, giving it it's set of breadcrumbs, with that either being where the page is nested, or the first category selected. 

If you wanted the breadcrumb to _change_ depending on how a person got to a product (i.e. they got a product via a particular category), I think you'd either have to use the session or something else to to track where the person came from. Perhaps when the product list is viewed, it could log in the session the page the person is one, then on the product page it could look at this 'last_category_page' value to form the breadcrumb.

**Comment by jakob-fuchs** [comment]
Thanks again for your input. Need to think about that a bit. Maybe I can get away with having a main category and storing the other stuff in attributes (vendor for example).

**Comment by Mesuva** [comment]
Closing this as it's really just discussion. Cheers @jakob-fuchs

**Comment by jakob-fuchs** [comment]
Can we create a channel in the c5 slack chat? To discuss things .. ;)

**Comment by krebbi** [comment]
to slip into the same communication nightmare as c5 is stuck? 
please no!

**Comment by Mesuva** [comment]
Well you're obviously welcome to create a channel if you like, but to be honest I think there is a lot of value in having things more formally discussed in a place where it's a bit more permanently recorded - on slack discussion really just gets lost. 

I'm quite happy to just leave issues on github open for longer and flag them with discussion tags.
