### ISSUE TITLE
Active vs Inactive Products

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#107]
When creating a Product I have the option to either mark it as active or inactive. What I assumed was that an inactive product can't be added to the cart and be purchased. 

That's not the case, so my question is what that option is used for? Or is that just something that needs to be manually implemented?

I could of course do $product->isActive() and hide/show it in the product and product list blocks depending on the value.

**Comment by Mesuva** [comment]
The inactive status of a product is meant to basically turn it on and off within the store.

You are right though that it wasn't quite working well on the product block side of things.
It was removing the inactive product from the product lists, but the actual product blocks weren't changing.  I've just checked in a bit of code to check for this status on the product block.

**Comment by jakob-fuchs** [comment]
That fixed it for me. Inactive products don't show in the product list block and in the product block I get an 'out of stock' message.
