### ISSUE TITLE
Duplicating product with options gives error

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#109]
Duplicating a product with option (Small, Medium, Large) results in the following error:

`A new entity was found through the relationship 'Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariation#options' that was not configured to cascade persist operations for entity: Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariationOptionItem@0000000000a41e160000000007a45974. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariationOptionItem#__toString()' to get a clue.`

**Comment by Mesuva** [comment]
What version are you running?  I've got a feeling this was fixed recently. Try clearing your cache too.

I just happened to have a tab open with a product with options - hitting the duplicate button resulted in a successful copy:

![screen shot 2016-10-26 at 9 04 09 pm](https://cloud.githubusercontent.com/assets/1079600/19722771/c3b713d8-9bbf-11e6-9acb-088271dcc8ac.png)

**Comment by katalysis** [comment]
I've got v.0.9.8.7

**Comment by Mesuva** [comment]
There's been some work on product variation/option saving since then;
https://github.com/concrete5-community-store/community_store/commit/a350b509e4faf756e731554b96e66e682e80b6a5

Try updating to the latest version

**Comment by katalysis** [comment]
Updated and issue is resolved. Many thanks
