### ISSUE TITLE
Can't add/edit Product List Block after updating from 0.9.9.2 to 0.9.9.3

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#122]
![product_list_error](https://cloud.githubusercontent.com/assets/1150242/20248313/033386dc-a9a7-11e6-9f78-e0a2983bdc16.png)

The error is thrown twice (if that matters). Happens when adding new product list blocks or editing existing ones.

I've updated the package with git pull, upgraded it in the dashboard and refreshed the db.xml file for the product list block.

Any ideas how to fix that?

**Comment by jakob-fuchs** [comment]
Same thing happened after installing community store on a different c5 installation (v.7.5.9).

**Comment by jakob-fuchs** [comment]
Temporarily solved by setting  $args['relatedPID'] = 0; in the Block Types' save method.

**Comment by Mesuva** [comment]
This looks like a bug from MySQL strict mode (and not testing in it).

I've pushed up this commit as a fix:
https://github.com/concrete5-community-store/community_store/commit/495e10f076dab94f91a51e03b80b16d81c171c07
