### ISSUE TITLE
Order dashboard search is lacking depth

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#123]
At the moment the order search can only search by order number.

It would be great to expand this to search by customer name, email, but it's not trivial as this information is stored in attributes. It may require a new function in OrderList.

**Comment by Jozzeh** [comment]
I've had a look at this , but haven't got the time to fork and make a pull request.  

Here's a pastebin (expires in a month) ...    [pastebin link](http://pastebin.com/NC44rD13)
We've tested with a previous version of CommunityStore, but got an error on the addWhere function.   

However, the query works to get the distinct oID's of the orders and it searches on customer name (first and last) and email.

**Comment by Mesuva** [comment]
That's awesome, I'll see if I can tie it in.

I'll just paste it here for quick reference

```
<?php
//OrderList.php at line 29->31
if (isset($this->search)) {
     $this->query->where('oID like ?')->setParameter($paramcount++, '%'. $this->search. '%');
}

//Change to 
if (isset($this->search)) {
     $this->query->where('oID like ?')->setParameter($paramcount++, '%'. $this->search. '%');

     $app = Application::getFacadeApplication();
     $db = $app->make('database')->connection();
     $matchingOrders = $db->query("SELECT DISTINCT(oID) FROM CommunityStoreOrderAttributeValues csoav INNER JOIN atDefault av ON csoav.avID = av.avID WHERE av.value LIKE ?", array('%'.$this->search.'%'));

    $orderIDs = array();
    while ($value = $matchingOrders->fetchRow()) {
        $orderIDs[] = $value['oID'];
    }

    if (!empty($orderIDs)) {
        if ($paramcount > 0) {
             $this->query->addWhere('o.oID in ('.implode(',', $orderIDs).')');
        } else {
             $this->query->where('o.oID in ('.implode(',', $orderIDs).')');
        }
    }
}
?>
```

**Comment by Mesuva** [comment]
This worked a treat, this is what I came up with:
https://github.com/concrete5-community-store/community_store/pull/134

Just needed to turn the addWhere into an orWhere

**Comment by Jozzeh** [comment]
Excellent ! I couldn't get my head around why the 'andWhere' failed but I'm glad the query was usefull.
