### ISSUE TITLE
Multilingual order notifications

### ISSUE THREAD

**Issue by Remo** [concrete5-community-store/community_store#125]
I heard that the mail notifications we send aren't sent in the right language. I didn't test it myself, but I had a quick look at the code an believe it's really not working. To ensure we don't forget.

Here's an example where we send an email: https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Order/Order.php#L572-L626

The whole produce runs in the currently active locale of the user, but that's not necessarely the language the user sent the order. In order to achieve this, we would have to save the value of `Localization::activeLocale` to the order and then quickly change it before the mail is loaded/sent using `Localization::changeLocale` and then back to ensure that the admin still see the same language in the dashboard.

UPDATE: I'm not sure anymore, it seems like all emails are sent from the front-end, I'll have a look later.

**Comment by Mesuva** [comment]
I think may depend on what payment gateway is in use, whether it's an 'external' gateway or not.
External gateways are going to trigger the completion of orders from a server to server request, meaning they'll not have access to the current user. So storing the language the customer used during checkout to place the order would likely be needed here.

It's on my todo list to refactor the way the orders are processed in general, I'd like to split out the receipt sending to it's own function, one that can be run again in the future for the purpose of a a 'resend invoice email' button in the dashboard.

**Comment by Remo** [comment]
In other words: Are you saying it's not worth looking into this issue till you refactored the way orders are handled? I don't have much time, but I feel like having some more multilingual functionality would make community store a lot stronger.

**Comment by Mesuva** [comment]
Perhaps not, it's really the next major thing I want to look at - I'll try to tie into that the language consideration.

I completely agree that multilingual features would be very beneficial, I'm currently writing up some notes on issue #128 agreeing with this sentiment!
