### ISSUE TITLE
Product attribute order

### ISSUE THREAD

**Issue by appliculture** [concrete5-community-store/community_store#127]
Each time I create a new attribute the display order is mixed and it's not displaying in the order of 
creation.

It would be great to be able to choose display order of product attributes.

**Comment by Mesuva** [comment]
This should be addressed via https://github.com/concrete5-community-store/community_store/pull/140

**Comment by Mesuva** [comment]
Just tried doing this and there's a misnaming of the class involved to make the sorting happen. Not sure if it's in the core or now.

**Comment by Mesuva** [comment]
I've looked further into this.

I've found that if at least one attribute group is created, the attributes are then sortable, and that sort order is what is shown when editing a product.

Beyond that, I don't have a way to fix this for product attributes not in a group.

**Comment by fmourey** [comment]
I have the same problem. 
I can sort customs attributes with the arrow (only when they are in collections). But even this way, the new order is not saved (lost when I refresh the page).
Is there a way to fix that ? 
I'd like to have a precise display order of custom attributes when adding a new article.

Thank you for your help !
