### ISSUE TITLE
Soon the Italian translation

### ISSUE THREAD

**Issue by lota** [concrete5-community-store/community_store#129]
Hi team,
great project! I just start the Italian translation with gettex, I do a pull request as soon as possible ;-)

anyway, I cannot show my translated phrases on web interface...
I created languages/it_IT/LC_MESSAGES/ with inside messages.po and compiled messages.mo, of course, removed cache and languages installed on server

$msgfmt -v messages.po
128 messaggi tradotti, 467 messaggi non tradotti.

any suggestions?

Alessandro - Lota

**Comment by lota** [comment]
ignore my request, after some reload and cache cleaning all works as expected

**Comment by Remo** [comment]
Translations are managed on transifex and automatically included in releases, no need for pull requests or anything!

**Comment by Remo** [comment]
It's already at 100%!

![image](https://cloud.githubusercontent.com/assets/129864/20522093/9feeda5e-b0ae-11e6-85fe-137907f8a3f4.png)

**Comment by Remo** [comment]
sorry, I thought you've posted this to concrete5/concrete5 )-:

**Comment by lota** [comment]
Hi Remo, no I am translating only "community_store" package, please tell me if continue to translate this package, I already spend some hours ;-)

**Comment by Remo** [comment]
yeah, I've noticed that a bit too late, my bad ;-)
I'm not aware of an Italian translation
