### ISSUE TITLE
Omnipay might not be the best choice

### ISSUE THREAD

**Issue by mnakalay** [concrete5-community-store/community_store#130]
Hello,

I was doing some work on a payment processor and frankly, Omnipay doesn't seem to be the best choice.

There is very little documentation and it's falling behind while existing payment processors are changing the way they work.

Maybe Payum would be a better choice. And tho good thing about it is that it can also use Omnipay payment modules so it might be the best of both world.

**Comment by Mesuva** [comment]
Sounds like a good tip to me. 

Fortunately there's nothing in community store that actually requires omnipay, it's only used at the moment in some of the individual payment methods - so we can swap things out down the track if it's best to do so.
