### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ebell14** [concrete5-community-store/community_store#131]
New install of Community Store (0.9.9.6) on concrete5.7.5.9 and get this error when attempting to add a product....  

Invalid argument supplied for foreach()

![image](https://cloud.githubusercontent.com/assets/17576984/20536338/ab0bb288-b0b6-11e6-90bf-276c64008839.png)

**Comment by Mesuva** [comment]
Sorry about this one, I'd recently reworked the way product categoires are handled and hasn't tested it well enough. Should be fixed with https://github.com/concrete5-community-store/community_store/issues/131

**Comment by ebell14** [comment]
Thanks!
