### ISSUE TITLE
Specific rules for options disappear when adding new option 

### ISSUE THREAD

**Issue by lvanstrijland** [concrete5-community-store/community_store#132]
I have added two product options and added specific prices and stock levels for those options.
When I add a new product option my old specific price and stock levels disappear and I have to start all over!

**Comment by Mesuva** [comment]
There might be something that can be done in the future to avoid this, but it's a case of when you add in another option you're effectively creating new configurations of a product.

If you've got a product with an 'colours' option, say, red and blue, you'd then have two product 'variations'. Say you have stock levels of 10 red and 20 blue, both the same price.

Then you add in another option, 'size', with small and large.

You've now got 4 variations. How many small red and large red do you have?  5 of each? 10 of each?  Are both the same price still?  The store can't work this out, you'd need to specify this.

Let me now if I'm misunderstood what you've described though.

**Comment by gstekelenburg** [comment]
hmm, i'd say copy the prices as they are while adding a new group and let the webshop owner adjust the prices for the newly added groups. I can imagine this would tackle a lot of frustration when adding new price options.
