### ISSUE TITLE
Search Product Catalog

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#136]
Do I need to do anything special to make the product description and product attributes available to the c5 search index?

I've updated the search index multiple times, but to no effect so far.

**Comment by Mesuva** [comment]
Details and attribute on a product aren't really related to concrete5's page search, as they're not really on pages to being with. When a product page is created it copies from the product the description into the page's description, so it does handle it partially.

However, both the product and product list blocks _should_ have a getSearchableContent() function, but looking now it looks like they've never been created. In those functions, the title, descriptions and attributes should be output.

So I think we just need to add in these functions.

**Comment by jakob-fuchs** [comment]
>  When a product page is created it copies from the product the description into the page's description, so it does handle it partially.

That doesn't seem to work for me, it copies the short description and copies it to the page's meta description attribute. The page description is not updated.

If I need the content of the product attributes indexed, the best way would be to recreate them as page attributes?

**Comment by Mesuva** [comment]
The meta description on a page should also be part of the sitewide index.. it's primarily for SEO purposes, but I would have thought that text would end up searchable. Do you need to re-run the indexing again?

At this point I'd say what you've described is probably the quickest way to achieve it. What should happen in the future is that the product block itself outputs text for searching purposes. Ultimately if this can also output attributes that have been marked as searchable that would solve the problem.

**Comment by jakob-fuchs** [comment]
Yes, the meta description attribute is indexed. Problem in my case is that I only use the long description (which is not copied to the page description as it seems).

**Comment by jakob-fuchs** [comment]
From my perspective a good solution would be to have an enhanced version of the c5 search block that can take product specific parameters.

**Comment by Mesuva** [comment]
I know that @datasouth have a pending pull request here that includes a product search:
https://github.com/concrete5-community-store/community_store/pull/116

I'm wanting to merge it in at some point, but I wanted to have a look at some more generic solutions to the problem whilst doing so.

I'm just having a play with some getSearchableContent() functions, I may have a quick solution.

**Comment by Mesuva** [comment]
This change here is one you could try:
https://github.com/concrete5-community-store/community_store/commit/7aeb212724b01e29c2c33839c5ee6618814a6b82

The only issue is that it doesn't automatically trigger the search index update after updating a product. That might be something that can happen though, I just have to look into it.

So with this in place, if you then run the search index job, the product name, short and long descriptions should be searchable content in concrete5's default search block. I've not included attributes at this point.

The product list block needs this as well, but it might need a bit of refactoring before that can be added in.

**Comment by jakob-fuchs** [comment]
Thanks. That worked for me.
