### ISSUE TITLE
Cart Modal

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#137]
Are there any reasons against appending the cart modal to the .ccm-page wrapper instead of the body element? 

Appending it to the page wrapper has the advantage that it would pick up the theme styling.

**Comment by Mesuva** [comment]
That's a really good point. I think originally it was done so that the cart styling was more controllable, and less likely to be broken by overall theme changes, or less styling to override in complex themes.

But I just had a play and found that the cart looked pretty good.

My only concern at changing it at this point is that upgrades will result in changes to existing cart styling. Keen to hear the thoughts of others on this.

**Comment by Remo** [comment]
I'd support this change. I think if someone spent a ton of time to customize their CSS it would annoy them to do the same for the cart again, especially if that someone doesn't know that LESS, SCSS is much cooler than plain CSS.
Better change this sooner than later. We don't have any releases or tags, maybe that's something that would help too. It would be move obvious if there was an increment of the version.

**Comment by Mesuva** [comment]
Release versions is something I'm planning to change fairly soon, starting with a 1.0 release after a few more things are addressed. 

I just tested on a few live site - the styling changes, even where Ive done some quite aggressive changes to the cart were pretty minimal. So yes, I reckon we do this.

**Comment by JohntheFish** [comment]
Don't take my thoughts too seriously, I am not an active developer or user of the store...

Looking back to 5.6 and the core commerce cart popup, I would have always liked it to automatically use whatever popup mechanism and styling the theme uses. With more and more themes using a few standard frameworks, providing options for Bootstrap, Foundation and jQueryUI based cart popups would provide most themes with carts that look like they were designed into the theme from the start with little need for subsequent styling.

**Comment by Mesuva** [comment]
I think this makes sense to move. Generally you want things like basic typographical styles to apply to something like the cart. Making the change with Elemental in play immediately makes the modal cart look nicer (or at least more consistent with the rest of the page styling).

PR is here, it's a simple change: https://github.com/concrete5-community-store/community_store/pull/141
