### ISSUE TITLE
Use transifex for translations

### ISSUE THREAD

**Issue by Remo** [concrete5-community-store/community_store#138]
Does anyone have a reason not to use transifex?

**Comment by Remo** [comment]
* Added this repo to concrete5-packages https://www.transifex.com/concrete5/concrete5-packages/community-store/
* Translations can be downloaded here http://concrete5.github.io/package-translations/
* I'd suggest to add a hint to the README pointing to these locations
* I'd suggest to remove the languages from this repo

**Comment by mlocati** [comment]
> I'd suggest to remove the languages from this repo

👍

**Comment by MichaelMaar** [comment]
Just added Danish Translation to Transifix
