### ISSUE TITLE
Selecting Display Quantity Selector in the products page raises error

### ISSUE THREAD

**Issue by Babinsky** [concrete5-community-store/community_store#143]
Hi
I would like to display the quantity selector in my products overview page, so I edit the block and enable Display Quantity Selector. Upon choosing save, suddenly displays now 1 item (instead of my 7)

After selecting Publish Changes the site displays:
An unexpected error occurred.
Fatal error: Call to a member function getHandle() on null

Page is broken, I had to restore an earlier version of this particular page.

Thanks for looking into this.

**Comment by Mesuva** [comment]
Thanks for this, should be fixed by:
https://github.com/concrete5-community-store/community_store/commit/cd5547d40a8f31abd2c7dc2273132a262eac8a17

**Comment by Babinsky** [comment]
How cool and fast is that?!
Thanks very much.
