### ISSUE TITLE
Product Variation Weight and Dimensions get cast to int 

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#144]
[See here](https://github.com/concrete5-community-store/community_store/blob/cd5547d40a8f31abd2c7dc2273132a262eac8a17/src/CommunityStore/Product/ProductVariation/ProductVariation.php#L271)

**Comment by Mesuva** [comment]
Yes, these values should be decimals, not ints in the database.
Will fix.

**Comment by Mesuva** [comment]
Should be fixed by: https://github.com/concrete5-community-store/community_store/commit/6059751590765330e956414ceb9442a0da1d8e53

I did test doing an upgrade in terms of it retaining the original set values, but certainly worth doing a db backup before applying.

**Comment by jakob-fuchs** [comment]
That worked for me. Can't comment on data loss since I didn't have any data stored.
