### ISSUE TITLE
Classes in product block bug

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#148]
In the community product block view.php you have some difference in the clases from php to js

in php:

`echo '<span class="sale-price">' . t("On Sale: ") . $product->getFormattedSalePrice() . '</span>';
                            echo '&nbsp;'.t('was').'&nbsp;';
                            echo '<span class="original-price">' . $product->getFormattedOriginalPrice() . '</span>';`

You the classes "sale-price" and "original-price"

But in the js you got:

`var pricing = '<span class="store-sale-price"><?= t("On Sale: "); ?>' + variationdata[ar.join('_')]['saleprice'] + '</span>' +
                        '<span class="store-original-price">' + variationdata[ar.join('_')]['price'] + '</span>';`

the classes "store-sale-price" and "store-original-price"

**Comment by Mesuva** [comment]
Fixed by https://github.com/concrete5-community-store/community_store/commit/c4970e56b1cb79a86f7daf7d07b839ec1fc3894b
