### ISSUE TITLE
Installation on version 8 broken

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store#149]
Basically broke the whole site:

Whoops\Exception\ErrorException thrown with message "Declaration of Concrete\Package\CommunityStore\Src\Attribute\Key\StoreProductKey::add($type, $args, $pkg = false) should be compatible with Concrete\Core\Attribute\Key\Key::add($handle, $type, $args, $pkg = false)"

Stacktrace:
#40 Whoops\Exception\ErrorException in /var/www/html/playground.dev/public_html/packages/community_store/src/Attribute/Key/StoreProductKey.php:0
#39 Whoops\Run:handleError in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php:236
#38 require_once in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php:236
#37 Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver:getAllClassNames in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php:128
#36 Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain:getAllClassNames in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:357
#35 Doctrine\ORM\Mapping\ClassMetadataFactory:addDefaultDiscriminatorMap in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:243
#34 Doctrine\ORM\Mapping\ClassMetadataFactory:doLoadMetadata in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
#33 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory:loadMetadata in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
#32 Doctrine\ORM\Mapping\ClassMetadataFactory:loadMetadata in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216
#31 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory:getMetadataFor in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
#30 Doctrine\ORM\EntityManager:getClassMetadata in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2608
#29 Doctrine\ORM\UnitOfWork:createEntity in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:144
#28 Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator:hydrateRowData in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:69
#27 Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator:hydrateAllData in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:147
#26 Doctrine\ORM\Internal\Hydration\AbstractHydrator:hydrateAll in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:888
#25 Doctrine\ORM\Persisters\Entity\BasicEntityPersister:loadAll in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:181
#24 Doctrine\ORM\EntityRepository:findBy in /var/www/html/playground.dev/public_html/concrete/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:164
#23 Doctrine\ORM\EntityRepository:findAll in /var/www/html/playground.dev/public_html/concrete/src/Attribute/Category/CategoryService.php:39
#22 Concrete\Core\Attribute\Category\CategoryService:getList in /var/www/html/playground.dev/public_html/concrete/src/Support/Facade/Facade.php:115
#21 Concrete\Core\Support\Facade\Facade:__callStatic in /var/www/html/playground.dev/public_html/concrete/single_pages/dashboard/extend/install.php:22
#20 include in /var/www/html/playground.dev/public_html/concrete/src/View/View.php:207
#19 Concrete\Core\View\View:renderViewContents in /var/www/html/playground.dev/public_html/concrete/src/View/AbstractView.php:151
#18 Concrete\Core\View\AbstractView:render in /var/www/html/playground.dev/public_html/concrete/src/Http/ResponseFactory.php:152
#17 Concrete\Core\Http\ResponseFactory:view in /var/www/html/playground.dev/public_html/concrete/src/Http/ResponseFactory.php:215
#16 Concrete\Core\Http\ResponseFactory:controller in /var/www/html/playground.dev/public_html/concrete/src/Http/ResponseFactory.php:371
#15 Concrete\Core\Http\ResponseFactory:collection in /var/www/html/playground.dev/public_html/concrete/src/Routing/DispatcherRouteCallback.php:41
#14 Concrete\Core\Routing\DispatcherRouteCallback:execute in /var/www/html/playground.dev/public_html/concrete/src/Http/DefaultDispatcher.php:115
#13 Concrete\Core\Http\DefaultDispatcher:handleDispatch in /var/www/html/playground.dev/public_html/concrete/src/Http/DefaultDispatcher.php:53
#12 Concrete\Core\Http\DefaultDispatcher:dispatch in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/DispatcherDelegate.php:39
#11 Concrete\Core\Http\Middleware\DispatcherDelegate:next in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/FrameOptionsMiddleware.php:39
#10 Concrete\Core\Http\Middleware\FrameOptionsMiddleware:process in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#9 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/CookieMiddleware.php:37
#8 Concrete\Core\Http\Middleware\CookieMiddleware:process in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#7 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/ApplicationMiddleware.php:29
#6 Concrete\Core\Http\Middleware\ApplicationMiddleware:process in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#5 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /var/www/html/playground.dev/public_html/concrete/src/Http/Middleware/MiddlewareStack.php:86
#4 Concrete\Core\Http\Middleware\MiddlewareStack:process in /var/www/html/playground.dev/public_html/concrete/src/Http/DefaultServer.php:85
#3 Concrete\Core\Http\DefaultServer:handleRequest in /var/www/html/playground.dev/public_html/concrete/src/Foundation/Runtime/Run/DefaultRunner.php:94
#2 Concrete\Core\Foundation\Runtime\Run\DefaultRunner:run in /var/www/html/playground.dev/public_html/concrete/src/Foundation/Runtime/DefaultRuntime.php:102
#1 Concrete\Core\Foundation\Runtime\DefaultRuntime:run in /var/www/html/playground.dev/public_html/concrete/dispatcher.php:39
#0 require in /var/www/html/playground.dev/public_html/index.php:3

**Comment by Mesuva** [comment]
Yep, just saw this reported on the forums.

Things were installing and working fine on recent v8 github versions, so something has obviously changed before the final release. Will investigate.

**Comment by jakob-fuchs** [comment]
Looks like you just have to add the additional parameter. Not yet tested if that has any side effects.

**Comment by Mesuva** [comment]
Yes, but from memory I think that makes in incompatible with v5.7

**Comment by jakob-fuchs** [comment]
> 100 % backwards compatible

**Comment by Mesuva** [comment]
In Andrew's defence, the attribute system was completely reworked in v8 to support Express, but he's been very responsive to reports of incompatibilities, including in v8 very complex legacy support

So I'd put this down to just an oversight. Looking at it now.

**Comment by jakob-fuchs** [comment]
Don't get me wrong. That wasn't meant to be a complaint. The express stuff sounds really great.

**Comment by Mesuva** [comment]
No sweat, it's just pretty complicated!

I've made some progress with this particular bug and have fixed some others.
Just have one final one to tackle, but I think it may still come down to some changed that are need in v8.

**Comment by Mesuva** [comment]
This particular issue should be fixed via this PR:
https://github.com/concrete5-community-store/community_store/pull/150

Those changed appear to be 5.7 compatible as well.

With those in place, Community Store installs fine under v8, but there are still some errors to do with attributes. Those are more complex issues that _may_ be still to do with the core.

The issues are:
https://github.com/concrete5/concrete5/issues/4757
https://github.com/concrete5/concrete5/issues/4756

The good news is that both of the little temporary changes I've described in both issues then make everything work correctly, so hopefully they are relatively straight forward to resolve.

**Comment by jakob-fuchs** [comment]
That worked. Seems to function normally.

**Comment by jakob-fuchs** [comment]
There are some errors related to custom attribute sets for store orders. Creating a set works but editing and adding attributes to it doesn't. This seems to be working for product attribute sets and attributes.

**Comment by MichaelMaar** [comment]
The Declaration Whoops - I do not think this is concrete5 related - Do you use PHP7? I have seen this a lot the last 2 weeks!

**Comment by jakob-fuchs** [comment]
That's the message I get when I try to edit a Store Order Attribute Set:

Argument 1 passed to Concrete\Core\Attribute\SetFactory::getByAttributeKey() must be an instance of Concrete\Core\Entity\Attribute\Key\Key, instance of Concrete\Package\CommunityStore\Src\Attribute\Key\StoreOrderKey given, called in /var/www/html/playground.dev/public_html/concrete/src/Support/Facade/Facade.php on line 118

Yes, I use PHP7 but c5 v7 and v8 should be compatible.

**Comment by Mesuva** [comment]
@jakob-fuchs That issue is the one I've raised here: https://github.com/concrete5/concrete5/issues/4756

@MichaelMaar I was able to find this issue here (and a few others) on PHP5.6. This pull request https://github.com/concrete5-community-store/community_store/pull/150 should have addressed all of them, except for the two I believe are core v8 issues. I'm not expecting PHP7 issues at this point, but it's still something we need to actively test.

**Comment by MichaelMaar** [comment]
I'm not sure, but it seem that there is some kind of PHP7 checker inside the core. I have had a few issues with the declaration whoops and as @jakob-fuchs mentioned earlier, correcting the parameters in a function seem to correct this.

But to be honest, I think that the best test environment at the moment is PHP7. Simply because it's more strict but still backward compatible. I have a package right now that, if it was developed in PHP7 I would have had no problems. But now I have to rewrite a lot of code.

**Comment by Mesuva** [comment]
Yep, I had to change the parameters of the function here: https://github.com/concrete5-community-store/community_store/pull/150/files#diff-297db354c5adf214b0ec82579c1bbbe7R131

I'm just saying it wasn't a PHP7 issue, it was going to affect all versions. But you are totally right that PHP7 testing is a priority

**Comment by Mesuva** [comment]
We should have a clean install under v8 now. 
If not, it may be due to new issues. From what I'm seeing on github for concrete5, the other fixes we need are due to be in 8.0.1
