### ISSUE TITLE
Adding Shipping Method fails

### ISSUE THREAD

**Issue by krebbi** [concrete5-community-store/community_store#152]
current version 1.0

An exception occurred while executing 'INSERT INTO CommunityStoreFlatRateMethods (baseRate, rateType, perItemRate, perWeightRate, minimumAmount, maximumAmount, minimumWeight, maximumWeight, countries, countriesSelected, smID, disableEnabled) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["5.9", "quantity", "", "", "0", "0", "0", "0", "all", null, null, null]: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'perItemRate' at row 1

**Comment by Mesuva** [comment]
Should be fixed by https://github.com/concrete5-community-store/community_store/commit/beb194c2cfe701ca56ca37e19fda69959a4e0124

(You've got your DB in strict mode, which is fine, helps to expose these kind of problems)
