### ISSUE TITLE
no issue but a question: how to display the custom product attributes?

### ISSUE THREAD

**Issue by buurvrouw** [concrete5-community-store/community_store#158]
Don't know if i'm allowed to ask a question here, but let's try:

I have created some custom product attributes in store>products>attributes, but i can't find out how to display those on a product page.
I made a custom block template by copying the default template from blocks/community_product/view.php. My custom template works, but i would like to display some of the custom product attributes. What code do i have to add to my template to achieve this?

By the way, i think you've done amazing work making this package!

**Comment by Mesuva** [comment]
Have you tried something like:
$attributevalue = $product->getAttribute('attribute_handle');

I'm pretty sure you can treat the $product option the same as you would a page (so $page or $c), and just fetch attribute values from it the same way.

**Comment by buurvrouw** [comment]
This is working perfectly :-) Thanks for pointing me the right direction!
