### ISSUE TITLE
Call to a member function getAddress1() on a non-object (1)

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#161]
My environment is concrete5 v8.0.3 with Community Store v1.0.1. The store is configured with a single product.  After checkout, using invoice payment, attempting to view the customer via Members, by clicking on the username, results in the following exception:

Exception Occurred: /[...]/concrete/attributes/address/controller.php:330 Call to a member function getAddress1() on a non-object (1)

Data is entered into both address fields during checkout.

Other users that were added manually via Members can be viewed/edited.

**Comment by Mesuva** [comment]
I'm not ruling out community store's fault here, but from the sounds of it the error is showing on a concrete5 core dashboard page, with a core attribute type - perhaps it's a core bug with the attribute  (I know the address attribute type had a few issues).

Or have I misunderstood this and this is on a community store dashboard page?

**Comment by dbuonomo** [comment]
You are correct, the exception is thrown on the core dashboard page.

I tested with with v5.7.5.7 and the exception does not occur with that version. I've also verified that there is in fact an address1 record in the atAddress table, with appropriate foreign keys to the attribute tables.

I would tend to agree that it's something with the core. I'll continue to investigate.

**Comment by dbuonomo** [comment]
Did a bit more debugging to try to determine the core issue. I haven't found it, but have determined that the getValue() method in the following segment is returning null:

$value = $this->getAttributeValue()->getValue();
$this->set('address1', $value->getAddress1());
...

The exception occurs on the second line. getAttributeValue() is returning a valid object, but getValue() returns null. Since I can see a valid address in the database, my sense is that this is a bug on the "getter" side of this. The attribute code has seen quite a bit of change since v5.7.

I did a fresh install, but the same exception occurred. Is anyone else running v8.0.3 with Community Store v1.0.6 and NOT having this problem?

**Comment by Mesuva** [comment]
I think this pull request may also fix this particular issue:
https://github.com/concrete5-community-store/community_store/pull/176

**Comment by dbuonomo** [comment]
I just tested with concrete5 v8.1.0 and Community Store v1.0.8 with pull request #176. I completed another purchase and hit the same exception when trying to view the (new) user via Dashboard -> Members. I haven't had time yet to look more closely, but have attached the debug dump and call stack.

[debug-out.txt](https://github.com/concrete5-community-store/community_store/files/732902/debug-out.txt)
[call-stack.txt](https://github.com/concrete5-community-store/community_store/files/732903/call-stack.txt)

**Comment by Mesuva** [comment]
I just tested it again with that combo and I'm able to view the members page with the details I'd expect, both the billing and shipping address are complete with the values I used in the order.

Previously broken accounts are still there though, pull request #176 won't fix though, only the way new user attributes are applied.  Are you certain that you're viewing the recently created user, after you've marked the order as paid?  I've tested it both with direct payments and ones where they are marked paid afterwards.

You can tweak concrete5's /concrete5/attributes/address/controller.php file to not die on this error quite easily, you can change the function to look like this:
```
public function form()
    {
        $this->load();
        if (is_object($this->attributeValue) && $value = $this->getAttributeValue()->getValue()) {
            $this->set('address1', $value->getAddress1());
            $this->set('address2', $value->getAddress2());
            $this->set('city', $value->getCity());
            $this->set('state_province', $value->getStateProvince());
            $this->set('country', $value->getCountry());
            $this->set('postal_code', $value->getPostalCode());
        } else {
            $this->set('address1', '');
            $this->set('address2', '');
            $this->set('city', '');
            $this->set('state_province', '');
            $this->set('country', '');
            $this->set('postal_code', '');
        }
        $this->set('search', false);
        $this->addFooterItem(Core::make('helper/html')->javascript($this->getView()->action('load_provinces_js')));
        $this->addFooterItem(
            Core::make('helper/html')->javascript($this->getAttributeTypeFileURL('country_state.js'))
        );
        $this->set('key', $this->attributeKey);
    }
```

(but I was testing with the default code)
