### ISSUE TITLE
Product and Settings tabs aren't respecting fragment identifier (page anchor)

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#163]
Normally when you have tabs on interfaces you can jump to a tab on page load by specifying an anchor value, e.g.:
/dashboard/store/settings#settings-shipping
_should_ jump to the shipping tab, but it doesn't.
The address should also change when you are changing tabs.

The Shipping Methods page for example links back to the settings page for global shipping options, but it currently doesn't jump to the correct tab.

**Comment by mnakalay** [comment]
Hi Ryan
Just sent you a pull request for this.

**Comment by Mesuva** [comment]
@mnakalay You da man!

**Comment by mnakalay** [comment]
@Mesuva Thank you, Sir! You're da man as well! :)
