### ISSUE TITLE
Limited Attribute Types

### ISSUE THREAD

**Issue by mnakalay** [concrete5-community-store/community_store#170]
Hey Ryan,

I was wondering if there was a technical reason you only attach some attribute types to products and orders (boolean, text, textarea, number, address, and date time)

Why not the select type for instance, and image/file and URL?

Thank you

**Comment by Mesuva** [comment]
No reason, they can be changed via /index.php/dashboard/system/attributes/types
If you think the should be different on install it should be easy to change

**Comment by mnakalay** [comment]
Cool, thank you Ryan.
I am working on an idea that will use a select attribute so for totally selfish reasons I'd say that's needed. Still, I'm going to try it first and see what happens.

Or we could leave it as it is and write a nice tutorial on how to attach more attribute types to orders and products manually.

**Comment by ChrisStudy** [comment]
Did your select attributes for order saved with order? Cause mine is not saved after i submit order.

**Comment by Mesuva** [comment]
I had a look at the order attributes under v8, but couldn't work out a reason for the select options not saving. I have a feeling that this might require some rewriting to be more v8 compatible.

**Comment by MichaelMaar** [comment]
Actually, I have been testing and thinking about this for a while. I was asked to add a table attribute (a lot of food companies if not all has to add AVERAGE NUTRIENT CONTENT or what ever you call it to explain what the product contains), but I have a hard time to figure out a good way to do this.
We already made an add-on to show all attributes as tabs, I only need to find out how I would be able to add a table attribute.
Any comment on this would be appreciated!

**Comment by ChrisStudy** [comment]
Thank you Mesuva.
We created hidden text attribute below every select options then use script to put selected option as input to the text attribute. So we have select option on page for guest to choice and we saved information guest select for order. I guess that's best way we can figure for now.
