### ISSUE TITLE
Items with multiple sizes

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#173]
Hi, Has anything been done to handle items with different sizes?  Selling the same T-shirt for instance being available in s - m- l - xl, for inventory control each should have it's own sku? and sizes selectable from the product page?

**Comment by mnakalay** [comment]
Hello,
When setting products you have access to "options". You can set option lists (e.g. Sizes) and under each list add options (e.g; small, large, xl...)

There is a checkbox labeled "Options have different prices, SKUs or stock levels"

If this box is checked, after saving your options, new fields will appear for you to input sku, stock level, and price for each option.

I hope this answers your question?
