### ISSUE TITLE
Cannot access Settings - throws 500 error

### ISSUE THREAD

**Issue by JonCope** [concrete5-community-store/community_store#177]
I installed Community Store on a site which was built using a particular URL, knowing that the URL would change (slightly) at the point at which the site went live.
I have been impressed with this plug-in - it worked well in testing, was easy to set up and presented no problems.
We went live today which required us to ask our server providers to change the principal URL to .org rather than .co.uk (same site name, which is englisharts - so now englisharts.org ),and that all went smoothly.  The Store appeared to continue to work well but I needed to change a setting in the Settings area, and clicking on that menu item produces a 500 error.  Everything else on the site is working exactly as before, so whilst I realise a 500 error is normally a server side problem I wonder whether this issue is connected with the switch of the URL.
Is the URL included as a setting?  Any suggestions as to what might cause this, and indeed how I can now access the settings to make any necessary changes?
I have looked through the MySQL tables and can't see any data there that would be to do with the site name or URL.
I have also reconnected my site to the Concrete Community following the URL change in case that caused the problem
Any advice or help would be very gratefully received and of course I can provide any information needed.     
Thanks in advance for any helpl

**Comment by Mesuva** [comment]
There's no separate URL settings for community store, so you shouldn't have had to do anything else to change url. 500 errors are often tricky to track down, I'd suggest:
- Turning on debugging with concrete5, that may catch and output the particular error
- Checking both concrete5's logs and the server logs
- Checking your PHP version, perhaps you're using an older version like 5.3

I'd say it's a bit strange to be getting a 500 error for just one section of the dashboard, I'd more expect to see PHP errors, or at least the generic concrete5 error/crash screen with the red error message.

Although I wouldn't expect it to be the cause, I'm assuming you've cleared concrete5's cache.

To manually access the settings, it depends a little on what you want to change, but you'll find community store related config files are stored in /application/config/generated_overrides
Items like shipping methods are configured via database entries however.

**Comment by JonCope** [comment]
Thanks Mesuva for the quick answer
Yes, I have cleared the cache, but I'll certainly check out the other suggestions - helpful!
If all else fails I guess a reinstall of the block may do it.

**Comment by Mesuva** [comment]
I wouldn't do a reinstall (it'll cause some other issues you'll then have to solve), instead I'd start commenting lines out in the settings controller to try to work out what is actually triggering the error. 

The only time reinstalling packages should be considered is if their initial install failed partway through.

**Comment by jasteele12** [comment]
I would add to @Mesuva great advice to also have your browser developer tools open to watch networking events.

I don't know if it's related, but a problem in either case (you might want to check your Trash) is your heading/link [**Buy tickets**](http://englisharts.org/%21trash/rachmaninov-vespers-tickets) is in there.

**Comment by JonCope** [comment]
Thanks @jasteele12.
A good spot, and helpful.  I've now changed that link, but actually that was to a page made in VividStore which I uninstalled and replaced with Community Store.  I had no issues with either before the URL switch and, sadly, having corrected the link it hasn't removed the 500 error.

I will watch in developer tools as you suggest, but all I'm seeing is it saying 
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
which I already know!

BUT
I now realise that because I had made the site live under the new URL I HAD ALSO chnaged all the "Cache and Speed" settings from those best for development to those best for a live site.  I'm now going to switch them back again and see if that makes any difference.
ALSO
I now see that I can't edit a product, so the whole issue seems to be around the editing of the Store as a result of, perhaps, the Cache settings.
Any thoughts on that please anyone?
And also whether there's a possibility of some sort of clash because I was previously running VividStore? (Not my top suspicion I have to say)
Thanks to you and @Mesuva for all the help so far

**Comment by JonCope** [comment]
OK - I've just  reverted all the Cache and Speed Settings to developer mode and immediately the Edit and Settings functions are available and working fine.  Anyone like to suggest which one or ones might be the cause of the issue or shall I just experiment?

**Comment by Mesuva** [comment]
Ah, I think I know what this is.

There is an issue with concrete5 v8.0.3, where if you had css and javascript caching on it, it would fail to compress the CKEditor libraries. Both the product editor page and settings page include a CKEditor.
https://github.com/concrete5/concrete5/issues/4922

So the solution to this is to upgrade to v8.1, or for the time being leave off the 'CSS and JavaScript Cache' option.

**Comment by JonCope** [comment]
Thanks @Mesuva.  I'll do just that.   I hadn't spotted 8.1 was available.  That will sort this out will it?  Given the improvements listed for this version I think I'll go with that, especially the CK Editor improvements.  Looks like MrKD in particular has been a busy boy!  He's an invaluable member of the Concrete community.
