### ISSUE TITLE
Customer registration create validation

### ISSUE THREAD

**Issue by edbeeny** [concrete5-community-store/community_store#181]
When setting creating account on purchase there seems to be no validation on the email address.
It allows the order to be processed but then falls over when it tries to create the new user and doesn't complete the transaction.

**Comment by Mesuva** [comment]
That's a good pickup, and should be easy to fix I believe, there's already a validation process for the email address, but only for whether it is present, not it's format.

I believe at the moment there's HTML5 email checking on the field, but obviously that should never be relied on.

**Comment by edbeeny** [comment]
I also think the validation to see if the email is present is not working correctly.

**Comment by Mesuva** [comment]
Out of interest, what browser are you using to test this?
(not suggesting client side validation is sufficient here)

**Comment by edbeeny** [comment]
Tested on Chrome and Edge.

**Comment by Mesuva** [comment]
Are you not getting the native HTML5 validation to kick in on Chrome?
The field should have required and type="email" attributes

<img width="736" alt="screen shot 2017-02-01 at 9 50 06 pm" src="https://cloud.githubusercontent.com/assets/1079600/22504896/89667006-e8c8-11e6-8e1a-46b61f604099.png">
<img width="513" alt="screen shot 2017-02-01 at 9 50 10 pm" src="https://cloud.githubusercontent.com/assets/1079600/22504895/89662bdc-e8c8-11e6-8ffd-4afa558c8150.png">

**Comment by edbeeny** [comment]
Yes looks like client side validation is working.
If I add an email address that is already registered it doesn't validate that and falls over when trying to register.

**Comment by Mesuva** [comment]
Although I did find a small issue with the process where it wouldn't add user groups to an already registered user account (i.e. same email address), I couldn't replicate errors as such.
The fix I made was this one:
https://github.com/concrete5-community-store/community_store/commit/f4b8abf5d9f17be39410535422965e5482c3c9c7

With that fix in place, if you order a product that creates a new user account with an email address that is already associated with a member account, it will only apply the user groups to that account that it needs to, but it doesn't try to create the account again. 

When I manually removed the HTML required attribute, trying to progress an order without an email _or_ a valid email address still triggered a server side validation error:

<img width="603" alt="screen shot 2017-02-01 at 10 32 59 pm" src="https://cloud.githubusercontent.com/assets/1079600/22506083/76d6da60-e8ce-11e6-985d-9df5ca81b38d.png">

I couldn't progress through the checkout without a valid email address.

So you may need to describe in further detail the steps you've taken to encounter this error.

**Comment by edbeeny** [comment]
OK, I will do some further investigation and come up with a better explanation of the process,

**Comment by Mesuva** [comment]
Do you know if this is still an issue, or has this been resolved along the way?

**Comment by edbeeny** [comment]
No, for me this is still not fixed.
I am a registered user not logged in, I place an order as a guest and add the email address already registered.
The order looks like it has processed fine, but is no where to be seen within the dashboard. It seems to fall over when trying to create the new user, although the code is set not to create new user.

**Comment by Mesuva** [comment]
I can't seem to replicate this bug. What I tried was:

- I went into the members area of the dashboard and picked an existing member, taking note of their email address
- Logged out
- I put through an order for a product that doesn't create new user accounts. I entered the same email address noted earlier. I used the Stripe payment method in test mode.
- The order went through and I received the notification emails (both order and receipt)
- I logged in again and checked the dashboard finding my order against that email address

- I then logged out again and put through another order, with a product that creates a user account and puts the user into a user group. I entered in the same email address and put through the guest order again with Stripe
- The order went through the same way 
- I logged in and found the new order in the dashboard, this time the order also noted the associated user account
- Checking the user account showed they had entered the user group when the order was placed

Is there anything different to the above steps that you are doing to trigger this issue?  What version of community store and concrete5?
