### ISSUE TITLE
Billing/Shipping Countries

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#184]
Hi, Is there a way to limit which countries are displayed for Billing and Shipping Select fields?

**Comment by Mesuva** [comment]
Yes, if you edit the billing and shipping attributes under Member Attributes (/index.php/dashboard/users/attributes), the country restrictions should reflect in the checkout

**Comment by pvernaglia** [comment]
I don't see attributes there for countries.  I need to add them?  What type/handles?

**Comment by Mesuva** [comment]
I should have said billing and shipping _address_ attributes - the countries are part of the addresses

**Comment by pvernaglia** [comment]
Got it, thanks...   You all are doing a great job on this, big changes since the last time I looked at it.

**Comment by Mesuva** [comment]
Great to hear, more enhancements are on the horizon!
