### ISSUE TITLE
How to give 5% discount for each product in community store

### ISSUE THREAD

**Issue by ajithkumar841** [concrete5-community-store/community_store#185]
How to give 5% discount for each product in community store.

**Comment by Mesuva** [comment]
Something like this should achieve it (it's 5% off the total order, not each product, but that's mathematically

![screen shot 2017-02-11 at 1 42 24 pm](https://cloud.githubusercontent.com/assets/1079600/22850794/10590e54-f060-11e6-921e-c3b2b1f2ad3d.png)
 the same).
