### ISSUE TITLE
How to use Product Attributes on Order-Email

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#186]
Is there any documentation or hint on how to include a product attribute (text) to the confirmation Email sent out? 

Or send out a separate Email containing the attribute for each order? 

To get something like this:

[http://www.concrete5.org/marketplace/addons/ecommerce-special-instructions/](http://www.concrete5.org/marketplace/addons/ecommerce-special-instructions/)

Thanks for hints!

**Comment by Mesuva** [comment]
In the both the new_order_notification and order_receipt emails you'll see it loop through the items returned from $order->getOrderItems(), that's the items in the order.

For each item in the order you can call $product = $item->getProductObject(), which returns a product object.
Then to fetch an attribute you should be able to just go $product->getAttribute('yourhandle') to fetch the attribute value, the same as you would if it was a page with attributes.

The emails can be easily overridden by copying them into /application/mail and editing them there.

If you are wanting to send up separate emails, you'll need to create a new package that responds to the community store events, probable the on_community_store_payment_complete event.

There is a package within the community store github organisation that shows how to respond to events - https://github.com/concrete5-community-store/community_store_event_example

**Comment by cahueya** [comment]
I don't seem to get it running... that's what I put inside:

`<?php
        $pAttribs = $order->getOrderItems();
        if ($pAttribs) {
            foreach ($pAttribs as $pAttrib) {
                ?>
               <?= $productAttribute = $pAttrib->getProductObject(); ?>
                        
                <?php echo $productAttribute->getAttribute('infotext');
	
            }
        }
        ?>`
Am I messing up syntax somewhere?

**Comment by cahueya** [comment]
Ok, here is the code that works:

<?php $orderItems = $order->getOrderItems();
    foreach($orderItems as $item){
        $pObj = $item->getProductObject();
        if(is_object($pObj)){
		echo $pObj->getAttribute('attribute_name');
            }
        } ?>

**Comment by cahueya** [comment]
Ok, here is the code that did the job:

`<?php $orderItems = $order->getOrderItems();
    foreach($orderItems as $item){
        $pObj = $item->getProductObject();
        if(is_object($pObj)){
		echo $pObj->getAttribute('product_info');
            }
        } ?>`
