### ISSUE TITLE
Issue with billing and shipping address defaulting to US

### ISSUE THREAD

**Issue by qodo** [concrete5-community-store/community_store#187]
When going through the checkout with a UK customer I could see that the address kept defaulting to US. I have found an issue in the code that I will submit a fix for. It is currently using:

### /packages/community_store/single_pages/checkout.php 

```
in_array($country, $billingCountries)
in_array($country, $shippingCountries)
```

and should be using:

```
array_key_exists($country, $billingCountries)
array_key_exists($country, $shippingCountries)
```

Will create PR for this....

**Comment by Mesuva** [comment]
I've pulled this update from your master branch, in case there's a bit more time involved testing that branch
