### ISSUE TITLE
Product options should deal with prices differently

### ISSUE THREAD

**Issue by mnakalay** [concrete5-community-store/community_store#189]
Hi Ryan and others,

When creating product options and setting them so that each has a different price, we end up in a strange situation.

Say I'm selling shirts and I create 2 options for size and gender.
    * Size has XL, L, M, and SM as choices. Each has a different price
    * Gender has 2 options F and M and each has a price

Now if I select Male and then L the price I am given is the price for Large, the gender option is not taken into account anymore. The last option selected sets the price.

Wouldn't it be better if instead of setting a price for each option, we could set an amount to add or withdraw from the original price?

Say my product price is $15 and for the size option I have
XL => +2
L => +1.5
M => +1

Also, I wouldn't remove the possibility to just set a price as it is now. I would just make the code recognize that if the amount starts with a + sign, it should be taken as an added amount.

If the amount doesn't start with a + sign, take it literally.

Same reasoning could be applied to have minus (-) amounts

When selecting different options, javascript could read the value of each available option and show the price accordingly.

When going to check out, the calculation could easily be done as well.

Do you think this is reasonable and needed?

**Comment by mnakalay** [comment]
What can I say, I talked too fast... please don't waste your time here, I'm closing

**Comment by Mesuva** [comment]
![8wk58ji](https://cloud.githubusercontent.com/assets/1079600/23112332/7908d92c-f77f-11e6-9a0b-a8b19dc9d433.jpg)

**Comment by mnakalay** [comment]
![obcbwh0](https://cloud.githubusercontent.com/assets/1488833/23115204/4cf7f76c-f73b-11e6-860f-d8d6f47040e6.jpg)
