### ISSUE TITLE
Session::set happens after redirect - wrong data

### ISSUE THREAD

**Issue by Jozzeh** [concrete5-community-store/community_store#190]
**Notice : this issue was present on version 0.9.9.2**

(This issue only happens when programmatically adding products/discountcodes.)  
I set a discount code by clicking on a button and immediately after I redirect to the cart or checkout. 
When the button is clicked I run the code:
```
StoreDiscountCode::storeCartCode('10off');
//here redirect to cart or checkout
```
When redirected to the cart or checkout, the discount was not active.  
After some searching, I found it's because the value returned does not wait for the session to be set.  
Code storeCartCode method (src/CommunityStore/Discount/DiscountCode around line 168): 
```
public static function storeCartCode($code)
    {
        $rule = StoreDiscountRule::findDiscountRuleByCode($code);

        if (!empty($rule)) {
            Session::set('communitystore.code', $code);

            return true;
        }

        return false;
    }
```
So the value true was returned and the redirect happened before the value was actually set in the session.
When I change the Session::set line and force it to wait for an answer, it was solved.

```
public static function storeCartCode($code)
    {
        $rule = StoreDiscountRule::findDiscountRuleByCode($code);

        if (!empty($rule)) {
            $waitforit = Session::set('communitystore.code', $code);

            return true;
        }

        return false;
    }
```

This seems a small issue, however this also impact some other parts such as adding a product to the cart and redirecting immediately to the cart or checkout. (The product was not in the session yet, so the totals were incorrect) 

I haven't experienced this issue when adding a product to the cart like a normal user would do.
Should every Session::set be forced to wait... probably not. In 'normal use' this issue will not happen.   
However let's say we want to give the option to redirect to cart immediately after adding a product (instead of working with a modal)... then this might be a problem.

**Comment by Mesuva** [comment]
This is interesting, I'm not understanding why 
```
Session::set('communitystore.code', $code);
```
is going to behave any differently from
```
$waitforit = Session::set('communitystore.code', $code);
```

Programatically it's identical, so if this is the solution I'd be saying there's something else going on like a race condition (it's take time to write the session to the filesystem without a lock or similar).

**Comment by Jozzeh** [comment]
It is a very strange issue indeed...  
It probably is like you say... the session is still being written while the next page has already loaded. 

I'll spin up a DO Droplet and try to reproduce this on a new/clean server.  
Again, this was some custom coding, so in normal use this won't be an issue.
