### ISSUE TITLE
Product Categories

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#192]
Hi, How do I get the product category for a product, I was looking for something like $product->getCategory() but haven't found a way to retrieve it.  I would like to use it in the view.php of the community product block.  thanks

**Comment by Mesuva** [comment]
You would do with with $locations = $product->getLocations();

$locations is then an ArrayCollection that you can loop through, with each item being a ProductLocation object, which you can call getCollectionID() on to get the id of the page (the 'category').

**Comment by pvernaglia** [comment]
Thanks. that did the trick
