### ISSUE TITLE
Getting file URL from product attribute

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#193]
Could someone tell me what the correct syntax is for grabbing a file URL from a product attribute?

**Comment by Mesuva** [comment]
It should be the same as if it was a page attribute.

<?php 
$file = $product->getAttribute('file_handle');
?>

<a href="<?php echo $file->getDownloadURL(); ?>">Download</a>

**Comment by teknoziz** [comment]
Amazing what the correct syntax can do for you... thanks!
