### ISSUE TITLE
Sort by Attribute?

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#196]
I have created attributes for my products and want to be able to filter them on specific pages through the block. So, say I have 6 checkbox attributes and want to sort based on one of those, I could select Sort By -> Attribute -> Is Checked. It would be nice to be able to pick multiple attributes so you can make custom filters or even have some kind of drag and drop filter maker with conditionals and booleans. I assume one can do this programmatically of course, but it would be cool to have some basic functionality in the block.

**Comment by Mesuva** [comment]
I certainly would be nice to have this kind of filtering available, it's been discussed at length before.

It's sort of on the future plan, but it's actually very difficult to handle programmatically, as the attributes aren't exactly stored in a way that makes this easy. It might be something that gets added in the future alongside a rework of the attribute handling side of things.  I'd love to be able to spend a few hours and have this in place but I think it's a pretty enormous exercise. I'd love someone to prove me wrong though!

**Comment by teknoziz** [comment]
I was able to work around the issue, by making these attributes product groups instead, and that way I can use the block to filter them. It was just a coincidence these particular attributes worked in that fashion. So in the meantime, when you are looking at the Store -> Products, why not be able to use the product groups at the top in the same way as in the block, by being able to select more than one at a time, filtering the in the same way?
