### ISSUE TITLE
Programmatically checking product group

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#198]
Hello again. Looking for direction in programmatically checking for a product group (specifically the syntax). Any help would be appreciated. Thanks!

**Comment by Mesuva** [comment]
Checking that a product is in a product group?

A product object has a getGroups() function, which returns a list of ProductGroup objects.

$groups = $product->getGroups();

There is also a getGroupIDs() function, which is just the ids of the groups, not the objects.

If you are just wanting to fetch a ProductGroup and see if it exists you can go;

$group = Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductGroup::getByID(123)

if ($group){
echo 'group exists';
}

**Comment by teknoziz** [comment]
Can I fetch a ProductGroup by name?

**Comment by Mesuva** [comment]
There's a bit more to what I posted earlier, ProductGroups are just entities that define the _relationship_ between groups and products.. so my second example was wrong. It should be:

```
$group = Concrete\Package\CommunityStore\Src\CommunityStore\Group\Group::getByID(123)

if ($group){
    echo 'group exists';
}
```

Fortunately there is also a fetch by group name, so:
```
$group = Concrete\Package\CommunityStore\Src\CommunityStore\Group\Group::getByName('Cat Food')
```
