### ISSUE TITLE
BUG: Filter on more than one Product Group

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#199]
There seems to be a bug in the Product List block pagination, when you filter for more than one product group. When pagination is turned on, the page count defaults to the group with the largest number of responses, not the sum of the groups selected. For example, group 1 has 25 results, group 2 has 5 results, so it should only show 5 but instead it shows 25. Example below. 

http://dev.teknoziz.com:8888/lin_mfg2/preservatives/personal-care/whole-foods

**Comment by Mesuva** [comment]
Below the the 'Filter by Product Groups' selector on the Product List block there is the 'Matching' option, which changes between all or any of the groups.

Are you finding that this isn't being respected?
If you've got two groups, 25 and 5 items in each respectively, the _all_ function is going to only show items that are in both groups (so a maximum of 5 would be possible), whereas the _any_ should be matching both, so it'll show 30.

I haven't used this feature much so there could be issues, but I just wanted to check that it wasn't a misunderstanding of the feature first.

**Comment by teknoziz** [comment]
So yes the product list is respecting the filter, but the pagination is not. So I would see the five pages but the pagination acts as though there is 25.

**Comment by Mesuva** [comment]
Gotcha  - will investigate

**Comment by Mesuva** [comment]
I've created a fix for this

https://github.com/concrete5-community-store/community_store/pull/201

If you can, it would be great if you can give this and test and let me know if you hit any further problems.
It's only ProductList.php that is relevant to this bug, with only a few lines different.

**Comment by teknoziz** [comment]
I replaced the code and it seems to work! Thanks!

**Comment by Mesuva** [comment]
Great, I've merged in the fix for this
