### ISSUE TITLE
Unexpected Data Error on 8.1 when trying to install Stripe add-on

### ISSUE THREAD

**Issue by tooqinc** [concrete5-community-store/community_store#203]
Unfortunately, it's killed my site so I can't provide much in the way of environment info other than this was a 5.7 site that was updated to 5.8. I tried installing the Stripe add-on the other day, and missed the composer bit about the installer. I removed the add-on manually from the site and db. Today, tried with the composer stuff run first (I think?) and now I receive the following message on every page of the site (public and dashboard side):

**An unexpected error occurred.**
Declaration of Concrete\Package\CommunityStore\Src\Attribute\Key\StoreProductKey::add($type, $args, $pkg = false) should be compatible with Concrete\Core\Attribute\Key\Key::add($handle, $type, $args, $pkg = false)

I'm happy to try and answer questions, but I may have simply delete all the store related packages to recover the rest of the site.

**Comment by Mesuva** [comment]
I think you may be running an older version of Community Store - that error message would have been addressed by a change that was made last December:
https://github.com/concrete5-community-store/community_store/commit/3009367371b9c51dbca57e055ab0a5c9de359ea3#diff-297db354c5adf214b0ec82579c1bbbe7L131

It's not really anything to do with the Stripe add-on, so I'm wondering if you've inadvertently wound back the community store package in your install.

With both Community Store and the related Stripe add-on, note that there are 'releases' under their respective tabs, zips that you can download which are considered stable versions where composer has already been run. Setting things up with the master versions and running composer should also be fine, but it more for development purposes.

**Comment by tooqinc** [comment]
I would have created the site back in late Nov or early Dec for sure. I updated the site but not Store. Any idea how I un-break things enough to run an update? Or am I stuck deleting things from the database and rebuilding the store with an updated version?

**Comment by tooqinc** [comment]
{And today I learned about the releases tab - feeling like a very special idiot now). :)

**Comment by Mesuva** [comment]
Try just replacing the community_store package folder with the latest release and seeing if the error disappears - it should I believe.

**Comment by tooqinc** [comment]
This did in fact work for me and I'm back in business now. Thanks very much for your help!

**Comment by tooqinc** [comment]
Looks like we're not out of the woods yet. When trying to complete a payment, Store calls a deprecated function resulting in the attached error. The file shows a note that the call is deprecated as of 5.8. 
![screenshot 1](https://cloud.githubusercontent.com/assets/5984407/24087153/0554521e-0ce1-11e7-8a92-b8aa7f212ce2.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/5984407/24087155/07259c56-0ce1-11e7-9aa0-0e4e1221feb7.png)

**Comment by Mesuva** [comment]
I don't think this is to do with the Stripe add-on as such, it's some other bug to do with attributes and v8. 

Does this error on a fresh install of v8, with the latest community store packages installed?

**Comment by tooqinc** [comment]
Given that the site is 95% complete, I haven't tried on a clean install. I can, but it's time consuming, especially if rebuilding from scratch becomes my answer.

Is 5.7 to 8 not an expected upgrade path that should work?

**Comment by Mesuva** [comment]
Well the idea is that it _should_, but that doesn't mean it _does_ work correctly.

I'm not taking any 5.7 sites that are currently running community store and updating them to v8, I think with the changes to the underlying attributes system there is a lot to go wrong.

I could test updating a 5.7 site with community store to v8 and see what kinds of things happen, but I think these kind of errors are core related and not to do with community store - so I unfortunately wouldn't know how to fix them.

**Comment by tooqinc** [comment]
I was mistaken - this was not directly when processing a payment (that process shows a generic "Something went wrong" error). When clicking on an order in the dashboard, that's when the attribute error is displayed. It's not say the Stripe portion does not work, but rather that the processing back to the core Store appears broken in its current state.

As for updating, I guess the messaging here: https://www.concrete5.org/download is very misleading. "You must update to 5.7.5.11 before updating to 8.0." certainly makes it sound like a viable update path. I wouldn't have done it if that wasn't the case. I'm likely not the only one that will run into the issue. While I'm pretty certain it would not be an issue on a clean install of 5.8, as I mentioned, rebuilding a site that's completed with the exception of the eCommerce side of things isn't really a path I'm keen on.

Guess I'm back a square one. Thanks for your help.

**Comment by Mesuva** [comment]
It is frustrating. Most things in v8 have upgraded fine, but the legacy attributes have been quite an issue. I've only update a few sites from 5.7 to v8 myself, and only those that have been very simple, without add-ons.

To be clear, I don't think this has anything to do at all with the Stripe add-on, I think it's just co-incidental that you were using it. It's to do with the display of the order attributes, i.e. the name, address, etc.

This might be one to flag with Andrew at concrete5 - errors like this are still core errors that I'm sure he'd like to solve.

**Comment by tooqinc** [comment]
Submitted issue on Concrete5 - cross referencing here. https://www.concrete5.org/developers/bugs/8-1-0/attribute-issue-with-5.7-to-version-8-updated-site 

> To be clear, I don't think this has anything to do at all with the Stripe add-on

We are agreed on this. It's either the core or the ability of Store to handle the payment response.

**Comment by tooqinc** [comment]
Forgot to come back to this and report that I was able to solve the issue by uninstalling and reinstalling the package. There was a little rework involved in getting things set up again, but fortunately, it did not require me to recreate products again.

While ideally, things would work through the upgrade path, the fix is relatively simple here.

Thanks for your help on this.
