### ISSUE TITLE
Search by attribute and variation

### ISSUE THREAD

**Issue by morganstar** [concrete5-community-store/community_store#205]
Is there a way to use ProductList to search based on product variations and product attributes?

I have Community Store setup for selling shoes, with a product attribute called "sex" for male/female and product variations for each size of shoe.  I'm working on a search handler and using the CommunityProductList block as my example.

If I try to filter a ProductList by the attribute, using **$products->filterByAttribute('sex', 'm');**, I get:

`An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p WHERE (ak_sex LIKE ?) AND (pActive = 1) GROUP BY p.pID ORDER BY pName asc' with params ["%\nm\n%"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ak_sex' in 'where clause'`

Is there something I'm missing that needs to be done so attribute based searches work?

Additionally, I don't see a way to filter by product variations; is that possible?

**Comment by Mesuva** [comment]
I don't believe this will work at the moment, the ProductList query isn't set up enough to handle the attributes.

I think this is a case of adding some further tables in to the query, it's just been a fairly complex query to get right in the first place. I'll try to look at this soon as attribute filtering is pretty damn useful to have, as illustrated by your example. If we could have this on the ProductList class, other ideas of being able to do advanced searching and filtering becomes possible.

Pages appear to have the table CollectionSearchIndexAttributes to be able to quickly look up attribute values, I think the PageList class does a simple join with it. The question/challenge is whether there is something automatically created for _product_ attributes, or whether a table like this needs to be generated.

**Comment by Mesuva** [comment]
A recent PR by @JeRoNZ has added in this filter - when the update happens it doesn't go an reindex everything, but I believe a simple save of a product will start populating the CommunityStoreProductSearchIndexAttributes table.
