### ISSUE TITLE
Timeout & Max Input Variables Exceeds 1000 Error When Saving Product Details

### ISSUE THREAD

**Issue by JeRoNZ** [concrete5-community-store/community_store#207]
I have added my first product, and set up approx 15 options (if there was a multi select option, there would be a lot less). I find that when saving the product details, I get a timeout after 30 seconds. This is on an 8 core blade server, 8GB of ram and a similarly juicy separate MySQL server. This is with PHP 7.0.15, current load average is 0.1. In addition I am seeing this in the error log:

PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0.

So, I increased it to **5000**, but:
[16-Mar-2017 13:25:42 Pacific/Auckland] PHP Warning:  Unknown: Input variables exceeded 5000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0
[16-Mar-2017 13:26:13 Pacific/Auckland] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/packages/concrete5.7.5.13/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php
on line 790.

I am unsure exactly how many $_POST vars are being sent, but there's a very long list when I look at the request with Charles proxy.

**Comment by Mesuva** [comment]
Have you got the 'Options have different prices, SKUs or stock levels' checkbox ticked for this product?

When you've got, say 2 options and each has three options values, you'll end up with four different variations of the product that you can configure (2x2).

If you've got 5 different options, each with 5 different options, you'll end up with 3125... (5x5x5x5x5)..

So if you've got 15 different options, event if you've got only 2 options each, you'll have 2^15, so 32 thousand different combos... which is obviously a problem and the source of all the POST vars.  The variations for a product can work for a handful, but not very large amounts. 

If you've accidentally ticked it with that many options, you may need to manually uncheck if via the database and reload the page.

It also could be showing the combinations regardless of the checkbox, which then is a bug.
I think this code needs something to prevent this kind of variation blowout from happening too.

**Comment by JeRoNZ** [comment]
"Options have different prices, SKUs or stock levels" is UNCHECKED
I have six text inputs, and 9 option lists. one option list has three values, the others all have two - what they really need to be is a checkbox. In this instance none of the options affect pricing they are really all informational fields.

I haven't looked at the code, but maybe there's a JS array somewhere that's getting inflated possibly as a result of sorting the options via drag/drop? I upped the timeout to 60 seconds, and it exceeded that, so that's not great.

**Comment by Mesuva** [comment]
I think what might be happening is that the list of variations is being added to page _in case_ the checkbox is ticked.

If you view the product edit page and check the box, do you get an enormous number of combos?

**Comment by JeRoNZ** [comment]
Absolutely. A rather insanely long list that makes my browser think for a few seconds.
A checkbox option akin to the text entry was actually all I wanted -  X 9

**Comment by Mesuva** [comment]
That's certainly not good.

I think there's two things that need to happen here:
- The variation list needs to only be created if the checkbox is in a saved state when the page opens up (which I think should be easy to change). Perhaps a warning or a limit.
- The addition of a checkbox option type. I'm not actually sure why I didn't add this in earlier.

A more complex solution might be the addition of a flag against each option type to define if it makes a different to the product, so it's not considered as part of the variation combinations.

I can't promise anything, but I _may_ have time to look at the first two items at the end of this week.

**Comment by JeRoNZ** [comment]
I did wonder if adding a switch to the option to determine if affects stock holding was the way to go, and I guess long term it is. Good to be on the same page.

A checkbox style option that acts like a text field would be fantastic. It's not urgent since I've managed to set the products up OK, even with the timeouts and warnings. I guess the product and options are updated before anything else times out. Don't go busting a gut.

**Comment by mnakalay** [comment]
> A rather insanely long list that makes my browser think for a few seconds
About that, I noticed in the code that you have a for loop going throughout the options and for each you get the template, replace variables and append it to the options container.
It would be more efficient to append all options in bulk at the end of the for loop instead of after each iteration. Or at least in batches of 50 or something.

**Comment by Mesuva** [comment]
I've finished up adding in the the checkbox option type, plus the ability to exclude options from variations.

https://github.com/concrete5-community-store/community_store/pull/236

If anyone has the time to glance over this before I merge it in it would be appreciated

**Comment by JeRoNZ** [comment]
I'm getting an error

"An issue has occured (sic) adding the product to the cart. You may be missing required information."

I have one product

One checkbox attribute
One option list, (colour with three colours)

If I set "Variations Options have different prices, SKUs or stock levels" to ON, the error occurs when adding to cart.

If I turn it off, it adds correctly.

**Comment by Mesuva** [comment]
@JeRoNZ thanks for this, will review

**Comment by Mesuva** [comment]
I've pushed up some updates to the variation extras branch:
https://github.com/concrete5-community-store/community_store/pull/236

You'll need to trigger an update to the package.

**Comment by Mesuva** [comment]
This should be resolved with the merge of the variation changes. You can now selectively pick what options are part of the variations, avoiding a stupidly long list of combinations.
