### ISSUE TITLE
Floating-point problem with tax rates

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#208]
I have been testing around with invoice templates and found some calculation problems that might be due to rounding of taxes.

I've set up to enter the price of products without taxes and the two tax rates required in germany: 7% and 19%

With two test products for (end price 10 and 25eur), I entered 8.40eur (+19% = 10eur) and 23,26 (+7% = 25eur).

I pulled the tax amounts from DB and it calculates correctly to 10 and 25eur BUT the $order->getTotal delivers 35,99eur (1eur is shipping).

As I can see, the prices are set with two decimals but tax amounts are much longer numbers - I suppose it must be about rounding somewhere.

**Comment by Mesuva** [comment]
Yeah, floating point maths is often a mess. Sounds like there needs to be a little bit of rounding earlier on in the tax calculations.. the tax amounts in the db shouldn't be to a high precision, they should be to even cents

**Comment by Mesuva** [comment]
I'd put in some extra rounding ages ago, but I forgot to merge it in.
It's here: https://github.com/concrete5-community-store/community_store/commit/f05961e5eba7ddb577589b2efca47b8d49d6dc35

I'm pretty confident that this will help with this issue.
