### ISSUE TITLE
E-mail template - wrong shipping address generated

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#210]
In the file /community_store/mail/new_order_notification.php

line 47 the shipping address is generated ($shippingaddress = StoreCustomer::formatAddress($shippingaddress);) but in line 48 the billing address is printed (echo nl2br($address);) it should have been (echo nl2br($shippingaddress);)

and the file /community_store/mail/order_receipt.php the same thing.

**Comment by Mesuva** [comment]
Fixed by https://github.com/concrete5-community-store/community_store/commit/b6f49258ca0ef6b6cb70c38100880ba72b3887e6

I'm a bit shocked this hasn't been picked up before. Well spotted!

**Comment by MichaelMaar** [comment]
Me too... strange that no one has complained...
