### ISSUE TITLE
Error with latest c5 Github version

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#216]
Hello there, I just encountered this error while testing around with the latest github error:

 Whoops \ Exception \ ErrorException (E_RECOVERABLE_ERROR)
Argument 1 passed to Concrete\Core\Mail\Service::__construct() must be an instance of Concrete\Core\Application\Application, none given, called in /Applications/MAMP/htdocs/nbc2/packages/community_store/src/CommunityStore/Order/Order.php on line 836 and defined

**Comment by Mesuva** [comment]
Are you saying this errors with the latest version from github of concrete5?
Or is this just on v8.1.0 with the master branch of community store?

That line hasn't been changed for quite some time, but it may need to be instead
$mh = Core::make('mail');

**Comment by cahueya** [comment]
This is from latest GitHub version: 8.2.0a2

Ok...

**Comment by Mesuva** [comment]
But I don't know if that replacement line would work in v5.7, so it may need a bit more adjustment. Good to spot this issue ahead of time.

**Comment by cahueya** [comment]
With the latest GitHub version of c5 (8.2.0b1), opening a product or adding a new one will result in this error:
Call to undefined method Punic\Calendar::tryConvertIsoToPhpFormat()

in

concrete/src/Localization/Service/Date.php

this function:

 public function getPHPDatePattern()
    {
        $isoFormat = \Punic\Calendar::getDateFormat('short');
        $result = \Punic\Calendar::tryConvertIsoToPhpFormat($isoFormat);
        if ($result === null) {
            $result = t(/*i18n: Short date format: see http://www.php.net/manual/en/function.date.php */ 'n/j/Y');
        }

**Comment by cahueya** [comment]
Ok - just set up a clean installation and it works. Whyever it failed when upgrading...

**Comment by mlocati** [comment]
> Call to undefined method Punic\Calendar::tryConvertIsoToPhpFormat()

I guess you just needed to run `composer install` to update the dependencies

**Comment by cahueya** [comment]
I had done that but still... well, a clean new install made it work but the first problem above still persists - orders will not be processed.

**Comment by Mesuva** [comment]
I might close this for now, as soon as 8.2 appears to be released we can revisit and check
