### ISSUE TITLE
Tax on product options calculated incorrectly

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#219]
There seems to be an issue with individually priced product options where the option price is ignored and tax is calculated on the base product price.

For example if I have a product with a base price of £4 and a large size with a price of £20 my tax calculation is given as:

    Items Subtotal: £20.00
    VAT (UK): £0.80
    Grand Total: £20.80

When in fact it should be:

    Items Subtotal: £20.00
    VAT (UK): £4.00
    Grand Total: £24.00

(UK VAT is 20%)

If I do not include a base price and give prices only to options then no tax is charged on the product at all.

**Comment by Mesuva** [comment]
Thanks for finding this, it's a critical bug!

I've pushed up a fix via https://github.com/concrete5-community-store/community_store/commit/32df03eec98c0301b4f7246fb1e32a9a6038e0c8

I'm pretty confident that it fixed it, but please let me know if you find otherwise.

**Comment by katalysis** [comment]
That seems to be working - many thnaks for the speedy fix.
