### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by IdeaSponge** [concrete5-community-store/community_store#222]
Started getting this error on src/CommunityStore/Order/Order.php on line 407, when viewing the Dashboard/Store page. All other Store pages are displaying just fine. I got this error after processing an Order using the Invoice payment method.

I have one Tax rate set and the default is set to use that Tax Rate. I initially set the Tax rate to include shipping, not sure if that impacts this. I changed the tax rate to just work on cart total but the error persists.

I added a \Log entry to show me the content of $tax and the 'amountIncluded' value is empty.

Using c5 8.1.0

**Comment by IdeaSponge** [comment]
I was able to apply a temp fix with this code.
It's a bit sloppy since I am not quite sure what is supposed to be in that variable.

` if(!is_float($tax['amountIncluded']) || !is_int($tax['amountIncluded']) || !is_double($tax['amountIncluded']))`
`        $tax['amountIncluded'] = 0;`
`$taxTotal = $taxTotal + $tax['amountIncluded'];`

**Comment by Mesuva** [comment]
would something like:
```
$tax['amountIncluded'] = (float)$tax['amountIncluded'];
```
be enough to enforce the correct type here?

I'm confused by the error, I'm wondering if it's a PHP7 strictness thing.

**Comment by IdeaSponge** [comment]
After removing my fix and adding that it worked. My environment was provisioned by the Forge SASS and is using PHP7.1, so you are probably right.

**Comment by Mesuva** [comment]
Cheers, I've pushed a commit to address this.
