### ISSUE TITLE
Double attribute handles in DB

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#223]
I stumbled over an error after changing user attributes settings (display in public profile) - then started looking at the database and found that the user attributes that come with Community Store are there twice:

billing_address with akID82 and well as akID91 just a few lines lower in table "AttributeKeys".

I suppose this is not meant to be like this and may cause problems.

I am working with the latest release of CommunityStore and the latest github version of c5.

**Comment by Mesuva** [comment]
There are actually two sets of attributes for billing address, one associated with users/customers and one with orders. So I actually would expect to see it listed twice.
