### ISSUE TITLE
Which version of community_store_stripe?

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#226]
The core community_store package README explicitly recommends using a release version for production. How about community_store_stripe. I see that the master branch is currently at v1.0.4, with the last change 2 months ago. Is there any reason not to use v1.0.4?

**Comment by Mesuva** [comment]
I'd be suggesting the use of v1.0.4 - the fact there isn't a matching release for it is simply down to me either forgetting to create one, or there wasn't something critical in the last few updates.

**Comment by dbuonomo** [comment]
Ok, makes sense. Thanks.
