### ISSUE TITLE
Are custom product attributes copied into order items?

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#228]
It appears that when an order is completed, custom product attributes are not copied and stored with each individual line item. Is this the case?

I have a number of custom product attributes and would prefer not to create a new SKU if any of these custom attributes need to be changed. In other words, I want the custom product attribute to be captured  and stored with the line item at the time the order is processed.

**Comment by Mesuva** [comment]
I don't believe the product attributes are copied across and saved against the order.
Perhaps this is a case of using a product option, one of the 'hidden' types instead?

**Comment by dbuonomo** [comment]
This became important when generating an export file for fulfillment. The concern is that the product attributes are updated, affecting orders already processed.

For our use case we'll need to stick with custom attributes. I'll look to see what's involved in finding a way to copy these to the order record as well.
