### ISSUE TITLE
Product, Product Link and Utility Links blocks need UI enhancements

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#23]
All three blocks in the Store have acceptable add/edit forms, but these could do with some tidying.

Both the Product and Product Link blocks may benefit from some tabs, or at least two columns.
(I dislike long blocks that have to scroll to show options).

Some of the option labels could also be improved.

**Comment by mnakalay** [comment]
the product block has some code commented out (line 128 of form.php) that is not commented out properly so some PHP code is showing on the edit screen.

Can that be simply deleted or do you need it for future reference?

**Comment by Mesuva** [comment]
That can be deleted I think. I commented it out as I didn't think they'd ever be a need to list product groups against products that way. Pretty easy to add back in.

**Comment by mnakalay** [comment]
Other question: those screens are not that big. Wouldn't making the edit screen wider make it look better and less cramped rather than using tabs for a small number of options?

**Comment by Mesuva** [comment]
@mnakalay Making them wider would totally help. I'm not a big fan of tabs, especially when there might only be two of them.

**Comment by Mesuva** [comment]
Addressed by #43
