### ISSUE TITLE
"on_community_store_order" Event working multiple times.

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#230]
Hi
In my project i place order via custom code but "on_community_store_order" event working multiple times for me.
can you tell my which method in \community_store\src\CommunityStore\Order\Order.php will trigger this event ?

**Comment by Mesuva** [comment]
_on_community_store_order_ should only fire when an order is created, regardless of payment status, then when something is actually marked as paid for _on_community_store_payment_complete_ fires.

The https://github.com/concrete5-community-store/community_store_event_example package should be useful to debug here, as it should create log entries for all events that are fired by community store
