### ISSUE TITLE
Add to Cart

### ISSUE THREAD

**Issue by tarilotta** [concrete5-community-store/community_store#231]
When adding a product to the cart I get a perpetual loading spinner overlay. All caching off. Using C5 8.1

**Comment by Mesuva** [comment]
You'll need to use something like Chrome's Web Inspector to see what javascript error message you are getting, or what error is being thrown by the call to the server. What you can do is open up the network tab and take a look at the request made when you add the product to the cart - the actual data returned can be investigated
