### ISSUE TITLE
Checkout errro

### ISSUE THREAD

**Issue by amatech-andrew** [concrete5-community-store/community_store#233]
Hi Everyone, 

First of all, I just want to say how great this package is.  It was easy to setup and customize.  

The one issue I have is that on Guest checkout, if there is an error with the Credit Card entry, the page reloads and the guest has to re-enter everything.  On top of that, the user gets no feedback as to what went wrong.  There is no Error message displayed at all.  

Is there a reason for this?  I looked through the code and I can see the if statement where it get broken up and all guest checkouts get loaded separately regardless of errors.  I was wondering if there is a good way to at least display the error (If the guest has to type everything in again, so be it)

Thank you very much!

**Comment by IdeaSponge** [comment]
Do you have error handling turned on in c5? Check your logs also to see what error is being created.

**Comment by Mesuva** [comment]
Errors _should_ be displayed for credit card gateway issues. If they aren't, it's normally a sign of a javascript error on the checkout page breaking the credit card form itself from working as intended with the gateway.

I'd check the javascript console for errors

**Comment by amatech-andrew** [comment]
Thanks for the replies everyone.  I looked at the errors and it is correct that there is a Javascript issue and I believe the issue is stemming from the checkout.php single page.  

The Javascript error is 'communityStore.js:265 Uncaught TypeError: Cannot read property 'top' of undefined and refers to this block: 

`loadViaHash: function () {
        var hash = window.location.hash;
        hash = hash.replace('#', '');
        if (hash != "") {
            $(".store-active-form-group").removeClass('store-active-form-group');
            var pane = $("#store-checkout-form-group-" + hash);
            pane.addClass('store-active-form-group');

            $('html, body').animate({
                scrollTop: pane.offset().top
            });
        }
    },`


The Javsacript issue is that it cannot find the store-checkout-form-group-payment div.  This is because in line 21 of the Checkout.php single page there is the following if statement:

`if ($customer->isGuest() && ($requiresLogin || $guestCheckout == 'off' || ($guestCheckout == 'option' && $_GET['guest'] != '1'))) {`

This line basically just renders the guest screen again and does not render the rest of the form.  

When a registered user does this, it loads the correct elements in the DOM and no Javascript errors are present. 

Sorry to be so long winded... I was just trying to explain everything the best I could.  I am sure there could be something that could be done to that if statement, but I didnt just want to make changes before putting it out to the community.  

Thanks again everyone!!

**Comment by Mesuva** [comment]
I'm having trouble discovering this particular javascript error, but I'm totally seeing the original issue you described. This bit of code needs some attention, it's perhaps been missed because I think most people operate stores in purely guest mode. 

So a temporary work around is to set 'Guest Checkout' to 'always' in the store config.
