### ISSUE TITLE
Community Store error installation

### ISSUE THREAD

**Issue by wells00** [concrete5-community-store/community_store#235]
I've completed my site, now I want to install "community store" but this is the error that returns:

I'm trying it on other sites is all right.
Please help me, it is necessary.

Thank you!!!

Whoops \ Exception \ ErrorException (E_ERROR)
Call to a member function setAttribute() on null

Whoops\Exception\ErrorException 
…/­src/­Page/­Collection/­Collection.php467

.../concrete/src/Page/Collection/Collection.php
![collection php-467](https://cloud.githubusercontent.com/assets/28661748/26470624/b3793d0e-419e-11e7-8730-9a27a235953c.png)

Environment & details:

Concrete5
Version	8.1.0
Installed Version	8.1.0
Concrete Configuration
concrete.version	8.1.0
concrete.version_installed	8.1.0
concrete.version_db	20170123000000
concrete.installed	true
concrete.locale	it_IT
concrete.charset	UTF-8
concrete.maintenance_mode	false
concrete.debug.display_errors	true
concrete.debug.detail	debug
concrete.proxy.host	null
concrete.proxy.port	null
concrete.proxy.user	null
concrete.proxy.password	null
concrete.upload.extensions	*.flv;*.jpg;*.gif;*.jpeg;*.ico;*.docx;*.xla;*.png;*.psd;*.swf;*.doc;*.txt;*.xls;*.xlsx;*.csv;*.pdf;*.tiff;*.rtf;*.m4a;*.mov;*.wmv;*.mpeg;*.mpg;*.wav;*.3gp;*.avi;*.m4v;*.mp4;*.mp3;*.qt;*.ppt;*.pptx;*.kml;*.xml;*.svg;*.webm;*.ogg;*.ogv
concrete.interface.panel.page_relations	false
concrete.mail.method	PHP_MAIL
concrete.mail.methods.smtp.server	
concrete.mail.methods.smtp.port	
concrete.mail.methods.smtp.username	
concrete.mail.methods.smtp.password	
concrete.mail.methods.smtp.encryption	
concrete.cache.enabled	true
concrete.cache.lifetime	21600
concrete.cache.overrides	true
concrete.cache.blocks	true
concrete.cache.assets	false
concrete.cache.theme_css	true
concrete.cache.pages	false
concrete.cache.doctrine_dev_mode	false
concrete.cache.full_page_lifetime	default
concrete.cache.full_page_lifetime_value	null
concrete.cache.full_contents_assets_hash	false
concrete.cache.directory	/web/htdocs/www.tenutavenezia.it/home/application/files/cache
concrete.cache.directory_relative	null
concrete.cache.page.directory	/web/htdocs/www.tenutavenezia.it/home/application/files/cache/pages
concrete.cache.page.adapter	file
concrete.cache.environment.file	environment.cache
concrete.cache.levels.expensive.drivers.core_ephemeral.class	\Stash\Driver\Ephemeral
concrete.cache.levels.expensive.drivers.core_filesystem.class	\Stash\Driver\FileSystem
concrete.cache.levels.expensive.drivers.core_filesystem.options.path	/web/htdocs/www.tenutavenezia.it/home/application/files/cache
concrete.cache.levels.expensive.drivers.core_filesystem.options.dirPermissions	493
concrete.cache.levels.expensive.drivers.core_filesystem.options.filePermissions	420
concrete.cache.levels.object.drivers.core_ephemeral.class	\Stash\Driver\Ephemeral
concrete.multilingual.redirect_home_to_default_locale	false
concrete.multilingual.use_browser_detected_locale	false
concrete.multilingual.default_locale	false
concrete.multilingual.default_source_locale	en_US
concrete.design.enable_custom	true
concrete.design.enable_layouts	true
concrete.log.emails	true
concrete.log.errors	true
concrete.log.spam	false
concrete.log.queries.log	false
concrete.log.queries.clear_on_reload	false
concrete.jobs.enable_scheduling	true
concrete.filesystem.temp_directory	null
concrete.filesystem.permissions.file	420
concrete.filesystem.permissions.directory	493
concrete.email.enabled	true
concrete.email.default.address	concrete5-noreply@concrete5
concrete.email.default.name	
concrete.email.form_block.address	false
concrete.email.forgot_password.address	null
concrete.email.forgot_password.name	null
concrete.email.validate_registration.address	null
concrete.email.validate_registration.name	null
concrete.marketplace.enabled	true
concrete.marketplace.request_timeout	30
concrete.marketplace.token	null
concrete.marketplace.site_token	null
concrete.marketplace.intelligent_search	true
concrete.marketplace.log_requests	false
concrete.external.intelligent_search_help	true
concrete.external.news_overlay	false
concrete.external.news	true
concrete.misc.user_timezones	false
concrete.misc.package_backup_directory	/web/htdocs/www.tenutavenezia.it/home/application/files/trash
concrete.misc.enable_progressive_page_reindex	true
concrete.misc.mobile_theme_id	0
concrete.misc.sitemap_approve_immediately	true
concrete.misc.enable_translate_locale_en_us	false
concrete.misc.page_search_index_lifetime	259200
concrete.misc.enable_trash_can	true
concrete.misc.app_version_display_in_header	true
concrete.misc.default_jpeg_image_compression	80
concrete.misc.help_overlay	true
concrete.misc.require_version_comments	false
concrete.misc.login_redirect	HOMEPAGE
concrete.misc.access_entity_updated	1495453637
concrete.misc.latest_version	8.1.0
concrete.misc.login_redirect_cid	0
concrete.misc.do_page_reindex_check	false
concrete.theme.compress_preprocessor_output	true
concrete.theme.generate_less_sourcemap	false
concrete.updates.enable_auto_update_packages	false
concrete.updates.enable_permissions_protection	true
concrete.updates.check_threshold	172800
concrete.updates.services.get_available_updates	http://www.concrete5.org/tools/update_core
concrete.updates.services.inspect_update	http://www.concrete5.org/tools/inspect_update
concrete.paths.trash	/!trash
concrete.paths.drafts	/!drafts
concrete.icons.page_template.width	120
concrete.icons.page_template.height	90
concrete.icons.theme_thumbnail.width	120
concrete.icons.theme_thumbnail.height	90
concrete.icons.file_manager_listing.handle	file_manager_listing
concrete.icons.file_manager_listing.width	60
concrete.icons.file_manager_listing.height	60
concrete.icons.file_manager_detail.handle	file_manager_detail
concrete.icons.file_manager_detail.width	400
concrete.icons.user_avatar.width	80
concrete.icons.user_avatar.height	80
concrete.icons.user_avatar.default	/concrete/images/avatar_none.png
concrete.file_manager.images.use_exif_data_to_rotate_images	false
concrete.file_manager.images.manipulation_library	gd
concrete.file_manager.results	10
concrete.search_users.results	10
concrete.sitemap_xml.file	sitemap.xml
concrete.sitemap_xml.frequency	weekly
concrete.sitemap_xml.priority	0.5
concrete.accessibility.toolbar_titles	false
concrete.accessibility.toolbar_large_font	false
concrete.accessibility.display_help_system	true
concrete.accessibility.toolbar_tooltips	true
concrete.i18n.choose_language_login	false
concrete.urls.concrete5	http://www.concrete5.org
concrete.urls.concrete5_secure	https://www.concrete5.org
concrete.urls.newsflow	http://newsflow.concrete5.org
concrete.urls.background_feed	//backgroundimages.concrete5.org/wallpaper
concrete.urls.background_feed_secure	https://backgroundimages.concrete5.org/wallpaper
concrete.urls.background_info	http://backgroundimages.concrete5.org/get_image_data.php
concrete.urls.videos	https://www.youtube.com/user/concrete5cms/videos
concrete.urls.help.developer	http://documentation.concrete5.org/developers
concrete.urls.help.user	http://documentation.concrete5.org/editors
concrete.urls.help.forum	http://www.concrete5.org/community/forums
concrete.urls.paths.menu_help_service	/tools/get_remote_help_list/
concrete.urls.paths.site_page	/private/sites
concrete.urls.paths.newsflow_slot_content	/tools/slot_content/
concrete.urls.paths.marketplace.connect	/marketplace/connect
concrete.urls.paths.marketplace.connect_success	/marketplace/connect/-/connected
concrete.urls.paths.marketplace.connect_validate	/marketplace/connect/-/validate
concrete.urls.paths.marketplace.connect_new_token	/marketplace/connect/-/generate_token
concrete.urls.paths.marketplace.checkout	/cart/-/add/
concrete.urls.paths.marketplace.purchases	/marketplace/connect/-/get_available_licenses
concrete.urls.paths.marketplace.item_information	/marketplace/connect/-/get_item_information
concrete.urls.paths.marketplace.item_free_license	/marketplace/connect/-/enable_free_license
concrete.urls.paths.marketplace.remote_item_list	/marketplace/
concrete.white_label.logo	false
concrete.white_label.name	false
concrete.white_label.dashboard_background	null
concrete.session.name	CONCRETE5
concrete.session.handler	file
concrete.session.save_path	null
concrete.session.max_lifetime	7200
concrete.session.cookie.cookie_path	false
concrete.session.cookie.cookie_lifetime	0
concrete.session.cookie.cookie_domain	false
concrete.session.cookie.cookie_secure	false
concrete.session.cookie.cookie_httponly	true
concrete.user.registration.enabled	false
concrete.user.registration.type	disabled
concrete.user.registration.captcha	true
concrete.user.registration.email_registration	false
concrete.user.registration.validate_email	false
concrete.user.registration.approval	false
concrete.user.registration.notification	false
concrete.user.group.badge.default_point_value	50
concrete.user.username.maximum	64
concrete.user.username.minimum	3
concrete.user.username.allow_spaces	false
concrete.user.password.maximum	128
concrete.user.password.minimum	5
concrete.user.password.hash_portable	false
concrete.user.password.hash_cost_log2	12
concrete.user.password.legacy_salt	
concrete.user.private_messages.throttle_max	20
concrete.user.private_messages.throttle_max_timespan	15
concrete.spam.whitelist_group	0
concrete.spam.notify_email	
concrete.security.session.invalidate_on_user_agent_mismatch	true
concrete.security.session.invalidate_on_ip_mismatch	true
concrete.security.ban.ip.enabled	true
concrete.security.ban.ip.attempts	5
concrete.security.ban.ip.time	300
concrete.security.ban.ip.length	10
concrete.security.misc.x_frame_options	SAMEORIGIN
concrete.permissions.forward_to_login	true
concrete.permissions.model	simple
concrete.seo.tracking.code	
concrete.seo.tracking.code_position	bottom
concrete.seo.exclude_words	a, an, as, at, before, but, by, for, from, is, in, into, like, of, off, on, onto, per, since, than, the, this, that, to, up, via, with
concrete.seo.url_rewriting	false
concrete.seo.url_rewriting_all	false
concrete.seo.redirect_to_canonical_url	false
concrete.seo.canonical_url	null
concrete.seo.canonical_ssl_url	null
concrete.seo.trailing_slash	false
concrete.seo.title_format	%2$s :: %1$s
concrete.seo.title_segment_separator	::
concrete.seo.page_path_separator	-
concrete.seo.group_name_separator	/
concrete.seo.segment_max_length	128
concrete.seo.paging_string	ccm_paging_p
concrete.statistics.track_downloads	true
concrete.limits.sitemap_pages	100
concrete.limits.delete_pages	100
concrete.limits.copy_pages	10
concrete.limits.page_search_index_batch	200
concrete.limits.job_queue_batch	10
concrete.limits.style_customizer.size_min	-50
concrete.limits.style_customizer.size_max	200
concrete.page.search.always_reindex	false
concrete.version_db_installed	20170123000000
concrete.site	Bed and Breakfast - Tenuta Venezia
GET Data empty
POST Data empty
Files empty
Cookies
CONCRETE5_LOGIN	1
CONCRETE5	o48p4qqm6e38nqn7ig1bhlpj73
CONCRETE5_INSTALL_TEST	1
_ga	GA1.2.652168701.1448817565
Session
_sf2_attributes	Array ( [accessEntitiesUpdated] => 1495745383 [multilingual_default_locale] => it_IT [uGroups] => Array ( [2] => 2 [1] => 1 ) [uID] => 1 [uName] => wells [uBlockTypesSet] => [uLastOnline] => 1495746022 [uTimezone] => [uDefaultLanguage] => it_IT [uLastPasswordChange] => 2017-05-22 14:19:27 [CLIENT_REMOTE_ADDR] => 93.150.225.15 [CLIENT_HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4 [uOnlineCheck] => 1495746045 [frontendPreviousPageID] => 1 )
_sf2_flashes	Array ( )
_sf2_meta	Array ( [u] => 1495746045 [c] => 1495745383 [l] => 0 )
Server/Request Data
PATH	/usr/local/bin:/usr/bin:/bin
UNIQUE_ID	WSdF-X8AAAEAAHcMY-cAAAAC
HTTP_HOST	www.tenutavenezia.it
HTTP_COOKIE	CONCRETE5_LOGIN=1; CONCRETE5=o48p4qqm6e38nqn7ig1bhlpj73; CONCRETE5_INSTALL_TEST=1; _ga=GA1.2.652168701.1448817565
HTTP_CONNECTION	keep-alive
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_USER_AGENT	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4
HTTP_REFERER	http://www.tenutavenezia.it/index.php/dashboard/extend/install
HTTP_ACCEPT_LANGUAGE	it-it
HTTP_ACCEPT_ENCODING	gzip, deflate
SERVER_SIGNATURE	
SERVER_SOFTWARE	Apache
SERVER_NAME	www.tenutavenezia.it
SERVER_ADDR	62.149.144.19
SERVER_PORT	80
REMOTE_ADDR	93.150.225.15
DOCUMENT_ROOT	/web/htdocs/www.tenutavenezia.it/home/
REQUEST_SCHEME	http
CONTEXT_PREFIX	
CONTEXT_DOCUMENT_ROOT	/web/htdocs/www.tenutavenezia.it/home/
SERVER_ADMIN	postmaster@tenutavenezia.it
SCRIPT_FILENAME	/web/htdocs/www.tenutavenezia.it/home/index.php
REMOTE_PORT	16655
GATEWAY_INTERFACE	CGI/1.1
SERVER_PROTOCOL	HTTP/1.1
REQUEST_METHOD	GET
QUERY_STRING	
REQUEST_URI	/index.php/dashboard/extend/install/install_package/community_store
SCRIPT_NAME	/index.php
PATH_INFO	/dashboard/extend/install/install_package/community_store
PATH_TRANSLATED	/web/htdocs/www.tenutavenezia.it/home/dashboard/extend/install/install_package/community_store
PHPRC	/web/htdocs/www.tenutavenezia.it/php.ini
PHP_SELF	/index.php/dashboard/extend/install/install_package/community_store
REQUEST_TIME_FLOAT	1495746045.4087
REQUEST_TIME	1495746045
Environment Variables empty
Registered Handlers
0. Concrete\Core\Error\Handler\ErrorHandler
1. Concrete\Core\Error\Handler\JsonErrorHandler

**Comment by Mesuva** [comment]
I'm not sure what this would be.
Do you have more of the error message that is thrown?
The final error message sometimes isn't useful, on the error screen you can often see a list the list of different calls leading up to the error. Can you see in that list the first place where community store is doing something?

**Comment by Mesuva** [comment]
Did you get this sorted?
