### ISSUE TITLE
How to redirect to cart page without Popup in Community store package

### ISSUE THREAD

**Issue by Deepu190** [concrete5-community-store/community_store#237]
How i can go to cart page without the pop up

**Comment by Mesuva** [comment]
I was able to achieve this by editing communityStore.js, around line 121:

If you add in:
```
window.location.href = CARTURL;
return false;
```
above the two lines:
communityStore.displayCart(res, true);
communityStore.refreshCartTotals();

The page should redirect to the cart page after adding the product.

What I'm not sure of is the best way to override this javascript without directly editing the copy of the file in the community store package.

You may be able to do a 'provideAsset' in a custom theme, or be able to include another javascript file that replaces the addToCart function within the communityStore object.

**Comment by mnakalay** [comment]
The best way to do this is to load a separate js file somwhere, either from your theme, or a package or any way you can.

In it you add:
`<script>
    (function(){
        var _addtocart = communityStore.addToCart;

        communityStore.addToCart = function () {
            // custom code goes here
            console.log('add to cart overridden');
            // then we call original function
            _addtocart.apply(this, arguments);
        }
    })();
</script>`

You need to modify this code though. In your case you don't want to call the original function after your custom code so you should just do it like this:

`<script>
    (function(){
        communityStore.addToCart = function () {
            // custom code goes here
            console.log('add to cart overridden');
        }
    })();
</script>`

And for the custom code you copy the whole original addTocart() function Ryan indicated with the proper modification he suggested.
