### ISSUE TITLE
Weights and Dimensions do not show

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#239]
When I first installed the cart they showed, then they stopped. I have not changed the coding at all.
`                    <?php if ($showDimensions) { ?>
                        <div class="store-product-dimensions">
                            <strong><?= t("Dimensions") ?>:</strong>
                            <?= $product->getDimensions() ?>
                            <?= Config::get('community_store.sizeUnit'); ?>
                        </div>
                    <?php } ?>

                    <?php if ($showWeight) { ?>
                        <div class="store-product-weight">
                            <strong><?= t("Weight") ?>:</strong>
                            <?= $product->getWeight() ?>
                            <?= Config::get('community_store.weightUnit'); ?>
                        </div>
                    <?php } ?>
`
If there is weights set in the products I would like the weight to show, if not, then not. Same with dimensions.

**Comment by Mesuva** [comment]
There is a 'Show Weight' checkbox on the Product block, have you got that checked on products?

**Comment by mdius** [comment]
Wow, I'm sorry.
Sometimes I am a little slow. LOL
