### ISSUE TITLE
Add to Cart button removed from product list

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#240]
Is there a way to remove the Add to Cart Button on the Product List when the product has options?

**Comment by Mesuva** [comment]
I'm sure you could do this with a custom template and a bit of conditional logic

**Comment by mdius** [comment]
I figured it out. Took several tries, but I got it. It wasn't hard I used:
`
                <?php if($showAddToCart){ ?>
				    <?php if ($product->hasVariations()) { ?>
					
                    <?php } else { ?>
`
