### ISSUE TITLE
Set "Active" as product default?

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#242]
Hi,
Is it possible to set products to be active when loaded rather than inactive?
Thanks
Dave

**Comment by madesimplemedia** [comment]
Actually don't worry. I got around this by adding a simple bit of jquery:

//Set Product to be Active by default:
$('#pActive').find('option').eq(0).prop('selected', true);

Also, in catalog mode it still insists on a price, so with this simple jquery it'll automatically set a minimal price:

//Set Price to be £1 by default:
if($('#pPrice').val() === '') {
     $('#pPrice').val('1');
}

**Comment by Mesuva** [comment]
Nice one.  The only other thing I would be suggesting is using the on_community_store_product_add event, to change the product after saving, but that's probably more work than your jquery here.

It might be nice to have these defaults adjustable

**Comment by madesimplemedia** [comment]
Yes I have used that add-on for sending emails when order status is changed, very useful.
Adjustable defaults would be great too.
