### ISSUE TITLE
How to upgrade to v1.1.5

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#243]
I am currently running Community Store v1.1.4. What is the recommended method for upgrading to v1.1.5? Is there a way to upgrade without uninstalling v1.1.4 first?

**Comment by Mesuva** [comment]
You should be able just go:
- take full site backup and database
- replace the community_store folder in packages with the new one
- trigger the upgrade of the package via the extend concrete5 section in the dashboard

**Comment by dbuonomo** [comment]
That worked. For some reason, I didn't get (or see) the upgrade option under Extend concrete5 the first time I tried.

Thank you.
