### ISSUE TITLE
Updates and 8.2

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#245]
Just wanted to let those following know that I've recently merged a few branches in 
https://github.com/concrete5-community-store/community_store/tree/develop
instead of going straight into master. There's quite a number of changes in this and I'd like to ensure that it's well tested and fixed before saying it's stable.

So if anyone has the chance to test this branch, especially to do with product variations that would be appreciated. I also haven't had the chance to test it on 8.2 yet. I think it's very close to a release candidate. 

If you are running an 8.1 site with Community Store and 8.2 comes out, just hold off updating until there's been a chance to fix bugs.

**Comment by MichaelMaar** [comment]
I will test it out in a few days. 8.2 still has some major issues and it brakes some add-ons (fx. the SuperMint3 theme). It also do not upgrade a 7 multilingual site to 8.2 yet.

But let's see in a few days where I will look at the Community Store against 8.2...

**Comment by Mesuva** [comment]
For anyone following and missed it:
https://www.concrete5.org/about/blog/community-blog/first-public-release-candidate-820-now-available

**Comment by Mesuva** [comment]
I've tested a clean install, so far I've only found one issue that required fixing:
https://github.com/concrete5-community-store/community_store/commit/91e8d49827a11a9683edc72bd2a834486c6d5a1d
(it should have been like this anyway)

**Comment by Mesuva** [comment]
Issues on 8.2 appear to have been all resolved.

I've put out a release after a fair bit of testing of updates:
https://github.com/concrete5-community-store/community_store/releases/tag/v1.2

**Comment by MichaelMaar** [comment]
Sorry I did not come back on this - Been busy debugging concrete5 8.2 when using it in multilingual setup.
I have been working on upgrade issue that did not work.
But I have now tried to install the store under concrete5 8.2 and got in trouble.
I'll open a new issue!
