### ISSUE TITLE
Billing address disappears after "paid status"

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#246]
To reproduce:

Latest Community Store release
Concrete5 8.2 Release Candidate

-> create a dummy user account
-> create a product that can be paid by invoice
-> buy the product, checkout everything

-> log in as admin, check orders
-> order displays correctly, details show billing address and such
-> change status to PAID
-> refresh order detail page
-> billing address is gone, customer name still there

This only happens when the purchase is done by a logged-in user, happens with admin user as well.

**Comment by Mesuva** [comment]
I can confirm this. 

Further to this, I'm noticing that if you place and order and then view the member's page in the dashboard, it errors to with trying to fetch the address details.
Then after you mark the order as paid (and the address details disappear from the order), and you return to the member page it works and displays the updated address.

What is unusual is that when an order is placed but not marked as paid, it's not supposed to update the user at all. It's as if at some points it's mixing up which attribute to use, the user one or the order related one (which have the same handle).

It's interesting that it's impacting the address attributes, and not the other attributes.
I think it may have something to do with the getAttributeValueObject and setAttribute functions within the Order class, or maybe the StoreOrderKey class. 

I'm pretty sure this same code worked on 8.1 and 5.7 though.

**Comment by cahueya** [comment]
Not sure if this is the same thing I saw in Issue#223 and couldnt quite understand. But the members page bug works here too, yes.

**Comment by Mesuva** [comment]
I just tested this on 8.1 - it's a problem there as well, the address is disappearing after the order is marked as paid, it's just not killing the members page.

I spent a lot of time last night with the debugger, but couldn't find anything. I think it may be an issue with the Address attribute type, or legacy attributes in general on v8.

**Comment by Mesuva** [comment]
With Andrew's update to 8.2 and a tweak to the Order code I believe I have this fixed in
https://github.com/concrete5-community-store/community_store/tree/develop

**Comment by cahueya** [comment]
I just tried and the problem seems to persists. Latest c5-dev and latest cs-dev versions.

**Comment by Mesuva** [comment]
Thanks for checking - I'll do another test run with a fresh dev install.

**Comment by Mesuva** [comment]
I've just downloaded a fresh copy of https://github.com/concrete5/concrete5/tree/develop
Installed it, and installed the https://github.com/concrete5-community-store/community_store/tree/develop branch of community store.

I placed an order with the normal Invoice method while logged in, then went to the dashboard and marked the order as paid - the order address details remained, and the address attributes against the member also stayed put. I also did a test as a guest where it creates a new member account and that also worked as expected.

Are you using the master or RC2 of concrete5 perhaps, instead of the _latest_ develop?

**Comment by cahueya** [comment]
Hm yes, I just pulled a new install too. Now it would not crash the user info page and will update the billing_address just fine when it is changed with a new order - but still the address will be removed from the order info after I change to "paid".

I tried all that with the admin account.

**Comment by Mesuva** [comment]
Ahh sorry, that's my fault. The very last fixed I did were still sitting in my local repo and hadn't been pushed up (SourceTree normally shows a number to show what's waiting to push but it wasn't there)

You should see a couple of extra commits from yesterdayL
https://github.com/concrete5-community-store/community_store/commits/develop
