### ISSUE TITLE
is cs working in concrete5.8 ?

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#248]

**Comment by AdamBassett** [comment]
Yes, I don't have anything in production yet but my dev seams solid.

**Comment by Mesuva** [comment]
Yes, it should work in v8

I've just been working on some minor issues with the upcoming 8.2, but I have those resolved I believe.
There is a develop branch I've been merging things into recently:
https://github.com/concrete5-community-store/community_store/tree/develop

The goal is to now test this on both 5.7 and 8.2 and make sure there aren't any new bugs (especially to do with product variations). Then put out a new community store release.

**Comment by midhun1993** [comment]
Great, thanks for the info
