### ISSUE TITLE
Filter by Product Groups Limit?

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#250]
I just tried to add a couple of Product Groups (aka Attributes) to my products, the first one added fine, and the second one which put the number to 13 seemed to as well. However it does not appear when you go and modify the block to filter by it. I tried changing the name, removing the underscore, deleting it, nothing. So, is the filter limited to 12 items?

**Comment by Mesuva** [comment]
Can you post a couple of code snippets of the filtering, just so I can test the same code?

**Comment by teknoziz** [comment]
I left the added attributes in place and here are the new pages:

This works attribute handle ("natural") #12
http://www.lincolnmfg-usa.com/preservatives/personal-care/natural

This doesn't attribute handle ("value_added") #13
http://www.lincolnmfg-usa.com/preservatives/personal-care/value-added

Is that enough?

**Comment by Mesuva** [comment]
I'm not seeing a limit to the number of groups.

I just put in 31 items, a-z, then aa-ae.
In the product group filter I can see all of them, as well as in the group list in the dashboard
![screen shot 2017-07-14 at 4 11 34 pm](https://user-images.githubusercontent.com/1079600/28201233-4d650056-68af-11e7-8a7f-0defa9c0cc6f.png)

Is this what you are referring to, or have I misunderstood the way you are filtering? Where I may be confused is your use of the word attributes - attributes and product groups aren't related

**Comment by teknoziz** [comment]
Ryan,

Apologies, you can remove this bug report. I was confusing the attributes with the product categories. Silly me. Carry on.

Sincerely,

David Zizza, TeKno Ziz
(617) 543-3971 cell    (978) 663-0951 home office
david@teknoziz.com <mailto:david@teknoziz.com>
teknoziz.com <http://teknoziz.com/>

**Comment by Mesuva** [comment]
No worries!
