### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'saleprice' of undefined"

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#256]
Got this JS error when changing a product option that has it's own price in conjunction with another option:

`Uncaught TypeError: Cannot read property 'saleprice' of undefined`

Using the latest version of Community Store.
It seems to point to this line of code:

`if (variationdata[ar.join('_')]['saleprice']) {`

**Comment by Mesuva** [comment]
This was a while back, not sure why I didn't comment - pretty sure it would have been addressed through updates, is it still an issue that you are aware of?
