### ISSUE TITLE
Shipping creates crazy taxes

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#258]
Hello,

I just stumbled on this error with shipping rates:

Setup
- Community Store latest release
- Taxes set to "Prices exlusive of taxes"
- Added some tax rates to different locations
- Added "table based" shipping

Now when a customer adds a product to the cart that included shipping, the shipping costs are calculated properly but a huge amount of taxes (much more than the value of the cart) is added to the equation.

I have not yet figured out where those huge numbers come from but they are added up to the total price, mutating a cart value of 20€ up to 150€.

This happens when a tax rate is set to work with "product sum + shipping".

The problem occurs also with the built-in shipping method.

**Comment by Mesuva** [comment]
I'm having trouble replicating this. This is CS1.2, concrete5.8.2 and a couple of tax rates enabled, using a flat rate shipping and exclusive tax entry.  Any other settings you can think of that might trigger this?

![screen shot 2017-08-01 at 8 47 33 am](https://user-images.githubusercontent.com/1079600/28802537-15b990e6-7696-11e7-803c-e88a890e8b93.png)

![screen shot 2017-08-01 at 8 49 58 am](https://user-images.githubusercontent.com/1079600/28802599-6e320898-7696-11e7-8dd9-be91bbb3c9bc.png)

**Comment by Mesuva** [comment]
Is this still occurring?
