### ISSUE TITLE
Wiki / Events

### ISSUE THREAD

**Issue by a3020** [concrete5-community-store/community_store#259]
Hi Ryan,

Would you mind adding this to the [Events](https://github.com/concrete5-community-store/community_store/wiki/Events) section in the Wiki?

**Sending Events to Slack**
The Slife Community Store package hooks into events triggered by Community Store and can send notifications to Slack: https://github.com/a3020/slife_community_store.

**Comment by Mesuva** [comment]
Hey that's a cool use for events. I've added that into the wiki.

**Comment by a3020** [comment]
Thanks 😄
