### ISSUE TITLE
Major crash during upgrade

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#261]
Upgrading from 1.1.3 to 1.2 get this:

An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p INNER JOIN CommunityStoreProductGroups g ON p.pID = g.pID and g.gID in (11,3) LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID WHERE (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID HAVING count(g.gID) = 2 ORDER BY pName asc': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lincolnmfg_usa_com.CommunityStoreProductSearchIndexAttributes' doesn't exist

Serious help required ASAP.

**Comment by Remo** [comment]
I think this table should be created on the fly if you change some of the product attributes.

**Comment by teknoziz** [comment]
Are you saying I should try to change something to see if it updates the table?

**Comment by teknoziz** [comment]
An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID GROUP BY p.pID ORDER BY pDateAdded desc': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lincolnmfg_usa_com.CommunityStoreProductSearchIndexAttributes' doesn't exist

**Comment by teknoziz** [comment]
Funny thing is, I updated my local copy of the site and it worked. Maybe it's a table case name issue?

**Comment by teknoziz** [comment]
Huh. Well I guess I fixed it, apparently the live site was using 1.1.6.1. I re-uploaded 1.2 and cleared the cache and it seems to have resolved itself. Thanks.
