### ISSUE TITLE
Demo or screenshots

### ISSUE THREAD

**Issue by systematic1** [concrete5-community-store/community_store#262]
Are there any live demos or a gallery of screenshots for Community Store?

**Comment by Mesuva** [comment]
There is this thread here with some examples:
https://github.com/concrete5-community-store/community_store/issues/111

But ultimately the best test is to just set up a new c5 install and give it test run. 
The styling of the shop frontend is bootstrap based, so it really just inherits the styling of Elemental or whatever bootstrap theme is enabled. Beyond that it's going to be a case of styling it yourself (with that arguably one of it's main goals - to be able to be custom themed)

**Comment by systematic1** [comment]
Thanks. I did find the list of sample sites. I might give it spin.
