### ISSUE TITLE
Checkout/Cart pages not themed

### ISSUE THREAD

**Issue by systematic1** [concrete5-community-store/community_store#266]
I have installed the Community Store and noticed that the checkout, cart, and complete pages are plain white unstyled content (with no template).  How do I make these pages use my theme?  I have tried modifying the application/config/app.php to enable the theme for these pages but it doesn't work.

Thanks,
Kelly

**Comment by Mesuva** [comment]
These are going to use your theme's view.php as the broader template - has that been correctly created?

**Comment by systematic1** [comment]
Mesuva,
Thank you, that did it!
