### ISSUE TITLE
Searchable Content

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#267]
I have noticed most people use the search bar and I see the searchable coding in the controller.php file, but it is not searching. I just updated my install to the latest version (1.2).

I thought it was working when I first installed this.

**Comment by Mesuva** [comment]
What search bar are you referring to here?
Do you need to re-index your site via the automated jobs?

**Comment by mdius** [comment]
It is the standard  search for Concrete 5.7.13.

I have it set to auto run my automated jobs through cron, and it is hanging up. 
So I manually updated it and it worked. I'm sorry to have posted this here when it should have went to the Concrete forum, it just wasn't searching the cart.

Thank you, I'll call this closed.
