### ISSUE TITLE
On Sale products, when options chosen the word "was" goes missing.

### ISSUE THREAD

**Issue by SpatialAnomaly** [concrete5-community-store/community_store#268]
Pretty minor bug but it's as the title states, when you have an on sale product and you first load the page with the product block on it, it displays correctly...

![missing-was-01](https://user-images.githubusercontent.com/1445491/29534517-4d5978f6-8684-11e7-9803-ce8c131c3f25.png)

Soon as you change an option that changes the price though, the word "was" vanishes and it squishes the prices together like so:

![missing-was-02](https://user-images.githubusercontent.com/1445491/29534546-67a20ade-8684-11e7-9dd2-30e490bd5baf.png)

**Comment by Mesuva** [comment]
I've pushed up a fix for this, feel free to close the issue if you confirm it works for you

**Comment by SpatialAnomaly** [comment]
Yeah, nailed it. Thanks!
