### ISSUE TITLE
Get 'Quantity must be greater than zero' when Quantity is Greater than 1

### ISSUE THREAD

**Issue by pixoinc** [concrete5-community-store/community_store#269]
I'm getting a 'Quantity must be greater than zero' message when adding a product to cart even when the quantity is set to 1 or greater than one.  The stock level is set to unlimited for the product and for the product quantity, when adding the product to the cart it doesn't seem to matter what number is chosen, that message still appears.  Any idea what might be causing that?

http://66.34.210.132/~fiverivers/index.php?cID=212

Running Community Store v.1.2.

Environment:
# concrete5 Version
Core Version - 8.2.1
Version Installed - 8.2.1
Database Version - 20170802000000

# concrete5 Packages
Community Store (1.2)

# concrete5 Overrides
blocks/community_product_list/templates/five-rivers/view.php, blocks/community_product_list/templates/five-rivers/view.css, blocks/community_product_list/templates/five-rivers, blocks/community_product_list/templates, blocks/community_product_list, blocks/autonav/templates/bootstrap-dropdown.php, blocks/autonav/templates, blocks/autonav, blocks/community_product/view.php, blocks/community_product/view.css, blocks/community_product, themes/fiverivers/elements/header_home.php, themes/fiverivers/elements/footer_bottom.php, themes/fiverivers/elements/header.php, themes/fiverivers/elements/header_top.php, themes/fiverivers/elements/footer.php, themes/fiverivers/elements, themes/fiverivers/css/styles.xml, themes/fiverivers/css/homeboxes-hover-transitions.css, themes/fiverivers/css/main.less, themes/fiverivers/css/build/mobile/navigation/slicknav.less, themes/fiverivers/css/build/mobile/navigation, themes/fiverivers/css/build/mobile, themes/fiverivers/css/build/bootstrap/bootstrap.css.map, themes/fiverivers/css/build/bootstrap/bootstrap.css, themes/fiverivers/css/build/bootstrap/bootstrap.min.css, themes/fiverivers/css/build/bootstrap, themes/fiverivers/css/build/blocks/autonav/templates/bootstrap-dropdown/nav.less, themes/fiverivers/css/build/blocks/autonav/templates/bootstrap-dropdown, themes/fiverivers/css/build/blocks/autonav/templates, themes/fiverivers/css/build/blocks/autonav, themes/fiverivers/css/build/blocks, themes/fiverivers/css/build, themes/fiverivers/css/presets/defaults.less, themes/fiverivers/css/presets, themes/fiverivers/css, themes/fiverivers/page_theme.php, themes/fiverivers/view.php, themes/fiverivers/default.php, themes/fiverivers/images/bubbles-bg.png, themes/fiverivers/images, themes/fiverivers/readme.txt, themes/fiverivers/full.php, themes/fiverivers/home.php, themes/fiverivers/thumbnail.png, themes/fiverivers/js/header.shrinkscroll.js, themes/fiverivers/js/theme.js, themes/fiverivers/js/modernizr-2.6.2.min.js, themes/fiverivers/js/bootstrap.min.js, themes/fiverivers/js/jquery.slicknav.js, themes/fiverivers/js/matchHeight.js, themes/fiverivers/js, themes/fiverivers/style.css, themes/fiverivers

# concrete5 Cache Settings
Block Cache - Off
Overrides Cache - On
Full Page Caching - Off
Full Page Cache Lifetime - Every 6 hours (default setting).

# Server Software
Apache

# Server API
cgi-fcgi

# PHP Version
5.6.31

# PHP Extensions
bcmath, calendar, cgi-fcgi, Core, ctype, curl, date, dom, ereg, fileinfo, filter, ftp, gd, hash, iconv, imagick, imap, ionCube Loader, json, libxml, mbstring, mcrypt, mysql, mysqli, mysqlnd, openssl, pcre, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, session, SimpleXML, soap, sockets, SPL, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib

# PHP Settings
max_execution_time - 30
log_errors_max_len - 1024
max_file_uploads - 20
max_input_nesting_level - 64
max_input_time - 60
max_input_vars - 1000
memory_limit - 64M
post_max_size - 8M
sql.safe_mode - Off
upload_max_filesize - 50M
mysql.max_links - Unlimited
mysql.max_persistent - Unlimited
mysqli.max_links - Unlimited
mysqli.max_persistent - Unlimited
pcre.backtrack_limit - 1000000
pcre.recursion_limit - 100000
session.cache_limiter - <i>no value</i>
session.gc_maxlifetime - 7200
soap.wsdl_cache_limit - 5

**Comment by Mesuva** [comment]
I think I know what this is. As you've overridden the product list block templates (which is fine), I think you've not got a required ID on a form tag that was added at some point, pretty sure as a fix to this issue.

See this line here:
https://github.com/concrete5-community-store/community_store/blob/master/blocks/community_product/view.php#L21

On your page on the form tag you've got id="five-rivers"
But it needs to be output with the code:
id="store-form-add-to-cart-<?= $product->getID() ?>"
The javascript uses this to find submitted form, and therefore the quantity value. It's not finding that value because it can't find the form.

**Comment by Mesuva** [comment]
I should mention that as a bit of a rough rule, any class or id that starts with _store-_ should be left in templates, in case it's used for javascript, or at least for consistency across projects. Anything that doesn't use that prefix is either bootstrap classes, or really not important, so can be removed/changed safely. 

This particular ID might not have been in the template when you first customised it though.

**Comment by pixoinc** [comment]
I believe this is the line that you are referring to:

    <form class="store-product store-product-block" id="store-form-add-to-cart-<?= $product->getID() ?>" data-product-id="<?= $product->getID() ?>" itemscope itemtype="http://schema.org/Product">

The code in the custom template is the same as in the package for that line and I see an id being applied in the source code.   Am I looking in the wrong place?

**Comment by Mesuva** [comment]
That's what it should be, but the output on your site for a product block is different to that.
From your overrides I believe you should be looking at /application/blocks/community_product/view.php
You basically need to find where **id="five-rivers"** is outputting, that's obviously custom code.

<img width="656" alt="screen shot 2017-08-24 at 8 17 49 am" src="https://user-images.githubusercontent.com/1079600/29641920-0b578466-88a5-11e7-9162-bc7099cc910f.png">

**Comment by pixoinc** [comment]
Thanks Ryan.  We got it working now.

**Comment by Mesuva** [comment]
Good to hear!
