### ISSUE TITLE
Setting permissions for access to Store admin features

### ISSUE THREAD

**Issue by systematic1** [concrete5-community-store/community_store#270]
I have searched throughout Concrete5 dashboard and cannot find how to control access (by user group) to the Store admin features.  I want to set up a new user group, give that group access to only manage the store.  How would I configure this?

**Comment by AdamBassett** [comment]
The way I control user access by group to the dashboard is through the sitemap.

Go to the sitemap and make sure the check box for 'Include System Pages in Sitemap' is checked. 
Then under dashboard remove the permissions to view/edit the sections you don't want each group to have. Simple click on each page in the dashboard and select permissions. You may need to logout and in the user to see the change.

**Comment by systematic1** [comment]
Thanks. I think this what I need.
