### ISSUE TITLE
Free Discount Wont Complete Order

### ISSUE THREAD

**Issue by LittleRainGames** [concrete5-community-store/community_store#271]
While trying to use a code that gives 100% off, instead being able to choose Paypal or Stripe. It automatically chooses stripe.

It forces you to input a credit card even though its $0.00 and after you input the card it says "Something went wrong with this transation."

**Comment by Mesuva** [comment]
This should be easy to fix, just a couple of updates to make:

- Make this change here to community store, https://github.com/concrete5-community-store/community_store/commit/b4073f47af6d3c6d904f9ce74c914ec54f25526a
- Make this change to the Stripe add-on, https://github.com/concrete5-community-store/community_store_stripe/commit/36d51270b15b1c5d22c4fa540fcdfe3bdc7673ec
- You then need to enable the Invoice payment option, but set a Maximum Order Value of 0 (you also might want to rename it to 'Free Order')

That then works as expected for me, the main problem was the Stripe add-on side of things

**Comment by LittleRainGames** [comment]
Just to clarify, this will only let the stripe add-on be used when its over 50 cents? And the invoice will be active only when its free?

Also I don't actually have the invoice files under /Methods/, the only thing there is stripe. My PayPal add-on doesn't seem to be there either.
