### ISSUE TITLE
Unlimited stock level with a non-zero stock count

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#273]
I have a requirement to track stock level in Community Store, but not have the actual stock level checked when adding an item to the cart. The stock level will be programmatically updated in table CommunityStoreProducts, and the "Unlimited" checkbox will be checked.

From what I can tell in code, stock level is ignored when adding an item to the cart as long as "Unlimited" is checked. Is this correct?

**Comment by Mesuva** [comment]
What you've described sounds correct - stock levels are only changed if they aren't marked as unlimited. If you look in OrderItem.php, you'll see around line 237 the code that handles this, calling updateProductQty.

You could potentially just comment out those checks and see how it behaves.
