### ISSUE TITLE
Product attributes in on_community_store_product_add

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store#274]
I am try to capture custom attributes for products in the on_community_store_product_add event as follows:

Events::addListener('on_community_store_product_add', function($event) {
    $product = $event->getProduct();
    $the_attribute = $product->getAttribute('some_attribute');

    ...
}

$the_attribute is returning as null/empty. Are product attributes included in the event object passed to the event handler?

**Comment by dbuonomo** [comment]
It appears that the on_community_store_product_add is dispatched before the custom product attributes are saved. In controllers/single_page/dashboard/store/products.php, the saveProduct() method call on line #306 is where the event is dispatched, just ahead of saving the custom attributes as well as other product properties:

305                 //save the product
306                 $product = StoreProduct::saveProduct($data);
307                 //save product attributes
308                 $aks = StoreProductKey::getList();
309                 foreach($aks as $uak) {
310                     $uak->saveAttributeForm($product);
311                 }
312                 //save images
313                 StoreProductImage::addImagesForProduct($data,$product);
314
315                 //save product groups
316                 StoreProductGroup::addGroupsForProduct($data,$product);
317                 ...

I don't know if it's possible move the event dispatch just after the attributes (and other product properties) are saved.

**Comment by Mesuva** [comment]
Here's a commit/branch that changes when the event is fired - it should be like this anywhere.

https://github.com/concrete5-community-store/community_store/commit/6fd54ca03902a66068c73ca19268b971220eea74

I've tested this with the demo events package, but let me know how you go with this and I can merge in.

**Comment by dbuonomo** [comment]
I tested this commit with v1.2 and I can now retrieve product attributes from the event.

I did notice that this commit also has changes from commit c5c1725 in src/CommunityStore/Product/Product.php ('Postponing doctrine flush during product save'). Any harm in including these as well?

**Comment by dbuonomo** [comment]
I did some additional testing, adding a new product and assigning it to one group. However, the product groups are not returned in the event object. In the event handler, I have the following:

$groups = $event->product->getGroups();

which returns null. I can see in the controller that the product groups are saved well before the event is dispatched, but no groups are returned.

323                 //save product groups
324                 StoreProductGroup::addGroupsForProduct($data,$product);
...
346                 // create product event and dispatch
347                 if (!$originalProduct) {
348                     $event = new StoreProductEvent($product);
349                     Events::dispatch('on_community_store_product_add', $event);
350                 } else {
351                     $event = new StoreProductEvent($originalProduct, $product);
352                     Events::dispatch('on_community_store_product_update', $event);
353                 }

**Comment by Mesuva** [comment]
I think this might be because the $product object isn't reinitialised with its newly related data when it's sent to the event dispatch. Functions like addGroupsForProduct just manipulates the database, but leaves the original $product object untouched. 

There might be ways to adjust this in community store, it could be a matter of just re-fetching the product again before doing the event dispatches. 

But I think this could be solved with whatever code you are using to handle the events by just using the product that is returned to find the product ID and then doing a Product::getByID($id) to fetch it fresh.

**Comment by Mesuva** [comment]
The commits from 'Postponing doctrine flush during product save' were intentionally included, it's stuff that I hoped could be tested at the same time.  (I was pretty confident of what it was doing, but didn't want to just include it into the master straight away)

**Comment by dbuonomo** [comment]
Ok, getting the product with Product::getByID($id) should work fine for my needs.

As usual, thanks for your feedback & support.
