### ISSUE TITLE
community_utility_links $total

### ISSUE THREAD

**Issue by krebbi** [concrete5-community-store/community_store#275]
the basket block shows the total value of all products in the cart. so far so good. but when initializing the purchase process as soon as the shipping method is choosen also the shipping cost is added to $total. 
so when leaving the order process to continue shopping the value doesn't fit OR the shipping costs should be visible in the cart modal. 
![bildschirmfoto 2017-09-05 um 19 34 12](https://user-images.githubusercontent.com/3884521/30074458-e6e741f8-9271-11e7-9763-ca7547cbc083.png)

**Comment by Mesuva** [comment]
This is a good point. I thought that the shipping was mentioned in the cart when it's able to be calculated, but that's obviously not happening.

I think this should be adjusted so it never includes the shipping, will look at this at some point.
