### ISSUE TITLE
Mollie Payment Method for Community Store

### ISSUE THREAD

**Issue by Jozzeh** [concrete5-community-store/community_store#276]
I've created a payment method for community store that works with Mollie.  
Mollie is a Dutch online payment provider and has these online payment methods:

    Creditcard
    SOFORT Banking (Europe)
    iDEAL (Netherlands)
    Bancontact (Belgium)
    Bank transfer
    SEPA Direct Debit
    PayPal
    Bitcoin
    PODIUM Cadeaukaart
    paysafecard
    KBC/CBC Payment Button
    Belfius Direct Net
    Gift cards

If the client chooses 'bank transfer' or 'SEPA' , then the payment does not occur immediately. The payment should be checked manually. Offcourse, you can disable payment methods in the Mollie Dashboard. 

Link to the package : [https://github.com/webhapp/community_store_mollie](https://github.com/webhapp/community_store_mollie)  

( @Mesuva : if you want to place the package in the community store repository list... Mail me)

**Comment by Mesuva** [comment]
Nice one!

As you're in the Community Store organisation group I believe you can already add/transfer it over if that's what you're wanting to do.  Correct me if I'm wrong

**Comment by Jozzeh** [comment]
The mollie package has been transfered to the Community Store organisation.

New URL : https://github.com/concrete5-community-store/community_store_mollie

**Comment by Mesuva** [comment]
Fantastic, I've updated the readme and wiki to include a link to the repo
