### ISSUE TITLE
Deleting option list plays havoc with existing options

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#277]
Using latest version, imagine you add option lists with options to a product say material, orientation, printed sides, quantity. 
Now you save the product and later you delete orientation, it messes up the remaining options.   
It will make printed sides have all the quantity options etc.  Its like some DB headings get offset with values.

Unfortunately, you can't just edit the product to correct the issue, it refuses to save the changes so the only way to fix it seems to be to reload the entire product.

**Comment by madesimplemedia** [comment]
Just to confirm, it seems this issue only occurs when you delete an option list.

**Comment by Mesuva** [comment]
I've hopefully fixed this via: https://github.com/concrete5-community-store/community_store/commit/957da9d5fa4b7097739c006d192a756eefc21838
There were some strange saving/updating bugs in play. If you could test out this latest update and let me know how you go that would be really great.

**Comment by madesimplemedia** [comment]
It's working like a dream now, you're a life saver, thank you so much!
