### ISSUE TITLE
Update product does not update pagename

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#279]
HI,

When updating a product it doesn't update the pagename, have to go to the sitemap and update the product page manually there.

**Comment by Mesuva** [comment]
Good point. What about the slug of the page as well?  That could be a little dangerous to change, it would have to retain the previous/original slug as an additional URL.

**Comment by madesimplemedia** [comment]
Sounds like a good plan re. the slug

**Comment by Mesuva** [comment]
I've put something in place for this via: https://github.com/concrete5-community-store/community_store/commit/1ed693e1f560053a19fec1226d7ee82b54d2445c

I did look at updating the slug as well and _almost_ had it working, but it ended up really tricky to get right and I felt it was only going to cause havoc. So I've left it just for the page name for now.
