### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#28]
Just tried installing on a site with 5.7.5.6 get an error:

main(): Failed opening required '/home/webli/public_html/sub-domains/store/packages/community_store/vendor/autoload.php' (include_path='/home/webli/public_html/sub-domains/store/concrete/vendor:.:/usr/lib/php:/usr/local/lib/php')

**Comment by Mesuva** [comment]
You need to run composer against the package before installing.
