### ISSUE TITLE
Error when adding Product Block to Page

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store#284]
When I try to add the product block to the product page, I get the following error.

Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/home2/wichitc9/public_html/ictmag_v2/application/config/doctrine/proxies/__CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOptionItem.php' (include_path='/home2/wichitc9/public_html/ictmag_v2/updates/concrete5-8.2.1_remote_updater/concrete/vendor:.:/usr/php/56/usr/lib64:/usr/php/56/usr/share/pear')

I only seem to get the error when the product has options.

**Comment by Mesuva** [comment]
I've not seen this before, it looks like something to do with Doctrine's cache files.
Have you tried clearing your concrete5 cache?

**Comment by drumrby** [comment]
Yes I have. Just did it again to be sure.

**Comment by Mesuva** [comment]
Can you provide a bit more detail as to what you are doing to trigger this - when you say you are adding a product block, is this on any page, or is on a page type default template?

I've tried adding a product block to a page, picking a product that has options and I didn't have any trouble.  

Have you recently moved this site by any chance?  I'm wondering if you don't have write permissions on that config directory.  What about your caching settings, does it make a different with caching on or off?

**Comment by drumrby** [comment]
I just ran through the options you gave me so I could give you exact answers.

1) It happens whenever i add the product block to any page, and I select a product that has options.

2) The site is in the same location on the server, but I did recently change the base URL. It was setup on a subdomain while in development and the site has since been made live, so it is no longer on that subdomain. I don't know if that would affect it. I didn't change anything with the site when we went live, I thought concrete5 got rid of the base URL option.

3) Changing the cache settings does not have any effect on the error.

Thank you for your help and speedy responses on this, I really appreciate it!

**Comment by Mesuva** [comment]
I think you should try to find the file mentioned in the error message. In my local install I can find the file __CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOptionItem.php 

I can trigger this same error if rename this file to something else. Check whether the file exists and it has read permissions. If you can't find it, the easiest thing to do is to find a copy from some other install of the same community store version.
