### ISSUE TITLE
getPageTypePageTemplateObjects on Null

### ISSUE THREAD

**Issue by JohntheFish** [concrete5-community-store/community_store#286]
Testing 'Shopin' theme in the PRB with Community Store.

 New 8.2.1 site setup with core sample content.

Install theme with sample content swap. Then following theme's instructions for using community store. Have setup a Product page type as per the theme docs.

No products added yet.

When I click to Add Product in the Community Store dashboard page, I get
Call to a member function getPageTypePageTemplateObjects() on null.

My current interpretation is that this is a community store issue, not anything to do with the Theme under test.

Whoops trace:
Whoops\Exception\ErrorException thrown with message "Call to a member function getPageTypePageTemplateObjects() on null"

Stacktrace:
#24 Whoops\Exception\ErrorException in /home/john/Documents/web/marketplace/dev_821_ecom/packages/community_store/controllers/single_page/dashboard/store/products.php:264
#23 Concrete\Package\CommunityStore\Controller\SinglePage\Dashboard\Store\Products:loadFormAssets in /home/john/Documents/web/marketplace/dev_821_ecom/packages/community_store/controllers/single_page/dashboard/store/products.php:78
#22 Concrete\Package\CommunityStore\Controller\SinglePage\Dashboard\Store\Products:add in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Controller/AbstractController.php:172
#21 call_user_func_array:{/home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Controller/AbstractController.php:172} in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Controller/AbstractController.php:172
#20 Concrete\Core\Controller\AbstractController:runAction in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/ResponseFactory.php:182
#19 Concrete\Core\Http\ResponseFactory:controller in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/ResponseFactory.php:369
#18 Concrete\Core\Http\ResponseFactory:collection in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Routing/DispatcherRouteCallback.php:34
#17 Concrete\Core\Routing\DispatcherRouteCallback:execute in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/DefaultDispatcher.php:122
#16 Concrete\Core\Http\DefaultDispatcher:handleDispatch in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/DefaultDispatcher.php:54
#15 Concrete\Core\Http\DefaultDispatcher:dispatch in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/DispatcherDelegate.php:39
#14 Concrete\Core\Http\Middleware\DispatcherDelegate:next in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/ThumbnailMiddleware.php:60
#13 Concrete\Core\Http\Middleware\ThumbnailMiddleware:process in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#12 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/FrameOptionsMiddleware.php:39
#11 Concrete\Core\Http\Middleware\FrameOptionsMiddleware:process in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#10 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/CookieMiddleware.php:37
#9 Concrete\Core\Http\Middleware\CookieMiddleware:process in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#8 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/ApplicationMiddleware.php:29
#7 Concrete\Core\Http\Middleware\ApplicationMiddleware:process in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/MiddlewareDelegate.php:38
#6 Concrete\Core\Http\Middleware\MiddlewareDelegate:next in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/Middleware/MiddlewareStack.php:86
#5 Concrete\Core\Http\Middleware\MiddlewareStack:process in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Http/DefaultServer.php:85
#4 Concrete\Core\Http\DefaultServer:handleRequest in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Foundation/Runtime/Run/DefaultRunner.php:115
#3 Concrete\Core\Foundation\Runtime\Run\DefaultRunner:run in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/src/Foundation/Runtime/DefaultRuntime.php:102
#2 Concrete\Core\Foundation\Runtime\DefaultRuntime:run in /home/john/Documents/web/marketplace/dev_821_ecom/concrete/dispatcher.php:39
#1  in /home/john/Documents/web/marketplace/dev_821_ecom/index.php:3
#0 {main} in /home/john/Documents/web/marketplace/dev_821_ecom/index.php:0
![page type output edit - dev_821_ecom](https://user-images.githubusercontent.com/1260106/31055034-4b55b75c-a6b6-11e7-9b6a-9a0abae9b845.png)
![page types dev_821_ecom](https://user-images.githubusercontent.com/1260106/31055035-4b58ddec-a6b6-11e7-9595-4c37250b0494.png)

**Comment by mnakalay** [comment]
Hi JOhn, that page type you have on your screenshot is the wrong one. The page type for Community Store is Product Page (not Product) and it has a handle of store_product not product.

Shopin doc says: 

> go to ‘Page Types’ under ‘Pages & Themes’ and set up the ‘**Product Page**’.

**Comment by JohntheFish** [comment]
Thanks, will try that. Will also communicate to Steevb that the instructions need to emphasise that.
However, the store code should also be sufficiently robust not to whoops on that and to give an error message/feedback.

**Comment by JohntheFish** [comment]
Same whoops

![page types 2 dev_821_ecom](https://user-images.githubusercontent.com/1260106/31059936-6da2e6d6-a701-11e7-9046-7c71891d2494.png)

**Comment by Mesuva** [comment]
I'm sure a few extra lines of checking would help here to catch this error.
In the meantime, the page type handle is 'store_product', in your screenshot John you have product_page.

**Comment by 55web** [comment]
By default you should see ‘store_product’ as page handle?
Fresh install the full C5 content this morning. Everything worked perfectly.
![store-page-type](https://user-images.githubusercontent.com/29726924/31066807-515b2a4c-a747-11e7-8695-45c10fd7de8f.png)

**Comment by JohntheFish** [comment]
Thanks, that gets me past the whoops. 

Unfortunately it is weaknesses like "getPageTypePageTemplateObjects() on null" that ran rampant in the original vivid store. The more you can do to guard against such basic issues, the more comfortable developers will feel about adding to the whole store ecosystem.

**Comment by 55web** [comment]
The issue is with the 'shopin' package stripping out the 'Product Page'. Looking at fixing this.

**Comment by Mesuva** [comment]
I've made some updates to avoid this error happening here: https://github.com/concrete5-community-store/community_store/commit/1f76a9252550a5a57f85425125ece891cbbe6eca
