### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by mnakalay** [concrete5-community-store/community_store#29]
Hi,
when installing on C5 5.7.5.6 using PHP 5.6.15 I get the following error:
An exception occurred while executing 'INSERT INTO CommunityStoreOrderStatuses (osHandle, osName, osInformSite, osInformCustomer) VALUES (?, ?, ?, ?)' with params ["incomplete", "Incomplete", 1, 0]: SQLSTATE[HY000]: General error: 1364 Field 'osIsStartingStatus' doesn't have a default value

**Comment by Mesuva** [comment]
This commit should fix this one.
https://github.com/concrete5-community-store/community_store/commit/8b4056f464822ca457f589346157fc4e81a82e7a

**Comment by mnakalay** [comment]
Why not just make osIsStartingStatus nullable?

**Comment by Mesuva** [comment]
I probably could be, but it's important that at least one is marked as the starting status, so I'm wondering if it's just safer to ensure that a value gets written. We can always change it down the track if we hit other issues with this.
