### ISSUE TITLE
Upgrade broke Product lists

### ISSUE THREAD

**Issue by aaronmarp** [concrete5-community-store/community_store#290]
I recently upgraded from Community Store v. 0.9.8.8 to v. 1.2 so I could implement Easypost Shipping.  All seemed fine until I tried to add a Product List to my category pages.  I can add PRoducts fine without error.  Product List block however is now breaking the page.

`Exception
setFeatureType method does not exist for the Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductList class
/home/devprime/public_html/sites/mmt/concrete/src/Search/ItemList/Database/AttributedItemList.php
                $handle = uncamelcase(substr($nm, 6));
                if (count($a) == 1) {
                    $this->sanitizedSortBy('ak_' . $handle, $a[0]);
                } else {
                    $this->sanitizedSortBy('ak_' . $handle);
                }
            } else {
                throw new \Exception(t('%s method does not exist for the %s class', $nm, get_called_class()));
            }
        }`

Any help would be much appreciated!

**Comment by aaronmarp** [comment]
It's definitely an issue in this function....
`public function __call($nm, $a)
    {
        //echo'hello';
        //die;
        if (substr($nm, 0, 8) == 'filterBy') {
            $handle = uncamelcase(substr($nm, 8));
            if (count($a) == 2) {
                $this->filterByAttribute($handle, $a[0], $a[1]);
            } else {
                $this->filterByAttribute($handle, $a[0]);
            }
            
        } else {
            //echo'hello2';
            //die;
            if (substr($nm, 0, 6) == 'sortBy') {
                
                $handle = uncamelcase(substr($nm, 6));
                if (count($a) == 1) {
                    $this->sanitizedSortBy('ak_' . $handle, $a[0]);
                } else {
                    $this->sanitizedSortBy('ak_' . $handle);
                }
            } else {
                echo'hello3';
                die;
                throw new \Exception(t('%s method does not exist for the %s class', $nm, get_called_class()));
            }
        }
    }`

In concrete/src/Search/ItemList/Database/AttributedItemList.php.

I just can't figure out what's different in the update.

**Comment by aaronmarp** [comment]
**UPDATE:** I copied the contents of the old file "old_community_store\community_store\src\CommunityStore\Product\ProductList.php" into the new file.  Hopefully that won't affect anything else!

**Comment by Mesuva** [comment]
I'm trying to work out where setFeatureType is called in the first place. I think it's a magic method for filtering by particular custom attributes.

Are you able to trigger the error, but with full debug on so that I can see the complete error stack?

Also, if it's easy to do, can you run a diff on the old and new ProductList.php files, to spot what has changed between those versions?

**Comment by Mesuva** [comment]
I'm closing this for now, please feel free to post further if you have more details
