### ISSUE TITLE
Abandoned Cart Package

### ISSUE THREAD

**Issue by Jozzeh** [concrete5-community-store/community_store#292]
Abandoned Cart e-mails have very high conversion rates, which is why a lot of e-commerce stores use it.  

I have created a package that creates/schedules and sends abandoned cart emails.  
https://github.com/Jozzeh/community_store_abandoned_cart  

I have tested it on Community Store version 1.2.2 . The package is not active on a live website...    

The mail is added on checkout, when the visitor has clicked the next-button on the billing-step. (so right after the e-mail address is filled in or the registered users has shown an interest in some products.)   
Settings can be found at Dashboard -> Store -> Settings -> Abandoned Cart   

![afbeelding](https://user-images.githubusercontent.com/15868451/31661417-e235a3ea-b33a-11e7-9f63-b36509da7ece.png)

**Comment by Mesuva** [comment]
Wow, this sounds awesome.

If it's not hard to explain, how are you saving down the carts when they are something that are stored in sessions?

**Comment by Jozzeh** [comment]
It's actually quite easy, although i'm not sure if it is the best or most correct process ...  
Inshort, the cart is stored in the database in a seperate 'abandoned cart' table.  

When the user presses the next button in the checkout , the cart (session variable) is retrieved and put in a variable .  
Example of 1 item in a cart =  
pID = 10   
qty = 2   
object = product object (.....)  

So I loop over every product in the cart, en unset the product object.   
Then I save the result json_encoded in the database.   
(I unset the product object, to keep the json_encode fairly small)

To retrieve the cart , there are 2 variables in the URL : 
* id
* hash   

Both of these should match in the database. If they match : the stored cart is json_decoded and looped again to add the product objects.  
When all items are looped, the cart-session-variable is set and the user is redirected to the cart-page.

**Comment by Mesuva** [comment]
I wouldn't call that exactly easy, sounds great.

The point where you save the cart, where the user hits the checkout, would you benefit from an event hook that fires when a customer moves to the checkout?  (have we already got one??)

**Comment by Jozzeh** [comment]
Now the cart is saved when the user hits the first next button at the checkout (billing step -> next ) .   
Not when the user goes to the checkout page.

When a user goes to the checkout , we have their e-mail address only if they are logged in.  
However if the user is not logged in... then we only get the e-mail address when they fill it in at the billing step.  (and the customer object is created.)  

So I don't think this package would benefit from an event when the user goes to the checkout.     
Now, that you mentoin events, I have also added events to the package. I'll list them asap in the readme.  

**Important to keep in mind with this package is what happens when choosing to mail 'everyone'**.  
Example :  
I go to a community store as a guest. I go to the checkout and fill in my email at the billing step, I hit next , next , next, but for some reason I do not complete the order.  
Even though I do not have an account, I will receive an abondened cart mail.  

As far as legality... since the abandoned cart mail is send only once... A person should not opt-in to receive the mail. (As far as I know, opt-in is only required for newsletters / mailings.)

**Comment by Jozzeh** [comment]
quick update... new link to the package :  
https://github.com/Jozzeh/community_store_abandoned_cart

I'm willing to transfer the package to community store (if that would be easier, and then we could close this 'issue') .

**Comment by Mesuva** [comment]
Yep, I'm happy for you to transfer this in.

**Comment by Jozzeh** [comment]
Great, it has been transfered  : https://github.com/concrete5-community-store/community_store_abandoned_cart
