### ISSUE TITLE
Uninstalling community-store 1.2.3 broke v8.2.1

### ISSUE THREAD

**Issue by bisector** [concrete5-community-store/community_store#293]
Hello.

I uninstalled version 1.2.3 from an upgraded from 5.7.13 to 8.2.1 site.  The uninstall returned:
An unexpected error occurred.
Class 'Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method' not found

No access to the site, or the Dashboard.

Any way I can retrieve this please?  The last backup is a couple of days old.

**Comment by bisector** [comment]
My bad.

Realised that another addon under development was referencing the community store.  Should have uninstalled that first.  Problem solved.

**Comment by Mesuva** [comment]
My first question here was going to be 'do you have any CS payment add-ons installed as well'?

What should optimally happen is that community store checks for other add-ons that use it as a dependancy and stop the uninstall if it finds at least one.  It's pretty hard to actually work this out, but I think it could do it at least via the installed payment methods.
