### ISSUE TITLE
Product Page Edit Defaults Throws Error in Dashboard

### ISSUE THREAD

**Issue by pixoinc** [concrete5-community-store/community_store#294]
In the 1.2.3 release, when going into the default page type page in the Dashboard I'm getting the following error:

Cannot redeclare class Concrete\Package\CommunityStore\Block\CommunityProduct\Controller

Need to get this site up fairly quickly so I thought I would try uninstalling it and then installing the earlier release but the package won't uninstall and I get the same error.

**Comment by Mesuva** [comment]
That reads like you have a copy of the product block sitting somewhere, or maybe the package copied and renamed. Can you turn on more detailed debugging to spot where this other declaration might be?

The line:
**namespace Concrete\Package\CommunityStore\Block\CommunityProduct;**
should only apply one in the package, try a search for that across your install to see if you find more than one.

I tried downloading the 1.2.3 install fresh and I'm not able to trigger this error.

**Comment by pixoinc** [comment]
Thanks.  I should have caught that.  It was a custom template that was causing the problem.  The path that was showing is misleading.

**Comment by Mesuva** [comment]
Glad it's solved!
