### ISSUE TITLE
Discounts Applied

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#298]
So far when adding a single Code to grouped discounts it shows up twice.
It does seem to be only taking the discount off 1 time though.

![shopping cart](https://user-images.githubusercontent.com/28864099/32609677-75e8b8f2-c52e-11e7-8e91-c7b2db1d052d.png)

To recreate this issue:
I created a 25% off discount
When valid code entered (Not single use codes)
Starts immediatly
Products Groups
(I have 11 product groups added, some products are in more than 1 group this don't seem to make a difference)
No User Groups

When customer adds code it shows up like in the screen shot.

**Comment by Mesuva** [comment]
I believe I've tracked this one done and put in a fix for it, via:
https://github.com/concrete5-community-store/community_store/commit/188c9efad673507ef56c39a7b5655ea5b7e2563a

I could recreate this bug if I set up my discount with codes and then had the _same code_ listed in it multiple times. That was the only way I could get that to happen though.

**Comment by Mesuva** [comment]
(the actual fix is one extra bit in an SQL statement, so it's pretty easy to apply directly)

**Comment by mdius** [comment]
Well this fix did take care of it.

I am very pleased at how this cart works and looks.

Thank you!
