### ISSUE TITLE
Creating new product fails

### ISSUE THREAD

**Issue by mnakalay** [concrete5-community-store/community_store#30]
Creating a new product on a fresh install fails
An exception occurred while executing 'INSERT INTO CommunityStoreProducts (cID, pName, pSKU, pDesc, pDetail, pPrice, pSalePrice, pFeatured, pQty, pQtyUnlim, pBackOrder, pNoQty, pTaxClass, pTaxable, pfID, pActive, pDateAdded, pShippable, pWidth, pHeight, pLength, pWeight, pNumberItems, pCreateUserAccount, pAutoCheckout, pExclusive, pVariations) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "Product 1", "001", "<p>Some testing product that happens to be first<\/p>", "", "15", null, "0", 0, "1", 0, "0", null, "0", "0", "1", "2016-03-04 20:34:05", "0", "0", "0", "0", "0", "", 0, 0, false, 0]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'pTaxClass' cannot be null

**Comment by Mesuva** [comment]
This one is confusing me a little, there should have been at least the 'Default' tax class saved against the product, as that tax class isn't deletable.  Is that tax listed at /index.php/dashboard/store/settings/tax for  ?

**Comment by Mesuva** [comment]
Nevertheless I've adjusted the field here, as I think null would be valid for a tax class: https://github.com/concrete5-community-store/community_store/commit/697b7cab51e152c2b518afd43910b6c49610c420

**Comment by mnakalay** [comment]
Yes I agree, that's what I did as well and it worked
