### ISSUE TITLE
&deg; in product name

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#302]
I've brought this up before and I thought I found a work around, but when trying to edit the pages it changed the code `&deg;` to an actual ° which is fine, but it still crashes my site when trying to edit it. So for me to edit these pages I'll have to manual change every ° to `&deg;` If there is no way around this, I'll make so, but could there be an easy fix to show the ° but not try to enter it on the url line?

**Comment by Mesuva** [comment]
I tried to recreate this yesterday but couldn't quite find where it was breaking. When I put in the degrees symbol concrete5 was changing this to a 0 in the url slugs.

Is this in 5.7 or v8?

Could you post a screenshot or two where you are editing this on the page?

**Comment by mnakalay** [comment]
I tested with the example you provided in your other thread
"High Temp Float Switch - 10 Foot - 225°F/107°C - Normally Open - Intermediate Angle"

I tried it with `°` and with `&deg;` and they both worked and both gave the same result with no error

I am on C5 8.2.1 and PHP 7.0.11

**Comment by mdius** [comment]
I am using the 5.7.5.13 version with php 5.6. I cannot try it again out of fear it completely crashing my site, tried to upgrade my backup site to 5.8 and it completely destroyed it. I will try to fix this today, and try again.

But what caused the most issues is when:
I create a page called "High Temp Float Switch - 10 Foot - 225°F/107°C - Normally Open - Intermediate Angle", set it all up. I believe the ° broke it right away, but it might have taken it the first try. But try to duplicate that page, leave the ° in the duplicated page and that crashed it every time. Maybe 5.8 fixed it?

This is a Concrete 5 issue, I just put the ° in the Page Name and when it got to the ° it crashed my site. Shouldn't have tried it.

**Comment by mdius** [comment]
So, if I make a new page through Concrete 5.7 with this as a Page Name: "Testing Degree Symbol ° Today"
It breaks it.
But if I just do a Page Name:  "Testing Degree Symbol °"
It works.
So this is a Concrete 5 issue I believe.

**Comment by Mesuva** [comment]
I just tried this on 5.7.5.13, through:
- creating a page via the normal composer style way
- via the sitemap
- via the creation of a new product

In all cases I didn't have any issues, it just created a page with a 0 in place in the slug. I'm wondering if this is a database encoding issue.

<img width="846" alt="screen shot 2017-11-18 at 11 49 46 am" src="https://user-images.githubusercontent.com/1079600/32975429-f8671358-cc56-11e7-938f-7e0b8c233ebd.png">

**Comment by mnakalay** [comment]
@Mesuva that's the conclusion I also reached and posted on c5.org http://www.concrete5.org/community/forums/usage/the-degree-symbol-breaks-my-server/#909960

**Comment by mdius** [comment]
A 0 would be nice, but it is obvious that this is a local issue. The Database idea didn't work, because it was utf-8.

So, I'll just deal with it. But that you for looking in to it and tying to help.
