### ISSUE TITLE
Is there any way to update product option ?

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#304]
Is there any way to update product option in checkout page ? i have tried to update the product option value in session but it's not working. Here is my code

`$cart = Cart::getCart();`
`$productIndex = 1;`
`$optionKey = 'po38';`
`$optionNewValue = 25;`
`$cart[$productIndex][$optionKey ] = $optionNewValue; `
`  Session::set('communitystore.cart', $cart);`

**Comment by Mesuva** [comment]
After running that code, and then go to the cart page, you're just not seeing a change?

Or are you wanting to do something with the cart after this code?
If so, you may need to use:
$cart = Cart::getCart(true);
to force it to refetch/process the cart again.

**Comment by midhun1993** [comment]
I have tried this. After setting the session I have used the following code to force refetch the cart again.
$cart = Cart::getCart(true);
But no luck.

**Comment by Mesuva** [comment]
I'm not sure why that wouldn't be working. Are you able to output the cart to the screen before and after your change to see whether it actually changes the array of cart items?

**Comment by Jozzeh** [comment]
@midhun1993  
Can you refresh the page after updating the cart session (or refresh the page twice)?  
After the refresh, do you see the change ? 

Perhaps this is the same issue I have had : #190

**Comment by midhun1993** [comment]
Hi @Mesuva , @Jozzeh 

Sorry for my late reply, i have coded wrongly for update option.
i replaced this line :
`$cart[$productIndex][$optionKey ] = $optionNewValue;`
With this : 
`$cart[$productIndex]['productAttributes'][$optionKey ] = $optionNewValue;`
Now it works perfectly.
Thanks for your response.
i closed this issue.

**Comment by Mesuva** [comment]
Glad you got it working, I wouldn't have picked that up for a long time!

**Comment by justynpride** [comment]
Is this something that might be incorporated in to Community Store. I'd love to try it out.
