### ISSUE TITLE
Product Variation Option List Sorting

### ISSUE THREAD

**Issue by danklassen** [concrete5-community-store/community_store#306]
if you add an option list variation to a product, and then change the order the options, the first one entered into the system will get selected="selected" on it, even though it no longer shows up at the top of the list.

It looks like the ProductVariation::options does not have a default sort set on the relation

**Comment by Mesuva** [comment]
I had to undo the fix submitted for this as I think it was incomplete.
The line  
```* @OrderBy({"poiSort" = "ASC"}) ```
was added to the @OneToMany of ProductVariation, but this assumed that ProductVariationOptionItem has the poiSort field, which it doesn't.
Were there more changes that you made to ProductVariationOptionItem that you may have accidentally omitted from your pull request?

**Comment by losttheplot** [comment]
I've just found this thread after digging down into the codebase trying to get to the bottom of similar symptoms to that reported by the OP (wrong prices displayed by default, following a re-ordering of variation options). I need to fix this issue, so before I spend more time on it, please can you tell me if either of you have any ideas that might help.

Incidentally, when looking at product details via the product modal, the option list is not 'selected' at all, so the first option is selected by default, which in turn populates the modal price (and sale price) correctly i.e. according to the top option in the select list.

The main problem though, is that the product listing shows the wrong prices, and this cannot be corrected by simply disabling an option list select mechanism as there isn't one on this page.
