### ISSUE TITLE
Custom Discount Restriction Types

### ISSUE THREAD

**Issue by mkly** [concrete5-community-store/community_store#309]
I have built a custom discount restriction type implementation that is similar to the Store Payment Method and Shipping Method custom type system. I wanted to open this issue up for discussion before submitting the PR to get a head start on any objections/suggestions I should consider before submitting it.

The use case is that discount restrictions can be numerous. For example a discount for being the first order a customer has ever placed or a discount on every 8th order. Another could be based on when the customer first signed up for the site. Or based a specific combination of products have been added. Etc etc. So this system allows for custom one-off restrictions for a single site as well as being able to package those up for wider use by the community

I'll probably be submitting it this weekend so we can also discuss the details then.

**Comment by justynpride** [comment]
Sounds an interesting feature. I’ve a scenario where I’d want to provide a discount based upon the selection from a select option on the check out. It will be great to see what is possible with your feature.

**Comment by justynpride** [comment]
Any update?

**Comment by mkly** [comment]
@justynpride Wow time flies! Been swamped and haven't come up for air yet. My use case changed for this in that I'm forking off community store and modifying it directly as opposed to trying to extend it. There is something written to do this, but I'm not sure at this point it will see the light of day. Am closing until I get a chance to circle back.

**Comment by justynpride** [comment]
@mkly I can understand that decision. I've seen a couple of Community Store features that others have created that are naturally forked off and modified directly. It's quicker and easier!
