### ISSUE TITLE
Product Parent page has unnecessary block

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#31]
When the package is installed and a the /products parent page is created, a composer block is added to the page and is visible when it shouldn't be. See attached.

This page isn't necessarily viewed/used, but it certainly could be.

I don't know how to programatically create this page but clear its blocks (or create it where this composer block isn't automatically added).   

Line 64 of /src/CommunityStore/Utilities/Installer.php

<img width="1011" alt="screen shot 2016-03-05 at 10 10 30 am" src="https://cloud.githubusercontent.com/assets/1079600/13543424/f9fcc640-e2ba-11e5-8e72-8f3e477b1c69.png">

**Comment by mnakalay** [comment]
mmm, when creating the page you are giving it the full template by default and that's where the composer block is set. Not 100% sure here but But it looks like that's only in the theme you're using. I don't have that block in Elemental.

**Comment by Mesuva** [comment]
Weird, I'm using Elemental for the testing here - no other theme installed!

**Comment by mnakalay** [comment]
I checked again, in edit mode and normal and no composer anywhere. Maybe you fiddled with yours and forgot about it?

**Comment by Mesuva** [comment]
Weird, I'm pretty sure I did this on a completely fresh install.
I'm talking about what appears under /products
I'll test again and close if I'm just going fou.

**Comment by Mesuva** [comment]
Didn't happen on a fresh install, with Elemental and sample content. I dunno where it came from!
