### ISSUE TITLE
Discount Code/No Code issues

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#310]
OK
Trying to push this product group discount to its limits.
So I set up a Cyber Monday Pump sale, selling our pumps for 10% off (this one applies when matching restrictions on Product Groups) and we are running a floats sale 25% off (this one is when a valid code is used on Product Groups). So I add 1 of each product to the cart and it immediately takes to 10% of the pump, like it should. But then if I add the 25% off floats code, it then takes the 25% off the pumps group too.

There are not any Products in Both Groups.  All Floats are separate from all Pump.

**Comment by Mesuva** [comment]
Found this issue. Try updating to the latest master, or applying the changes to the two files in this commit:

https://github.com/concrete5-community-store/community_store/commit/46fc53fdf19992c9ba4dd7e5b78c0a33fd28d289

**Comment by mdius** [comment]
Perfect fix!
