### ISSUE TITLE
Allow customer to select Username & Password when creating account on purchase

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store#315]
I had our store setup where Guest Checkout was not allowed but that created the difficult step of making them use the Concrete5 registration process, which is far from ideal. SO I switched our store to always use Guest Checkout, and then set the products to create an account on purchase. Which is much more streamlined and more inline with what my original goal was.

All that said, is there a way to allow the customer to select their own username and password during the checkout process, instead of the randomly generated username and password that happens now?

**Comment by Mesuva** [comment]
There isn't something in place to handle that now, sorry.

The username is based off their email, and the password generated is supposed to be reasonably 'secure' in the generation. 

Personally I would be setting it up to use emails as the login, meaning that usernames become irrelevant.

**Comment by drumrby** [comment]
I was actually thinking about that. If I switch the setting in the concrete5 dashboard to use the email for login, will that automatically adjust the Community Store setup, or would anything even have to change in the Community Store setup?

As far as the password goes, could I create an additional field in the checkout form and then pass that to the user creation function in Order.php?

**Comment by Mesuva** [comment]
The store should handle the switch to email as login (or at least I remember coding that in).

You might be able to work something out with the additional field, but I think it would take quite a fair bit of adjustment to the order completion function. I think the trickier stuff is validating that a password has been entered, it's long enough, etc.

**Comment by drumrby** [comment]
Hmm, ok. Let me ask you this, do you know of a way to make that password auto expire on first login? That way the first time they login it would prompt them to change their password to something they want? I've looked for this before in concrete5 but have never been able to find anything on it.

**Comment by mnakalay** [comment]
I think your best bet at this point is to send them an email asking them to do so after they place their order.

**Comment by mnakalay** [comment]
Another way of doing it (kind of a hack to be honest) is to create 3 user groups Group A contains users allowed to buy stuff, Group B also contains users allowed to buy stuff but expires automatically so users are removed from the group after a certain time. Group C contains users not allowed to buy stuff and need to change their password.

On first buy you put users in Group B. When they are taken out of the group you use the event on_user_exit_group to put them in GROUP C (need to change password) and notify them that they are required to change their password.

When they do, use the even on_user_change_password to put them in Group A and remove them from Group C

**Comment by drumrby** [comment]
That's a pretty good hack there. I like that. I also like the idea of the simpler email idea. I think we are going to implement both for the time being. My ideal scenario would be the ability to select the username, but more importantly the password at the time of purchase, so I guess that would be a feature request. But these will work for the time being.
