### ISSUE TITLE
Pre-Authorization 

### ISSUE THREAD

**Issue by pinecreativelabs** [concrete5-community-store/community_store#316]
I have a client who is wondering if Community Store has pre-authorization capability. Unfortunately, I don't know enough about this sort of thing, so I'm looking for a little help on how to answer this.

Is this something that a payment gateway such as Authorize.net or Paypal would handle?

**Comment by Mesuva** [comment]
This come down to each individual gateway, it would be a setting control within each payment add-on and not the core store (I think).  

With Authorize.net for example, it would be case of changing the line here:
https://github.com/concrete5-community-store/community_store_authorize_net/blob/master/src/CommunityStore/Payment/Methods/CommunityStoreAuthorizeNet/CommunityStoreAuthorizeNetPaymentMethod.php#L115

From **authCaptureTransaction**
to **priorAuthCaptureTransaction**

Then merchants would then need to go into their Authorize.net dashboard to actually capture the transaction and make the charge happen.

I think it would be as simple as that for Authroize.net, and it's not a big deal to add that as option on the add-on, but what I haven't looked at is if there are any other changes to the XML that is sent that would need to change. If you have a sandbox account set up that might be an easy thing to test.

Paypal I've not looked at, but it's likely to be similar in terms of changing a parameter.
