### ISSUE TITLE
Display users that have purchased product

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store#318]
I would like to display all the users that have purchased a product on the product page. How could this be done?

**Comment by drumrby** [comment]
Any ideas on this? It's something that I'm really needing to implement.

**Comment by Mesuva** [comment]
There's not built in functionality at this point to do something like this.

I'd suggest using direct SQL to find out the orders numbers where the product has been purchased, then looping and fetching the orders to find the customer details for display.

Although it's not necessarily best practice, I think you could do all the above within a product block template so you can selectively apply it to products.

**Comment by drumrby** [comment]
Ok, sorry for the delay in responding, I just jumped right into experimenting. I've been messing around with this, I don't have that much experience with direct SQL. Hoping to be able to have it working in the next day or two. Thank you for the idea!
