### ISSUE TITLE
Categorize under page - not going under that page

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#319]
Hi,
When I am categorising a product under a page it is not actually going under that page, it is still adding the page under the default products parent.
Is there a way to fix this?
Thanks
Dave

**Comment by Mesuva** [comment]
Categorising a product under a page isn't supposed to place the product page itself under it in the sitemap, it's just a mechanism that the Product List block can use to find products. Keep in mind you can categorize a product under multiple categories.

If you're wanting to move the actual product page somewhere other than the default it's really just a case of doing this in the sitemap.

**Comment by madesimplemedia** [comment]
Thanks, that makes sense.
