### ISSUE TITLE
Discounts over £x ?

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#320]
Hi,

How can I make it so I offer a discount over a certain £x?
Ideally I would have:
>£300 discount of 5%
>£500 discount of 10%
>£1000 discount of 15%

**Comment by Mesuva** [comment]
That's not an option with the current discount rules. 
Personally it's not a style of discount I've heard of that often, but maybe that's just me.

Could you handle it with the more recently introduced quantity based pricing?

**Comment by madesimplemedia** [comment]
Hi Ryan, I think we managed to handle it - it's pretty common here in the uk to have those discounts.
