### ISSUE TITLE
duplicate an order with same product options in community store

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#324]
How can i duplicate an order with same product options in community store

**Comment by midhun1993** [comment]
Any idea to duplicate an order with same product options in community store

**Comment by Mesuva** [comment]
You may need to write your own function for this. I believe you would be able to programatically do it without having to resort to SQL - the _product_ duplicate works this way, you may be able to look at that to see the pattern of how the main record is copied and then all the associated records.

Where it could get a bit tricky is where the order attributes would need to be copied.

A fairly big task I'm afraid.

**Comment by midhun1993** [comment]
Hi @Mesuva 

Thanks for the info, i will close the issue now.

Thanks
Midhun
