### ISSUE TITLE
Google Rich Cards for Products

### ISSUE THREAD

**Issue by pinecreativelabs** [concrete5-community-store/community_store#329]
Rich cards helps provide Google with structured data for improved search results, especially for mobile. There are many types of cards, one of which is for products. I really think this would be a very valuable feature to have for product listings. 

https://developers.google.com/search/docs/data-types/product

Is this fairly easy to implement?

**Comment by Mesuva** [comment]
I'm pretty sure I have already added this in, using microdata format.

You can see the itemtype on the product block for example here:
https://github.com/concrete5-community-store/community_store/blob/master/blocks/community_product/view.php#L21

I did initially test it, but things might have become invalid with changes over time - let me know if you think it's not correct

**Comment by webiflex-dotcom** [comment]
As discussed on slack it appears that we have the below that are not included in Rich results. Let me know if can help in any way

Brand
<div itemprop="brand" itemtype="http://schema.org/Thing" itemscope>
      <meta itemprop="name" content="ACME" />
    </div>

Availability
<meta itemprop="availability" content="https://schema.org/InStock" />

URL
<link itemprop="url" href="https://example.com/anvil" />

Price valid until - not sure if can apply to sale price with a date when ends 
<meta itemprop="priceValidUntil" content="2020-11-05" />
