### ISSUE TITLE
Create "Buy x Get y " discount rule

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#331]
Is it possible to create a discount code for buy 5 product get one same product free

**Comment by Mesuva** [comment]
Not really, discounts currently work by applying a percentage or value off of a product, based on simple matching rules - it doesn't have any rules to handle discounts based on quantity.

The current workaround would be to create a 5 pack product with the discounted price.

**Comment by midhun1993** [comment]
Thanks for the info, i will close this issue.
