### ISSUE TITLE
Feature: Add Product, Detail Page, Page Template should default to Settings [Page to Publish under Default Page template]

### ISSUE THREAD

**Issue by martbase** [concrete5-community-store/community_store#332]
When adding a product /index.php/dashboard/store/products/add#product-page defaults to the first Page template alphabetically I believe as set here 
community_store\single_pages\dashboard\store\products.php around line 1398 in Community Store v 1.3.2.

```
                    <?php if ($productPublishTarget) { ?>
                        <?php if ($pageTemplates && !empty($pageTemplates)) { ?>
                        <div class="form-group">
                            <label><?= t("Page Template")?></label>
                            <?= $form->select('selectPageTemplate',$pageTemplates,null);?>
                        </div>
```

Since we already select a Page to publish products under and it has a Default Page template in Basic settings we should pick the same to speed up adding products when there are several page templates for the product page and only the default one has been setup properly (output has product block, ...)

When I add a product without specifying a Page Template under Detail page it results in blank output when a product is clicked since the wrong template is used to display the detail view.

**Comment by Mesuva** [comment]
My question here is: why do you have multiple page templates set up again the 'Product Page' page type?  

I think this would be a case of either removing from the list of available templates for the page type the page templates you don't want used, or at least setting up the others to have a default product block as well.

You are right though that it should default to the default page template set for the page type, that should be a fairly quick one to fix I think.

**Comment by martbase** [comment]
The reason I have multiple templates for the Product Page is for flexibility - specific/special products can be displayed differently.

I had the Product Page already setup in my theme (before installing CS) and it allows all page templates (someone else might also have more than one template). 

I usually customize output just for the default page template so having it as the default would speed up my workflow when adding products.

**Comment by Mesuva** [comment]
I've pushed up a change to make it default the page template to the default set for the page type:
https://github.com/concrete5-community-store/community_store/commit/bcf314d87ab155554dcc2b58a9a99c2df6a21b85

Since it's only a few lines of code you might want to try directly updating these files and letting me know if it addresses your concern.

**Comment by martbase** [comment]
Works perfectly. Thank you for the quick fix.
