### ISSUE TITLE
Cart Error == Proxy Errors

### ISSUE THREAD

**Issue by poppypetal** [concrete5-community-store/community_store#333]
Help! I'm having an issue with adding a product to the cart.  I just uploaded the latest version of the community_store package, so I am running v.1.3.2 and concrete 8.2.1.  What's going on and how do I fix it....thanks!
 
When selecting a product and adding it to the cart, this error shows up in the cart popup:
{"error":{"message":"Doctrine\\Common\\Proxy\\AbstractProxyFactory::getProxyDefinition(): Failed opening required '\/home\/fr\/public_html\/application\/config\/doctrine\/proxies\/__CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOption.php' (include_path='\/home\/fr\/public_html\/concrete\/vendor:.:\/usr\/lib\/php:\/usr\/local\/lib\/php')"},"errors":["Doctrine\\Common\\Proxy\\AbstractProxyFactory::getProxyDefinition(): Failed opening required '\/home\/fr\/public_html\/application\/config\/doctrine\/proxies\/__CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOption.php' (include_path='\/home\/fr\/public_html\/concrete\/vendor:.:\/usr\/lib\/php:\/usr\/local\/lib\/php')"]}

Then, when I view the cart, there is this error, and the css styling of the cart page is not correct: 
Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/home/fr/public_html/application/config/doctrine/proxies/__CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOption.php' (include_path='/home/fr/public_html/concrete/vendor:.:/usr/lib/php:/usr/local/lib/php')

In the dashboard, Logs I find this error: 
Exception Occurred: /home/fr/public_html/concrete/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209 Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/home/fr/public_html/application/config/doctrine/proxies/__CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOption.php' (include_path='/home/fr/public_html/concrete/vendor:.:/usr/lib/php:/usr/local/lib/php') (64)

**Comment by Mesuva** [comment]
I've seen something like this before, it seems like a concrete5 bug to be honest.

You could try:
- backing up the /application/config/doctrine/proxies folder, it should have a whole bunch of files in it with long filenames
- visit /index.php/dashboard/system/environment/entities/view and hit the red 'Refresh Entities' button

that process should regenerate all the 'proxy' files, including the __CG__ConcretePackageCommunityStoreSrcCommunityStoreProductProductOptionProductOption.php one that is supposedly missing in your install

**Comment by poppypetal** [comment]
Thank you very much, that solved the problem!!

**Comment by Mesuva** [comment]
Fantastic, perhaps it timed out originally when generating those files
Glad to know there's a simple fix for this if it pops up again
