### ISSUE TITLE
Continue Shopping

### ISSUE THREAD

**Issue by jagseven** [concrete5-community-store/community_store#335]
Hi all, we are almost at completion of a new site using the community store. My issue is that after having added a product to the shopping cart, and I select "Continue Shopping", all that happens is the shopping cart modal/pop out disappears. All the previously entered information is still present in the fields - both custom fields and dropdown menus / checkboxes.
I think that this will be confusing for customers who may not think that they have added the product to the basket.
Is it supposed to be like this or is it a bug?

Any help in resolving this issue would be much appreciated.

**Comment by Mesuva** [comment]
Have you got a cart block on your page, i.e. the 'Utility Links' block?
That then provides the number of items in the cart, links to the checkout, etc. 

There is also an option to send customers directly to the checkout if you prefer, this is handy if you have only a few products and it's unlike they'll want to add multiple.

Another question might be: what would you expect to happen instead when the Continue Shopping button is pressed?  Would you expect it to go to the home page, or reset the form, or something else?

**Comment by jagseven** [comment]
Thanks for the reply. 

Yes, we have the Utility Block installed. I think that it might be easier for end users to have the form reset on hitting the Continue Shopping button to avoids any confusion.

Is this possible?

**Comment by Mesuva** [comment]
To achieve that I believe you would need to override and write some custom javascript.

Are you perhaps overthinking the potential of confusion here though?

When someone adds something to the cart they:
- actively click a button and see a cart overlay come up - feedback 1
- see a message in the cart that says 'Item has been added to the cart' - feedback 2
- they also see buttons to checkout at that point
- they see behind on the page itself the mini cart show a change in items, or perhaps appear if it was originally empty - feedback 3

Then clicking the button that says 'continue shopping' is surely an implicit action that they want to  close the cart for now and continue browsing - they might want to add another variation of the product, or go to a related product of what they just added. Personally I would find if the selections I just made change back disorientating - I would be thinking "wait, didn't I just pick the big one, not the small one", whereas I know I've closed a modal window and I'm viewing what I just configured.

**Comment by jagseven** [comment]
Thanks for the reply again.
The issue is only really coming up on the mobile view as the items for sale are race entries for triathlons, so when pressing the "Continue Shopping" button on the mobile the Utilities block disappears and you are faced with the previously filled in form. 
Her ideal scenario would be to clear the form upon pressing the "Continue Shopping" button but if that is a big job, could it redirect to the Home Page to make it clearer to the visitor that the initial process has worked?
I am not a JavaScript expert - is this something that you could do? How much would you charge?

**Comment by Mesuva** [comment]
Are you building a custom theme for this shop?  If so you might be able to sneak this extra javascript in, either within an existing javascript file or maybe just in the footer (just before close of body) between some <script> tags:

 $(document).on('click', '.store-btn-cart-modal-continue', function(){
        window.location.href="/";
 });

That should do a redirect to the root of your domain.

If you are using a pre-built thing and don't really have access to the code, another place you could paste it (with script tags around it) is the tracking codes in the dashboard, in the footer.

**Comment by jagseven** [comment]
Thanks very much - that's going to work - it is a custom theme so I have been able to add it to the footer.
Your help is very much appreciated.
