### ISSUE TITLE
getCurrencyMultiplier()

### ISSUE THREAD

**Issue by edsaxmoore** [concrete5-community-store/community_store#336]
I have concrete5 v8.2.1. I've installed community store with Stripe and paypal. When I go to checkout, I am getting the following error: Call to undefined method Concrete\Package\CommunityStore\Src\CommunityStore\Utilities\Price::getCurrencyMultiplier()
I have run the composer, updated it as well. Still the same thing. Any help is appreciated.

Ed.

**Comment by Mesuva** [comment]
That sounds like are running an older version of community store. That getCurrencyMultiplier function was introduced in version 1.2, I'm guessing you are running something earlier than that.

If you're not keen on updating for other reasons I think you'd be able to get away with updating src/Utilities/Price.php with the latest version, to add in a couple of additional functions.
