### ISSUE TITLE
Next button on Checkout in mobile is blocked by Cart View Element.

### ISSUE THREAD

**Issue by AdamBassett** [concrete5-community-store/community_store#337]
When on mobile sizes the ```<div class="store-checkout-cart-view col-md-6">``` element is floating over the next button when filling out the billing info.  This makes the button unpressable.  This is repeatable in Edge, Firefox, Chrome, and Safari. Tested on W10, Mac OS and iOS 11.2.1.

**Comment by Mesuva** [comment]
Yep, looks like it was covering the bottom half of the button

**Comment by Mesuva** [comment]
Just saw your pull here: https://github.com/concrete5-community-store/community_store/pull/338/files

A few seconds ago I pushed up: https://github.com/concrete5-community-store/community_store/commit/45360f51635061551153b541ca3ce9b5af781f0c

What do you think is the more appropriate fix here?

**Comment by AdamBassett** [comment]
Just put a pull request in that fixes it.  Just needed a row div around it.

**Comment by AdamBassett** [comment]
Yup looks like we are both working on it.
Well I'm not sure.  My fix dose not require an extra CSS class, but not sure that's a big deal.

**Comment by Mesuva** [comment]
I might leave it with my fix if that's ok - I think there's a little less chance of it breaking someone's custom styling.

**Comment by AdamBassett** [comment]
That's a good point.  Thanks for the quick fix.
