### ISSUE TITLE
How to upgrade an install of Community Store

### ISSUE THREAD

**Issue by JonCope** [concrete5-community-store/community_store#341]
I installed community store on a C5 site about a year ago and have been very pleased with it.  However we have not upgraded it when upgrading C5 itself, and have a suspicion that some of the functionality may not be there any longer - for example order acceptance emails to the client don't appear to be getting through, or may not even be being sent.  We understand that the Submit button isn't working on phones or tablets.

We are running Community Store version 1.0.1 in C5 version 8.2.1 and are well aware that you have resolved issues since that version by means of upgrades and also by database changes, but until yesterday we had not attempted to update.  We use the Paypal payment module as well.  

On trying to install the newest version, which we did by uploading to the package folder after renaming the old Community Store as OLD, we experienced an error that made our site inaccessible.  We tried to revert to the old version by renaming both but still received the same error which was:

An unexpected error occurred.
Class 'Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method' not found

We checked that path and the method.php file was present in both old and new versions.  We presume that that is what should be there.

Eventually we had to ask our hosting company to reinstate our site from our backup.

Now I must make it very clear that we have no problem with any of this and are certainly not complaining.  We realise this is an unsupported, community written project and congratulate you on and thank you for your work - a much needed addition to C5.   As I say we have been very pleased with the module and it has worked pretty well for us and, to repeat,, we realised it needed to be updated.

My question then is how should this be done?  I can't see anywhere in the Wiki how one should update or reinstall, only instructions for the initial install, and are there steps one should take to ensure the site isn't broken by doing it the wrong way?

Any advice or assistance will be gratefully received.

**Comment by AdamBassett** [comment]
@JonCope well first I recommend that you try updating in a dev location.  This way if something gets messed up that you cant recover from you can just start over with your copy of the live site.

As far as upgrading you should just replace the files in the community_store directory and then login to the admin.  Go to manage packages and C5 should see that there is an update and an update button should appear next to the community_store package.  Click it and C5 should do all the work.

One thing you may check is that the permissions on all folders allow your web server access.  If the web server cant access a folder the class wont load.

Again I would do all this in a beta location.  If something goes wrong no big deal your site is not down and you can easily restore using the live site as a backup.

**Comment by Mesuva** [comment]
I also can't recommend enough the exercise of testing out any major updates on a development copy somewhere seperate from your 'production' website. When you do trigger an upgrade of a package, the only thing that will be actually changed is your database (and obviously the updated package folder). So if things do go wrong you really only need to roll back the database to your good version and replace the package folder - all other concrete5 files shouldn't need to be replaced.

The process to update community store isn't any different than updating any other manually installed packages - replace the add-on directory with the latest one and trigger an update from the dashboard. I'll add something to the wiki for clarity though.

One thing that has caught me out a few times is that you can't leave an old copy of a package in the packages directory, even if you rename it - concrete5 tries to load everything from those packages to see what is in there, but when you have the same files it will find the same exact class files twice and throw an error. So if you want to not overwrite or delete the existing package from the server, just create a top level packages_old folder (so next to /packages) and drag the packages into there instead.

**Comment by Mesuva** [comment]
I've written up this:
https://github.com/concrete5-community-store/community_store/wiki/Updating

Feedback welcome

**Comment by JonCope** [comment]
Many thanks to all who have given advice and guidance re updating.  We'll have another go shortly, following the steps in the new Wiki article, which is very helpful - as are all the comments.

It may be a few days before we have another try, but I will report our progress.
