### ISSUE TITLE
Saving products is triggering mod_security

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#343]
Hi,

On one of my sites running CS when I save products it is being blocked by mod_security and I get a 403 forbidden error.
![image](https://user-images.githubusercontent.com/10834004/36386913-5051fc6e-158f-11e8-8888-9af1e63831b3.png)

It's a Lightspeed server running PHP7.  If I disabled mod_security then it saves.

Thanks
Dave

**Comment by madesimplemedia** [comment]
If anyone else comes up against this, my host were able to fix it by whitelisting the modsec rule with ID of 390707.

**Comment by Mesuva** [comment]
Modsec is a tricky one - sometimes it can be the style of form submission and sometimes it can be a particular keyword that it rejects in your content. The word 'casino' or 'gambling' seems to be words we hit all the time, when we're pasting legitimate content.
