### ISSUE TITLE
Payment method using coinpayments.net

### ISSUE THREAD

**Issue by hemiipatu** [concrete5-community-store/community_store#349]
Hi there, I am wondering if it would be possible to add https://www.coinpayments.net/ as a payment method onto the store as this is a quickly growing form of payment and it would also open more possibilities with what people are accepting etc.

**Comment by Mesuva** [comment]
There shouldn't be any restriction from the community store side of things to allow for integration here, it can handle both client side and server side handling in different ways to accommodate different payment gateways.

It really just comes down to the amount of work that might be required. Stripe for example has both a client side library (for the pop up form) as well as strong server side libraries, so it ends up being a bit easier than others. For this one, I'm not really seeing anything that handles the client side, so stuff like picking what cryptocurrency you want to use, really the final payment interface would all need to be written.

Personally I wouldn't have plans to work on this (I'd need a client to request it), but I'm happy to point someone in the right direction. The existing payment gateways do act as good code examples.

**Comment by hemipatu** [comment]
If a "client" did decide they wanted said feature. what's your estimates on pricing for it's creation? 

Furthermore would it be something you'd consider if you where to be paid to develop this new payment method?
