### ISSUE TITLE
Handling of products ordered with floating numbers (e.g. 0.1 m)

### ISSUE THREAD

**Issue by typoman76** [concrete5-community-store/community_store#350]
I'm checking community store for selling fabrics. Fabrics are priced in meters and ordered in part of meters (cm). So a customer should be able to order 0.6 m of fabric.
This is not possible at the moment with community store. But it should be e possibility for every product that is sold in custom lenghts (fabrics, ropes, chains) or weights (e.g. special spices, tea, cosmetic base products...). 
How can I do this with community store?

I checked some fields where I have to put in these partial numbers:
* stock amount
* order amount -> price calculation
* cart

**Comment by Mesuva** [comment]
Right now the store doesn't handle decimal amounts for quantities, but I would think that if the database was changed the rest of the maths would carry through correctly. 

It's then more about the front-end and allowing different products to be configured to either except whole numbers or decimals. I think then a maximum 'quantity' would be helpful too (which I think @mnakalay suggested once). I also think that the units of the quantity (cm, linear metres, grams, etc), would need to be entered in against a product so it could be displayed against the quantity input and used in the cart/order summary.

So it would need a bit of work to add to the store, but there wouldn't be any reasons why it wouldn't be able to be done.

**Comment by typoman76** [comment]
I'm closing this for now. It's clear there is some work to do and it's not available at the moment. 
I will come back to this.

**Comment by Mesuva** [comment]
I _have_ actually done some work on this, as I do see it as valuable feature.
I just haven't finished it up yet, a few more things to adjust - and trying to fit it in other work!

**Comment by Mesuva** [comment]
I've worked on this via https://github.com/concrete5-community-store/community_store/tree/decimal-quantities

**Comment by typoman76** [comment]
I'm testing this on a dev environment and will give feedback soon.
