### ISSUE TITLE
"Create user account on purchase" and "On purchase add user to user groups" not working

### ISSUE THREAD

**Issue by ideasc** [concrete5-community-store/community_store#351]
"Create user account on purchase" and "On purchase add user to user groups" are working features or are only placeholder? On my project, they do nothing...
![screenshot](https://user-images.githubusercontent.com/37593541/37674134-65fd31a6-2c72-11e8-93d2-429d4fd1b5ff.jpg)

**Comment by Mesuva** [comment]
Those features _should_ be fully working.

One thing to keep in mind is that it doesn't create a user account until an order is in the _paid_ status. So if you just the Invoice method and put through an order that way, it doesn't create a the user account until the admin logs in and marks the order as paid.

A payment method like Paypal or Stripe on the other hand should mark an order as paid immediately.

**Comment by ideasc** [comment]
Yes, I used receipt, it's surely my problem, thanks and sorry...

**Comment by Mesuva** [comment]
No sorry needed, glad we've worked it out!

**Comment by typoman76** [comment]
I have an additional question to this. The option that a user is createad after a purchase is a setting on a specific product - right? 
I can't do this in general? I.e. after a customer has done the checkout process as guest and marked something like "create account".

**Comment by Mesuva** [comment]
@typoman76 There currently isn't an option for the customer to create a user account after or during the checkout process, it is either before the checkout (when you enable the option) or automatically if a product is purchased that forces the creation of an account.

**Comment by typoman76** [comment]
@mesuva - thanks for clearing this up. 
I will make a proposal as feature request for this. But this will work for now. :-)
