### ISSUE TITLE
Quantity Selector Still Displayed in Quickview Modal Even if Disabled 

### ISSUE THREAD

**Issue by pinecreativelabs** [concrete5-community-store/community_store#352]
I have noticed that the quantity selector is still visible within the quickview modal, even if I disable it from showing on the page. 

I have certain products where I do NOT want users to select a quantity (these are digital downloads), but the quantity selector is still visible and usable within the quickview modal.

**Comment by Mesuva** [comment]
Try the commit here and let me know how you go: https://github.com/concrete5-community-store/community_store/commit/a93f436cb73e0025281d7b8b896cf6e4f6f7f897
