### ISSUE TITLE
Google Analytics Ecommerce 

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#355]
You would n't happen to have a plug in for this, would you? I feel I am close, but my programming skills are lacking, so I am struggling to get the PHP to load, it crashes when I do the OrderItems:
`ga('ecommerce:addItem', {
  'id': '162',			// Transaction ID. Required.
  'name': '<?php $order->getOrderItems() ?>',		// Product name. Required.
  'sku': 'Test',				// SKU/code.
  'price': '1.65',			// Unit price.
  'quantity': '1'			// Quantity.
});`

**Comment by Mesuva** [comment]
I don't believe there's an add-on that does this yet.

What you've created at a casual glance looks fine to me logically.
What you need to be careful of is outputting product names or SKUs that may have quotes or other character in them that might break the javascript. You should look to use the json_encode function on those outputs.  So instead of the lines:
```
'name': '".$item->getProductName()."',
'sku': '".$item->getSKU()."',
```
use
```
'name': '". json_encode($item->getProductName())."',
'sku': '".json_encode($item->getSKU())."',
```

**Comment by mdius** [comment]
OK I made you suggested changes, but I had to do a few more.
I also am glad you suggested the " issue, I knew about it, but I thought I already removed them, I didn't.

Here is the new layout:
`    <?php }    

   $orderItems = $order->getOrderItems();
   foreach($orderItems as $item){
	   echo '<div class="CompleteQty"><span class="CompleteBlock"><b>Qty:</b> '.$item->getQty().'</span><span class="CompleteBlockLG">'.$item->getQty().'</span></div>';
       echo '<div class="CompleteProd"><span class="CompleteBlock"><b>Product:</b> '.$item->getProductName().'</span><span class="CompleteBlockLG">'.$item->getProductName().'</span></div>';
       echo '<div class="CompletePrice"><span class="CompleteBlock"><b>Paid:</b> $'.$item->getPricePaid().'</span><span class="CompleteBlockLG">'.$item->getPricePaid().'</span></div>';
       echo '<div class="clear"> </div>';
	   echo "
	   <script>
ga('ecommerce:addTransaction', {
  'id': '".$order->getOrderID()."',
  'affiliation': 'MDI',
  'revenue': '".$item->getPricePaid() * $item->getQty()."',
  'tax': '".$item->getTax()."',
});

ga('ecommerce:addItem', {
  'id': '".$order->getOrderID()."',
  'name': '". json_encode($item->getProductName())."',
  'sku': '".json_encode($item->getSKU())."',
  'price': '".$item->getPricePaid()."',
  'quantity': '".$item->getQty()."'
});

ga('ecommerce:send');
</script>
	   ";
   }
 ?>

<?
       echo '<p><b>Tax Total:</b> $'.$order->getTaxTotal().'<br>';
	   echo '<b>Shipping Total:</b> $'.$order->getShippingTotal().'<br>';
	   echo '<b>Order Total:</b> $'.$order->getTotal();
	   echo "
	   <script>
ga('ecommerce:addTransaction', {
  'id': '".$order->getOrderID()."',
  'affiliation': 'MDI',
  'shipping': '".$order->getShippingTotal()."',
});

ga('ecommerce:send');
</script>
	   ";
  
?>
			</div>
		</div>
	</div>
</div>`
