### ISSUE TITLE
"Cash' payment method

### ISSUE THREAD

**Issue by fmourey** [concrete5-community-store/community_store#356]
Is it possible to add a "Cash" payment method ?
It would be for concert tickets, and to let the customer have the possibility to pay the day of the concert.

I suppose the easiest way would be to 'clone' the current basic invoice method ?

Ideally, I'd need 3 payment choices at checkout :
- invoice (bank transfer)
- paypal
- cash

Could you point me in the right direction as how to achieve this ?

Thank you very much !

**Comment by Mesuva** [comment]
If you didn't need a seperate invoice option, I would have just suggested your rename that one.
But since you need both cash and invoice, the process would be to clone the invoice method as you've suggested.

So try this one!
https://github.com/concrete5-community-store/community_store_cash

**Comment by Mesuva** [comment]
Great to hear.
I started to write a reply explaining how to build the add-on and realised that two or three more minutes would be all it would take to finish it off!
