### ISSUE TITLE
Attribute in checkout has no required attribute (terms and conditions)

### ISSUE THREAD

**Issue by typoman76** [concrete5-community-store/community_store#357]
I need a checkbox in my checkout for accepting terms and conditions.
So I created a checkbox attribute under oders/attributes. Then i marked 'required in checkout'. 
But it seems not required in checkout process. I can leave this attribute unchecked an go ahead. But for processing an order i need to have this required and it should not process until this is checked. 

Do i missunderstand the 'required in checkout' functionality? Is there another way to achieve this 'terms and conditions' checkbox?

Thanks for help :-)

**Comment by Mesuva** [comment]
I can see code in the checkout that adds an HTML5 attribute to the field if it's marked as required.
Here is what happens when I try to continue:

<img width="977" alt="screen shot 2018-05-15 at 2 19 09 pm" src="https://user-images.githubusercontent.com/1079600/40037185-fa333d26-584a-11e8-8c11-5ec9a442fa81.png">

I'm aware that this is only client-side validation, but in this kind of scenario I think that's acceptable.

I can't remember when this was added - what version of community store are you seeing this on?

**Comment by typoman76** [comment]
I have to recheck this on another installation. Good it works for you and thanks a lot for proofing it. 
On my installation even the value is not saved. And it has no html5 required attribute. 

Using C5 8.3.2
And Community Store 1.3.4

But i override it with a custom checkout. I copied checkout.php to /application/single_pages/checkout.php 

Perhaps this could be the cause. Will check some things and come back with my findings. But it doesn't seem to be a bug as I first thought.

**Comment by typoman76** [comment]
Update: Same behaviour on a second project. Newly added a checkbox to 'other customer choices' and tested it without override. Required attribute is not set. 
Have to retest it on a fresh installation later to see it is something other specific on my installations.

**Comment by Mesuva** [comment]
It's this line here that should be adding the required attribute:
https://github.com/concrete5-community-store/community_store/blob/master/single_pages/checkout.php#L137

It works in 5.7, but not in v8 I've just found.

Try using this line instead:
echo str_replace('<input', '<input required="required" ', $fieldoutput);

**Comment by typoman76** [comment]
Thanks Ryan! This is right and I see what the issue was with the space after '<input ', 
It is adding the required attribute now! And works like expected. 

It would be enought to set only 'required'. 
`<input type="checkbox" required name="example">`
and not 
`<input type="checkbox" required="required" name="example">`

I see a second issue:
The value of the checkbox is not saved correctly. It shows always 'no' 
I have checked this on the order page and in the confirmation email. It does not have any effect if I check or uncheck the box during checkout.

**Comment by Mesuva** [comment]
The saving bug was another v8 related difference

I've pushed an update here that improves the checkout javascript, to correctly detect the checkbox value.

https://github.com/concrete5-community-store/community_store/commit/ff6d5e0f20f991b5b06fcaf64057eb86ddda4369

Take note with the extra data attribute I've added on the the checkout single page:
https://github.com/concrete5-community-store/community_store/commit/ff6d5e0f20f991b5b06fcaf64057eb86ddda4369#diff-aa7353e5ebe715b3922ffcb83604eed2R125
- this is used to work out a translated 'No' value if the checkbox isn't checked.
It shouldn't break leaving that off (i.e. in an override), but it's better to have it there so the checkout clearly shows when the checkbox hasn't been ticked

**Comment by jasteele12** [comment]
I was just about to comment that the normal HTML posts **nothing** if a checkbox isn't checked, and can also pass a value="Terms Agreed" _(example)_ if checked.

I'm unclear why you would need to set an attribute if it isn't checked, but I probably am just not as familiar with how the CS code works.  Seems like a lot of possibly breaking code for a non-problem that doesn't handle the required attribute server-side?

**Comment by typoman76** [comment]
Many thanks for the fix! It's working and the valu is stored correct in the database. 
Now I have launched my first community store for a small fabrics store in our town. 
https://www.liliundmo.ch/shop
