### ISSUE TITLE
Skipping Orders

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#359]
I read your closed comment on the skipping orders (#278).

So, now I'm  wondering if there was a simple way to actually log those orders as incomplete or something to let us know they exist. If someone went that far and did not complete I'd like to know and to see if it is happening on a certain product or type of product.

**Comment by typoman76** [comment]
I use smartlook.com to record sessions of users. and one thing observed: 
customers are adding products to the cart. then on the checkout page they can choose to login/register or go as guest. if they register and log in they are redirected to a confirmation page and are lost. they don't go back to the checkout process. even if they could click on the cart icon. and mine is not small ;-)
So a redirect to checkout after login would help if there is something stored in the cart.

**Comment by typoman76** [comment]
After rereading your post I recognized that I missunderstand 'skipping'. Your issue ist with customers loosing during checkout. But perhaps the free version of the mentioned tool helps you too!

**Comment by cahueya** [comment]
I've got this on all the CS installations I've used, as it is the only option to make "failed payments" visible and there are some failed payment with PayPal and such...

So I do think this should be standard behaviour or a preference setting somewhere.

**Comment by Mesuva** [comment]
I think this should be a preference setting.
I don't think it should be the default though, just easy to turn on and off.

**Comment by mdius** [comment]
Thank you!
