### ISSUE TITLE
Language Update & little code refactoring

### ISSUE THREAD

**Issue by difi68** [concrete5-community-store/community_store#36]
Hi, i have made a complete german translation of the store and due to that some small refactoring on several items in the code. At the moment, these changes are located in my fork
So, if someone is interested in this, i can publish this.
But how can i pull this into the github ? It seems that i don't have write permission.

**Comment by Remo** [comment]
1. You should have created a new branch. Never commit to master if you are working on a forked repository
2. You can't directly commit to this repo, that's the whole idea behind pull requests.
3. You should be able to open this page and create a PR there https://github.com/concrete5-community-store/community_store/compare

**Comment by difi68** [comment]
Thx Remo, i have created a pull request now and hopefully it was correct. ( i am from old school cvs and newby in git)

**Comment by Remo** [comment]
The PR looks good, but try to remember to always create a new branch. If a pull request of yours gets denied your master branch will be different from the upstream branch. If you then create a new pull request you'll have the old and denied changes in it. One can always rebase or create a new branch from an upstream branch, but it's much easier to just follow the best practices.

Remember that you also have to pull changes from the upstream master branch into your own master branch before you create new pull requests in the future.

**Comment by difi68** [comment]
Ok, thx a lot for the info remo!
