### ISSUE TITLE
Cannot Duplicate Products

### ISSUE THREAD

**Issue by pinecreativelabs** [concrete5-community-store/community_store#361]
I am using Community Store 1.3.4 on with Concrete 8.3.2. When I try to duplicate a product, I am getting an unexpected error: 
`Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/home/fwfpcom/mywebsite.com/application/config/doctrine/proxies/__CG__ConcretePackageCommunityStoreSrcCommunityStoreGroupGroup.php' (include_path='/home/fwfpcom/mywebsite.com/concrete/vendor:.:/usr/lib/php:/usr/local/lib/php')`

**Comment by Mesuva** [comment]
You could try visiting /index.php/dashboard/system/environment/entities/view and hitting the red 'Refresh Entities' button.  A backup beforehand is prudent, but I think this is safe activity.
