### ISSUE TITLE
Calling /productmodal throws an exception

### ISSUE THREAD

**Issue by typoman76** [concrete5-community-store/community_store#362]
The page /productmodal is indexed by search enginges an throws an exeption on calling directly. This has shown up on Google Search Console for me. 
Is there a way that this redirects to home if this is called directly?

**Comment by Mesuva** [comment]
I've pushed up a fix for this:
https://github.com/concrete5-community-store/community_store/commit/da78aee48517e20e0464f98c57d4ccbe66d1ffc8

**Comment by typoman76** [comment]
This works great! Many thanks!
