### ISSUE TITLE
CS v1.3.6 - count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by linuxoid** [concrete5-community-store/community_store#365]
Tried adding the first product and got:

count(): Parameter must be an array or an object that implements Countable
in
community_store/src/CommunityStore/Product/ProductOption/ProductOption.php 240

using C5-8.4.0 and PHP-7.2

**Comment by Mesuva** [comment]
I've fixed this with: https://github.com/concrete5-community-store/community_store/commit/5934992e80d503e7d5dee9087df9615c78f20f8f

It just wraps an if statement around the body of that code:
if (is_array($data['poSort'])) {
...
}

I thought we'd caught all the 7.2 issues at this point, but obviously not!
