### ISSUE TITLE
ShipStation

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#366]
Trying to set up Shipstation, you know any way to link that to this shopping cart?

**Comment by mdius** [comment]
Is this something that is possible?

**Comment by blueatlas** [comment]
What specific features of Shipstation do you want to utilize with Community Store? Do you only need to send orders to Shipstation, or integrate beyond that?

**Comment by Mesuva** [comment]
I get the impression from a quick look that Shipstation is a bit like Easypost, in that it's a shipping aggregator. 

I'd say it's another case of having to write a custom shipping method, very similar to the Easypost one, where it hooks into their API.

**Comment by mdius** [comment]
I believe you are correct.
I will check out Easypost, maybe that will do what we want already, but if not, what all would you need to quote this?

**Comment by Mesuva** [comment]
It's going to be about listing the features of ShipStation you'd want to use and describing a typical process. You could either put this out onto the jobs forum, or contact those that have worked on community store directly.
