### ISSUE TITLE
Order OptionList Attribute not saving selected.

### ISSUE THREAD

**Issue by ChrisStudy** [concrete5-community-store/community_store#372]
Hi 
Just find if you assigned OptionList attirbute type to CommunityStore Order, the option value which customer selected which is showing at order summary before check-out(which is not showing correctly it is showing avSelectOptionID instead of value). However, after checkout, if we check order information in dashboard, it will not showing the value at all. I have check the atSelectOptionSelected table, looks like it is not saving customer selection.

Will attach all the relevant screen shut.

![filling optionlist](https://user-images.githubusercontent.com/33081818/42141572-908f9506-7ddc-11e8-898c-b6a92a9ddcab.jpg)
![order summary](https://user-images.githubusercontent.com/33081818/42141573-90df2e36-7ddc-11e8-8418-41e1e8bc97a6.jpg)
![order-preview dashborad](https://user-images.githubusercontent.com/33081818/42141574-912f3ee4-7ddc-11e8-8c4e-cbcc898b8209.jpg)
![atselectoptionstable](https://user-images.githubusercontent.com/33081818/42141570-8fecf490-7ddc-11e8-8baa-29aacbdf7aa4.jpg)
![database table](https://user-images.githubusercontent.com/33081818/42141571-903def76-7ddc-11e8-93b2-da011a26edab.jpg)

**Comment by ChrisStudy** [comment]
An Updata the optionlist attribute value are showing normally at checkout summary, but still not saving in database and not showing in order view.

**Comment by Mesuva** [comment]
I've started looking at this - was your testing on v8, or 5.7?

**Comment by ChrisStudy** [comment]
Thank you very much, I was testing it on v8

**Comment by Mesuva** [comment]
This has just been fixed
