### ISSUE TITLE
Installer.php Line 30 die(_("Access Denied."));

### ISSUE THREAD

**Issue by linuxoid** [concrete5-community-store/community_store#373]
Is that an underscore typo inside the die(**_**?

**Comment by Mesuva** [comment]
It doesn't appear to break anything, but I don't actually know what that underscore function does!
But that line in general isn't needed in a class file - I've removed it and a few others, and I've done a fine and replace on these weirder versions.

**Comment by Mesuva** [comment]
Ps - thanks!

**Comment by Remo** [comment]
`_` is just a wrapper for the translate method used early in the process of concrete5.
No typo, but not needed in classes and in other elements we don't use `_` anymore. Those messages can stay untranslated.
