### ISSUE TITLE
C5 8.4.0 - CS 1.3.6 Setting default country in address attributes does not seem to work

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#374]
When trying to set the default language and force only one language, it does not seem to work.

![screenshot_313](https://user-images.githubusercontent.com/1224538/42204931-535e7e6e-7ea3-11e8-87fe-4b5cb0fb9ee6.jpg)

I go to the dashboard/store/orders/attributes and choosing the "Billing Address". And here I only set Denmark as country to use and at the same time I pick Denmark as default language.

![screenshot_314](https://user-images.githubusercontent.com/1224538/42205105-c4ecd01c-7ea3-11e8-8dee-3673e5bec67f.jpg)

When I now go to the check-out page, I still get all languages and it defaults to USA.

Is this a concrete5 or CS issue?

**Comment by Mesuva** [comment]
Confusingly, the list that appears in the checkout is controlled via _Members_ attributes, not the Order ones.  But when I configure this I normally edit both sets.

**Comment by MichaelMaar** [comment]
My bad, I'm a little rusty... When changed in member attributes it works. But I'm a little baffled as of I thought the same as you that they would be changed the same time. But it works now and I will close this.

**Comment by Mesuva** [comment]
It's a bit confusing, but there's a technical reason for it.

When you are logged in and you put in your contact details, they are updated against your member record (for checking out next time) - those are _member_ attributes that get saved.

When the order is actually placed, those details are stored against the order. 

So the checkout process does actually deal with two different sets of attributes, but you only see the one form (and that's going to be the member attribute settings)

**Comment by MichaelMaar** [comment]
That means that I should never touch the attribute under order?

**Comment by Mesuva** [comment]
I actually don't think there's a need to ever touch it - as long as it doesn't have different settings to those under the member I think it's fine.
