### ISSUE TITLE
Feature request - Make it so that the final receipt containe the same info as the receipt email

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#375]
I think that the final receipt page (after check-out completion) should reflect what the customer receives in the receipt email. Also that would be cool to be able to print.

**Comment by Mesuva** [comment]
I agree that it would be nice to show a summary at that point.
The current single page template for complete does already have some commented out example code showing how to fetch the order and output details - the thinking was it would then allow devs to customise that page to their liking.

But I think a modest summary would be good, as that would be equally easy to comment out if not wanted.
