### ISSUE TITLE
Display Total Weight in cart

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#376]
I use a weight / price  total for the possibility of free shipping. So, I'd like to display a total weight in the check out process. 

I am able to get it to display each items individual weight and multiply it by the qty to show the total weight per item.

In the /elements/cart_list.php I added 
`<?php
	$Weight = $product->getWeight();
		echo $Weight * $qty;
?> <?= Config::get('community_store.weightUnit'); ?>`

Then right below the </table> on the same page, but it only shows the weight of the last item.
I have tried several different weight codes, but I just don't know how to get the info, I know it must get it from someplace to add up the weight in the shipping.

![display weight](https://user-images.githubusercontent.com/28864099/42216652-959c65ce-7e90-11e8-8d2d-f0220684f910.png)

**Comment by mdius** [comment]
That gave an error, so I changed it too:
`<?php $weight = \Concrete\Package\CommunityStore\Src\CommunityStore\Cart\Cart::getCartWeight() ?>`

It worked!!

Thank you. I tried the "getCartWeight" I just didn't know how to call to it, so it returned empty.

**Comment by Mesuva** [comment]
Fantastic.

I can see what I did there, forgot to include an extra \Cart\.. glad you were able to spot that!
