### ISSUE TITLE
Products -> Detail Page still shows product's page after the page is deleted

### ISSUE THREAD

**Issue by linuxoid** [concrete5-community-store/community_store#378]
I guess it's the way Concrete5 works but it may be confusing to the Store user.

If you delete a product's page, it's deleted from the site tree but not from the database, it goes to the Trash and seats there until the Trash is cleaned. So

`if ($page->isError())`

will return false (in edit() of products single page controller).

But until then, if you go to Products -> Detail Page, it still shows Detail Page is set to: [product page]. So there's no way to generate a new page until the Trash is emptied. Maybe it's worth to add a warning to there to tell the user to empty Trash to enable new page generation?

**Comment by Mesuva** [comment]
This is an excellent point, there are ways to detect pages in the trash so this could be handled better.
