### ISSUE TITLE
Product Detail Page Option select not working

### ISSUE THREAD

**Issue by difi68** [concrete5-community-store/community_store#38]
In the product detail page are two issues causing 
a: the option select not working
b: the magnific Popup not working

There are wrong class names used in the script section.
Solution:
a: has to be _var pdb = $(this).closest('.store-product-block');_ instead of 
_var pdb = $(this).closest('.store-product-detail-block');
_
b: has to be _$('.store-product-thumb').magnificPopup({..._ instead of 
_$('.product-thumb').magnificPopup({..._

I think it is not necessary to create a pull on that, could be fixed by the way.

**Comment by Mesuva** [comment]
Thanks for this, I've fixed these things via:
https://github.com/concrete5-community-store/community_store/commit/48370cbfeb4533301a991a36b21ac80917ac5afe
