### ISSUE TITLE
Creating Additional Checkout Fields

### ISSUE THREAD

**Issue by Hunterm267** [concrete5-community-store/community_store#380]
The standard checkout form contains sections for billing information, shipping information, shipping, payment, etc.

I'd like to add an additional section to my checkout form to request "end-user information". Ideally, I'd only display this whenever a product in the customer's cart is in a certain group of products.

I've located the `checkout.php` single page, and familiarized myself with its layout. However, I have two questions:

- Is there a way to access parameters of the products in the customer's cart, to check to see if any of them are within a certain product group?
- Is it possible to / how difficult is it to create additional parameters for a `customer` object, so that I could create things like, `enduser_email` - similar to how calls are made to `$customer->getValue("shipping_last_name")`?

**Comment by dbuonomo** [comment]
Perhaps there is more than one way to do this, but in general, you can check if a product is in a group like this:

```
use \Concrete\Package\CommunityStore\Src\CommunityStore\Cart;
use \Concrete\Package\CommunityStore\Src\CommunityStore\Group;
use \Concrete\Package\CommunityStore\Src\CommunityStore\ProductGroup;

$cart = Cart:getCart();
$group = Group::getByName('{group name}');

foreach ($item in $cart) {
    if (ProductGroup::isProductInGroup($item, $group)) {
        // do something
    }
}
```

As for additional customer attributes, you can create those via the dashboard under Users -> Attributes, and place them into the Store Customer Info attribute set. Access them the same as other customer attributes:

$storecustomer->getValue('billing_first_name');
$storecustomer->getValue('{your new attribute}')
