### ISSUE TITLE
Two Feature Requests

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store#383]
I am unsure how to implement these two requests that I have.

1) I would like to be able to set a date for a sale price to expire. I see it as being a date selector just below the sale price field that, at least expires the sales price on that date. Ideally I see it as being two date selectors, one that is the sale start date and the other is the sale end date, so you could program in a sale ahead of time. 

2) I would like to be able to send the order confirmation emails to different addresses based on what is in the order. For instance, if someone buys an apple it would send an order confirmation email to the produce department. Or is an order includes some salmon, it would send an email to the seafood department. I see this working as a product attribute or some like that. Where when I'm adding products, there would be a field for me to include additional email address to send order confirmations to.

Any help is greatly appreciated!!

**Comment by Mesuva** [comment]
I think both of these features would be reasonably easy to implement, they'd just need to be done in the core of the store.  

I actually had to code the second feature for eCommerce for 5.6 at one stage, I did this with an extra product attribute and responding to the order event via an extra package - the same could be down with community store, but it's a feature I think is very handy to have included by default.

The main question I'd have is whether it would just collect up all the emails it needs to send to and copies them into the original order notification email, or, would it only include the product that is relevant in the order, effectively hiding the other products in the order (and maybe the totals).. what do you think?

**Comment by drumrby** [comment]
I think ideally it would be more like the second setup you mentioned. The emails to the additional address would only include the pertinent info to that product. That said, I can think of a couple scenarios where it would be handy to have pricing information included in those emails. So maybe that could be an additional checkbox (include pricing info) next to additional email addresses field?

But I think if all of that is not feasible the ability to copy additional email address on the original order notification email would be very handy.

**Comment by Mesuva** [comment]
Just an update with this, I've effectively completed the second part here, where you can enter in additional emails against a product, and those are used when that product is included in the order.
It's been pushed up to master, but will be included in the next release.

Might be worth creating a new issue for the first item so it doesn't get forgotten.

**Comment by drumrby** [comment]
Amazing. I look forward to using that feature. I have created a new issue for the other item, #404
