### ISSUE TITLE
Overlapping fieldsets

### ISSUE THREAD

**Issue by typoman76** [concrete5-community-store/community_store#386]
I had some calls from customers that they can not change the status of an order.
After checking the issue I have seen that there are overlapping fieldsets. This issue is based on the concrete5 dashboard-theme.
I opened an issue here: https://github.com/concrete5/concrete5/issues/7020

Sceenshot on community store 1.4beta and concrete5 8.4.2:
![image](https://user-images.githubusercontent.com/16708175/44999094-14f2c600-afbb-11e8-96e6-cdd4b3753908.png)

**Comment by Mesuva** [comment]
I've pushed up a fix for this - just the removal of those fieldsets.
I'd like to re-organise this page a bit, since there are some further features I'd like to add.

I'm thinking maybe some tabs or similar so the page isn't so long.
