### ISSUE TITLE
trailing_slash config setting gives json error on add to cart

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#387]
Switching the concrete5 config setting seo.trailing_slash to true stops the add to cart function from working.

The following error is generated in the console when the add to cart button is clicked on the product page:

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by Mesuva** [comment]
I've pushed up a fix for this. 

It feels a bit hacky, there may be a cleaner way to achieve this, but it's also not a big change either.

It also includes something to add a version string to js and css files, so that when the version of the package changes they are downloaded fresh

**Comment by katalysis** [comment]
Thanks @Mesuva seems to be working well now.
