### ISSUE TITLE
How to change order numbers in community store

### ISSUE THREAD

**Issue by surfsupjoe125** [concrete5-community-store/community_store#388]
Just wondering if anyone has wanted to do the same and where that file is located

**Comment by Mesuva** [comment]
There is discussion here about it:
https://github.com/concrete5-community-store/community_store/issues/382

I'd personally just adjust the database auto-increment number, as per:
https://github.com/concrete5-community-store/community_store/issues/218#issuecomment-294826129

**Comment by surfsupjoe125** [comment]
Thanks Ryan

*Joe Notarianni*
Tel:(239) 434-7095
Cell:(239) 298-3984
