### ISSUE TITLE
Error in OrderItem.php when using Digital Downloads

### ISSUE THREAD

**Issue by difi68** [concrete5-community-store/community_store#39]
When i'm using the digital downloads feature, i receive the following error during the checkout process:

_Type error: Argument 1 passed to Concrete\Core\Permission\Access\Entity\UserEntity::getOrCreate() must be an instance of Concrete\Core\Support\Facade\UserInfoFactory, instance of Concrete\Core\User\UserInfo given, called in <path_to_my_c5_instance>/packages/community_store/src/CommunityStore/Order/OrderItem.php on line 280_

I'm using C5 v5.7.5.6
Any ideas how to fix this ?

**Comment by Mesuva** [comment]
Digital downloads is something I haven't tested much, I've had it listed as something that is likely to have a few issues. I think it may need to be reworked a bit, I'll try to look at this myself soon.

**Comment by Mesuva** [comment]
I believe I've fixed this with:
https://github.com/concrete5-community-store/community_store/commits/master

I basically removed code that was manipulating permissions on the files - I found it a bit too risky.
I also fixed a couple of other bugs along the way.

Are you able to confirm this is fixed for you?

**Comment by difi68** [comment]
Yes, it looks good to me. Thx!
