### ISSUE TITLE
[Feature Request] Alter Express Object Attributes

### ISSUE THREAD

**Issue by BloodyIron** [concrete5-community-store/community_store#391]
Not yet finding if this is possible, so sorry if I missed it.

The idea is having it so when someone buys something, it alters one or multiple attributes to (an) existing Express Object(s). Such as, showing that someone bought a ticket for an event, and putting their username in a list, or altering it so they now have that ticket bought.

Is this currently feasible? If not, could we get this added please?

**Comment by mnakalay** [comment]
You could use community store events to react when somebody buys something and do whatever you want with the data.

The event you probably want to use is on_community_store_order which is dispatched when an order has been completed. From that event, you get the order object and from that object, you can grab the customer ID which in turns allows you to get the customer details and do whatever you want with them like updating an Express object.

**Comment by BloodyIron** [comment]
@mnakalay well, I'm more of a system arch/implementer myself. How would I connect those dots? I think I understand what you mean, but I'm not sure how to execute on that.

**Comment by mnakalay** [comment]
@BloodyIron first I'd suggest you have a look at the event example package @Mesuva has. You can find it here: https://github.com/concrete5-community-store/community_store_event_example

You can just use that as a base for what you want to do and make sure it hooks to the event you need. In my previous message, I suggested on_community_store_order 

I also suggest you change the package handle so it doesn't interfere in the future if you need to use this event package example again.

Now that's just the first step. Your second more difficult step is to do the Express stuff.

Luckily, Express does have some good doc available and it works in a way that tries to be intuitive. I suggest you read this page from the doc: https://documentation.concrete5.org/developers/express/creating-reading-searching-updating-and-deleting-express-entries.

As a quick-and-dirty first step helper, what you can do is:

In the event package, edit the file controller.php and, inside the on_start() function, keep only the event you need.

If you keep the on_community_store_order as I suggested you see that it calls the function 'orderPlaced' which is inside the file community_store_event_example/src/Event/Order.php

You will put your Express updating code inside that 'orderPlaced' function.

If you don't need any of the product related events, just delete the file Product.php

you see you can get the order object from the even in that function by doing:

`$order = $event->getOrder();`

Once you have the order you can get the user ID doing 

`$customerID = $order->getCustomerID();`

that customer ID is actually the same as the Concrete5 user ID so once you have it you could use C5 user helpers but I suggest you use Community STore own customer class.

So you would so something like:

`$customer = new \Concrete\Package\CommunityStore\Src\CommunityStore\Customer\Customer($customerID);`

and then you could do:

`$email = $customer->getEmail();`

For the Express side of things, I'll let you read the doc.

If you want to know more about what you can do with the order and the customer, look in Community Store for the files community_store\src\CommunityStore\Order\Order.php and community_store\src\CommunityStore\Customer\Customer.php

Any function in them that starts with 'get' and is public you can use the same way we did above to get the data you need. So, for instance, you can do:

`paymentMethodeName = $order->getPaymentMethodName();`
