### ISSUE TITLE
Groups Error

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#393]
After upgrading to C5 8.4.3 and CS 1.4.2 and going to Community store->Groups, I get this error. But honestly, I don't know if the error was already in existence prior to upgrading or not since I don't really check out all the features every time I upgrade an addon. ** Actually I performed this upgrade locally first and it was when I upgraded from 1.4-1.4.2 locally that this error occurred. On the live site I am still at 1.3.6. I will wait to hear from you prior to updating.

<img width="1275" alt="screen shot 2018-10-04 at 8 10 15 am" src="https://user-images.githubusercontent.com/7119442/46473234-6904ec00-c7ad-11e8-8c9d-11974fdefb72.png">

**Comment by Mesuva** [comment]
This seems to the same sort of error as this one here:
https://github.com/concrete5-community-store/community_store/issues/333

The solutions appears to be to visit /index.php/dashboard/system/environment/entities/view and hit the red 'Refresh Entities' button.

I've not been able to work out what causes this, as it seems to be a bit random (and I've seen it with other packages unrelated to Community Store).

**Comment by jasteele12** [comment]
I've also run into this problem sporadically without CS installed. Had it happen on a virgin 8.4.0 to 8.4.1 upgrade and several client's upgrades (not good).    Regular humans will have no idea what this error message means.  The only information I received after inquiring about it was "Refresh Entities".

Just for documentation's sake, this can now be done from the command line (and avoids any possible PHP timeouts as mentioned in [#333](https://github.com/concrete5-community-store/community_store/issues/333))

`concrete/bin/concrete5 c5:entities:refresh`
Doctrine cache cleared, proxy classes regenerated, entity database table schema updated.

Unfortunately, this doesn't appear to exist (yet) in the documentation (I keep getting _logged out_ on both [legacy](https://legacy-documentation.concrete5.org/) and [documentation](http://documentation.concrete5.org/) sites using my c5 login, which works fine on concrete5.org):
[https://documentation.concrete5.org/developers/appendix/cli-commands](https://documentation.concrete5.org/developers/appendix/cli-commands)

This appears to be added in **8.4.2** (ran in a directory containing core zip files):

` for f in concrete5*\.zip*; do (echo $f; unzip -v $f | fgrep Command/RefreshEnt); done`

Hope this helps someone in the future...

**Comment by teknoziz** [comment]
I tried refreshing the entities and got this:

> An unexpected error occurred.
An exception occurred while executing 'ALTER TABLE AttributeSets ADD CONSTRAINT FK_FCA02D5FCE45CBB0 FOREIGN KEY (pkgID) REFERENCES Packages (pkgID)': SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`lin_mfg2`.`#sql-830_b1`, CONSTRAINT `FK_FCA02D5FCE45CBB0` FOREIGN KEY (`pkgID`) REFERENCES `Packages` (`pkgID`))

**Comment by teknoziz** [comment]
However, it _did_ appear to fix the Groups error.

**Comment by Mesuva** [comment]
There appears to be a few references to this kind of error:
https://www.concrete5.org/community/forums/customizing_c5/foreign-key-problem-on-packages
Following that to github, there's a fair bit of discussion and some suggested fixes
