### ISSUE TITLE
dimensions not showing properly

### ISSUE THREAD

**Issue by xb385** [concrete5-community-store/community_store#395]
i entered the following data in my product settings:
length 300
wide 150
height 100

but i get this output, seems like length is not being outputted correctly:
dimensions: 150.00x150.00x100.00 cm

edit: found the bug, fixed and commited it

**Comment by Mesuva** [comment]
Easy fix here: https://github.com/concrete5-community-store/community_store/commit/5d55455fdf79abe44a541072fa304ad33f136fc8
