### ISSUE TITLE
btCommunityStoreProductListGroup needs a Primary Key

### ISSUE THREAD

**Issue by losttheplot** [concrete5-community-store/community_store#397]
> An exception occurred while executing 'DELETE FROM btCommunityStoreProductListGroups where bID = ?' with params ["426"]: SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (xxx.btCommunityStoreProductListGroups) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER

Whilst the lack of a primary key on a table may not cause any issues on standard hosting platforms, it is a show-stopper on a PXC cluster in strict mode. There may be other similar tables, I haven't checked. You might want to consider making this project strict-mode compliant as you go, to save problems in the future.

Rightly or wrongly, I have worked around this by adding an extra column as follows:
ALTER TABLE `btCommunityStoreProductListGroups` ADD `pkey` INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`pkey`);

I'm loving what Mesuva and the team are doing with this project and I'm just trying to help :)

EDIT: I've just taken a quick look at all the project db tables and everything else looks like it has a PK, so it's just this one that needs a tweak :)

**Comment by Mesuva** [comment]
I've added in a key for this table, via https://github.com/concrete5-community-store/community_store/commit/b949894fba4738a161c62ff67ebccfa2f9887b7d

I'm assuming that with PXC, a primary key can use multiple fields, which I've done instead of adding another column just for that purpose.

**Comment by losttheplot** [comment]
I've tried your suggested schema and it seems fine thanks :)
