### ISSUE TITLE
$('.store-checkout-form-shell form').size is not a function

### ISSUE THREAD

**Issue by losttheplot** [concrete5-community-store/community_store#398]
Line 414 of /community_store/js/communityStore.js is as follows:

`if ($('.store-checkout-form-shell form').size() > 0) {`

However .size() was depreciated in jQuery 1.8 and dropped for 3.0. Whilst Chrome doesn't seem to have a problem with this, it causes the pop-up cart to fail in iOS Safari with "$('.store-checkout-form-shell form').size is not a function". Thus the project cannot be used on an iPhone - or my iPhone at least!

I recommend updating line 414 as follows:

`if ($('.store-checkout-form-shell form').length > 0) {`

...and also changing line 740 to this for good measure:

`if ($(this).find('.store-btn-add-to-cart').length > 0) {`

I'm not familiar with the process of contributing to GitHub projects, so I'll just leave this as a suggestion if that's okay :)

**Comment by Mesuva** [comment]
Thanks for this, I agree this is a good change to make - I've pushed something up to the master.

Interestingly I did try the original code with iOS, but didn't pick up any issues with the pop up cart, but maybe it's Safari version specific. Nevertheless, this tidies things up.

**Comment by losttheplot** [comment]
The JS failure/error also occurred using the Developer's Responsive Mode tools in Safari, with the emulator in its standard 'iOS 11.3' mode. Either way, glad to help.

I'm loving what you're doing with this project, by the way. We use Magento2 for our largest client's ecommerce needs, but I hate it with a passion. Everything about Magento2 is just so damn overly complex and resource-hungry, I weep sometimes. We run each instance on a dedicated hi-spec bare-metal replicated platform (with a dev/prod release set-up) with every speed enhancement going, but it still struggles to feel fast sometimes. The thing is, when it comes to enterprise features, robustness on enterprise platforms, and scalability, there's not much to touch it. Plus it's OS so I shouldn't complain, even though I do ;)

But when you come back down to the other end of the scale in terms of features and scalability, you're left with the likes of WooCommerce (the best of the bunch in my opinion), which means working with the illogical mess that is WordPress. Not that WooCommerce is particularly bad per se (for something built on WP) - it isn't - but if one wants to build a decent brochure or interactive website (e.g. with bespoke API-chatting modules) that can also be used to sell products, then concrete5 with community_store is the perfect solution. 

In its original guise, vivid_store was limiting and very rough round the edges, but what you're doing with it now is impressive (speaking as someone who used to roll his own ecommerce solutions in the early days), and I for one am very grateful for the time that you and the team are putting into this project so that we all might benefit from your efforts. Thank you, and well done :)

**Comment by Mesuva** [comment]
Thanks for the really positive feedback here!
