### ISSUE TITLE
Email Address Format Validation

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#399]
Here is the scenario:

Someone places an order and gets an typo in their Email Address like "myadress@gmail".

This will just throw an error to the logs but the user receives no notification of the problem and no order confirmation email.

So it clearly is too much to do a proper email address validation, but maybe we could integrate a validator for a proper format? So at least those that totally forget to put their whole address into the Checkout will realise?

**Comment by MichaelMaar** [comment]
Actually, I have thought the same and I think the best solution would be typing and then verifying the same email address in a second email field. It's kind of a problem when we are not able to contact the customer by email.

**Comment by losttheplot** [comment]
I'm not part of the dev team but for what it's worth, even Magento2 suffers from this issue, with failed email deliveries having to be forwarded to the client (retailer) for manual checking and correction. Having a second email form field is not good for the majority of users who are able to get it right first time. However I can thoroughly recommend Bootstrap Validator ( http://1000hz.github.io/bootstrap-validator ) as being a simple yet surprisingly powerful validation tool once you start to use the **data-remote** feature for AJAX checking of data. Anyway, as this issue explains > https://github.com/1000hz/bootstrap-validator/issues/455 even test@g (or myadress@gmail) is a valid address, but there's nothing to stop you adding pattern matching such as `<input type="email" pattern=".*@\w{2,}\.\w{2,}" class="form-control">`

**Comment by Mesuva** [comment]
I think the main concern here is that on failure of the customer email, the order _notification email_ isn't being sent. That says that whatever email related exception is being thrown isn't being handled. That would be the priority to fix first.

**Comment by losttheplot** [comment]
Ah, right; well if an incorrect email address is stopping the retailer's notification email being dispatched then yes, this is a more serious problem. Sorry, I hadn't appreciated that this was happening, or not!

**Comment by Mesuva** [comment]
I've made some changes here: https://github.com/concrete5-community-store/community_store/commit/614c0e330677766177104bf17e95d4621d541326

This means now the order notifications send first instead. I've also added some exception handling and logging, which might help with debugging - I find this hard to test though!
