### ISSUE TITLE
Pricing Tiers

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#400]
Using Pricing Tiers, is there a way to do a 50 + amount?

https://www.mdius.com/products/tilt-switch-1-amp-valox-case-06-inch-leads

Just had someone order 100 pcs and it used the full 1 to 9 piece price.

**Comment by Mesuva** [comment]
I see this as a bug in community store.. you shouldn't have to define some very large number or some other way, if someone orders larger than your largest tier it would expected you get the last tier's price.

So I've pushed a fix for this code, pretty easy to update:
https://github.com/concrete5-community-store/community_store/commit/5824179801a511227c23fc42a2a139c2f101e772

**Comment by mdius** [comment]
Thank you, worked perfectly.
