### ISSUE TITLE
Orders Page with direct link to print?

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#402]
I got some feedback from clients that use the shop and they wish for a function in the "Orders" Dashboard page:

A quick-linked print function. So basically the same thing that happens when you go "print order slip" when viewing an actual order, but also on the summary of the orders.

The reasoning is:

Right now, we have two ways to jump from the Orders List to the actual Order:
1. Click Order Number
2. Click "View" Button

In many cases, when there is a payment processor which marks an Orders as Paid, there is no need to actually view that Order in Detail. But there is always the need to Print the Order slip.

So how would it be to replace the "View" Button with a "Print Order" Button to save that extra Click-New Tab-Click-Close Tab Workflow for printing the Order Slip which is theoretically always necessary (accounting / attach to delivery)?

I know I can do this with a singlepage override. This is for discussion if it seems useful for anyone else.

**Comment by Mesuva** [comment]
What about if we used one of those bootstrap drop down buttons? Like this:
<img width="386" alt="screen shot 2018-11-26 at 10 53 51 pm" src="https://user-images.githubusercontent.com/1079600/49047073-3b955700-f1ce-11e8-980c-9391130c43be.png">

**Comment by Mesuva** [comment]
Could potentially put some other options in that drop down as well.. maybe a cancel

**Comment by cahueya** [comment]
For the usecase I think of, this would help half-way. Right now the customer goes like that:

1. He opens up the "Orders" Page
2. He opens up his Paypal Payments page
3. He opens all the PayPal-paid Orders (check by name of customer) in new Tabs
4. Now with 85 open Tabs which are all in the correct sequence for how the PayPal orders where paid, he goes through all of them and prints the Orders Slip as a "Print to PDF". 

This way, he got all the orders slips in their correct sequence in a folder as PDFs. So for accounting, he just batch-prints them and that's it.

The dropdown would save the visit to the Order Details Page, yes. So all the actions that do not need further Information (Print, Cancel...?) could be added like that, yes. 

Though not sure if a button dropdown or a button group is better.
https://getbootstrap.com/docs/4.0/components/button-group/

**Comment by Mesuva** [comment]
I think the dropdown makes sense to me, to keep the space used to a minimum.

I've pushed up to the master a commit here:
https://github.com/concrete5-community-store/community_store/commit/cdcbf9273f2f641563b2a541d505c2a9ec76708c

But I also re-worked the way the order slip urls are handled, so they use the order ID in the URL (easier to quickly change by hand), but also so they are more secure.
So this would need to be applied:
https://github.com/concrete5-community-store/community_store/commit/4b170a41ab4118a53a4bc98967a1a903bfa5308d

Sorry it's a bit messy, I'm trying to clean up a lot of things before the next release.

**Comment by cahueya** [comment]
Thank you!
