### ISSUE TITLE
Search on "Reports" Page?

### ISSUE THREAD

**Issue by cahueya** [concrete5-community-store/community_store#403]
This is a feedback I got from a customer that sells a lot of digital goods.

When they want to look at the sales numbers of a product (dashboard/reports/product), they need to jump through a lot of pagination to find that product they are looking for. Filtering by date is not sufficient to reduce those steps.

Is it possible to get a Search Box there that will filter out the possible products like the product block does?

**Comment by Mesuva** [comment]
I've added this feature, along with a tidy to the page product report page overall:
https://github.com/concrete5-community-store/community_store/commit/bfbce1c51ec5da5f2d096044fede010e0bb79acb

A follow up commit is also relevant:
https://github.com/concrete5-community-store/community_store/commit/f5e835af760500813bc30a44e9f1e5332c37feab

**Comment by cahueya** [comment]
This can be closed I think
