### ISSUE TITLE
Discount Set to $0.00

### ISSUE THREAD

**Issue by tbrown-hub** [concrete5-community-store/community_store#405]
Is this possible to have a product that if the correct discount code is entered and the value of the code is set to $0.00 the payment method (auth.net) does not appear. Currently, it does not allow you to bypass the payment method. 

Thank you

**Comment by Mesuva** [comment]
You can't make a zero payment with Auth.net - that method would have a minimum configured.

What you can do is also enable the Invoice method, rename it to suit, and configure it only to appear for 0 to 0.01 (use the Minimum Order Value and Maximum Order Value fields to do that).
