### ISSUE TITLE
Unable to add Product Attributes - V1.4.7

### ISSUE THREAD

**Issue by system19** [concrete5-community-store/community_store#406]
When trying to save a newly created **product attribute** on the product attribute page it just goes blank and no product attribute is added to the DB. This issue isn't present in V1.4.2. I guess it is caused by changes to /community_store/src/CommunityStore/Product/Product.php in the last few updates but  fixing the issue is well beyond my coding skill level. As you are changing to the V8 version do you think you will spend time on addressing this issue or would I be better to just try and upgrade my instance of CommunityStore to V8?

**Comment by system19** [comment]
I uninstalled 1.4.7 and then installed 2.0.4 but during installation I received an error that while executing ALTER TABLE CommunityStoreOrderAttributeKeys...... Cannot add or update a child row: a foreign key constraint fails on...... REFERENCES `AttributeKeys` (`akID`) ON DELETE CASCADE. 
I uninstalled 2.0.4 and then deleted both CommunityStoreProductAttributeValues and CommunityStoreProductAttributeKeys tables and then reinstalled 2.0.4
Everything appears to work fine now. Just had to add the Product Attributes again. All other store data was good.
Not sure if its worth your time to fix 1.4.5+ as you are releasing V8, Just letting you know that issues may appear if using product attributes. Thanks

**Comment by Mesuva** [comment]
That's interesting, what about all the order attributes, did that data remain?  Or did you not have any test orders in place?

I've simply not tested an upgrade for 1.x to 2.x of community store yet myself.

With the original issue, I can see that in 1.4.7, I'll look for a fix for that. I'd like to keep that branch stable and updated as long as I can really.

**Comment by Mesuva** [comment]
(but for a new project, using the v8 branch is probably going to be the best way forward, it's proving fairly stable for me, just be on the look out for minor fixes along the way)

**Comment by system19** [comment]
I only had demo products, no orders. I like the idea of using the V8 version without the legacy code so will go with that branch.

**Comment by Mesuva** [comment]
I have fixed the current master branch saving/editing:
https://github.com/concrete5-community-store/community_store/commit/d038aa9363668449463c4e8c1eae49df6c72ef46
