### ISSUE TITLE
Custom Product attributes broken on upgrade

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#407]
Following an upgrade from concrete5 version 5.7.13 to version 8.4.3 custom product attributes that I created have broken.

The values associated with the attributes are no longer available on the product page and when I try to edit the attributes through the dashboard I get the following error:

Call to a member function getAttributeType() on null

/var/www/vhosts/laserphysics.co.uk/httpdocs/packages/community_store/controllers/single_page/dashboard/store/products/attributes.php90

Which references this:
            $type = $key->getAttributeType();

Newly created attributes work and are editable. But I have lots of data in the existing attributes and need to recover them somehow.

**Comment by Mesuva** [comment]
Did you happen to run this bit of manual SQL after that 5.7->v8 upgrade?

https://github.com/concrete5-community-store/community_store#compatibility

**Comment by katalysis** [comment]
I did run that but now looking again, the attributes had NULL as the package ID and were ignored.

Updated in the database and now all fixed.

Thank you.

**Comment by Mesuva** [comment]
Well I'm glad to hear that it's resolved

Do you think there was something wrong with the query, or do you think another one needs to be run?
