### ISSUE TITLE
Single pages appear in the sitemap

### ISSUE THREAD

**Issue by mnakalay** [concrete5-community-store/community_store#408]
Hey Ryan,
When generating a sitemap for the site, /cart, /checkout and /checkout/complete are listed. Maybe they should get the proper attribute, so they are not listed?

**Comment by Mesuva** [comment]
Done!

https://github.com/concrete5-community-store/community_store/commit/ade95a50f8e259a503335a523d1c8be1865a6ae2

(and in v8 branch as well)
