### ISSUE TITLE
Typo in currency select option

### ISSUE THREAD

**Issue by 4ndygriffiths** [concrete5-community-store/community_store#41]
I have been testing this using Stripe and GBP sterling as the currency. I got back an error regarding "Invalid currency". Looking in the this file community_store_stripe/src/CommunityStore/Payment/Methods/CommunityStoreStripe/CommunityStoreStripePaymentMethod.php on line 44 there is a very small typo:

'GPB' Should be 'GBP'

That fixes it.

**Comment by Mesuva** [comment]
Thanks for this, I've fixed it with: https://github.com/concrete5-community-store/community_store_stripe/commit/597cf43f25bfbec502430c645e82f6f747a498ce

**Comment by 4ndygriffiths** [comment]
Nice one, That was fast. Great product BTW.

**Comment by Mesuva** [comment]
It's certainly getting there!

If you can lend a hand on anything it would be appreciated, even if it's just a bit of testing/bug reporting or discussion in the issues - it all adds up.

**Comment by 4ndygriffiths** [comment]
More than happy to help out as and when. When I get some time I will give it a good test run and try and weed out any issues. Although I must say on first glance it is more than stable.
