### ISSUE TITLE
Installing Store Packages for Concrete5-8.4.3 / 8.2

### ISSUE THREAD

**Issue by Mesign** [concrete5-community-store/community_store#411]
I had the latest version of Concrete 5 (8.4.3) installed. I could install the Community Store but I couldn't install any package like: community_store_mollie, community_store_shipping_tablerate, community_store_toolbar_buttons. 

As a temporary solution I went for a fresh install of 8.2 but still can't install the store packages. (other packages I can install). What am I doing wrong?
![schermafbeelding 2019-01-04 om 11 52 50](https://user-images.githubusercontent.com/24596881/50684902-7c775b80-1017-11e9-8cd4-4a41ca565d8d.png)

**Comment by Mesuva** [comment]
The main problem here is that you've still got -master in the folder names of the packages.
Where available, I'd suggest you download a release zip of each package, but if those aren't available and you download the master you just need to remove -master from the folder names.

What version of community store are you installing?
With the 2.x version, please note that you may have some issues installing some of the shipping related add-ons. (I'm working on this and will be pushing something up to github to address soon)

If you are using 1.x, all should install cleanly.

**Comment by Mesign** [comment]
Oké thank you for the explanation! 

I'm just starting with building the webshop. Are there any difficulties updating from 1.x to 2.x otherwise it would be smarter for me to start building it with the latest versions (2.x).

**Comment by Mesign** [comment]
Thank you, I will do that.
