### ISSUE TITLE
Installing community store removes Set dropdown on edit user attribute

### ISSUE THREAD

**Issue by rosie607** [concrete5-community-store/community_store#415]
Installing community store removes Set dropdown on Edit Attribute page. 
Also if you then save the attribute it removes it from whichever set  it was in.

If I make any changes to a user attribute I have to go to the set, add it back in then reorder the attributes every time. Meh 

Steps to reproduce, install of C5 8.4.4, install latest community store version downloaded today.

<img width="1442" alt="screenshot 2019-02-07 at 18 06 40" src="https://user-images.githubusercontent.com/11563269/52433018-e9dd4700-2b03-11e9-86cb-f461ac531567.png">
<img width="1442" alt="screenshot 2019-02-07 at 18 06 07" src="https://user-images.githubusercontent.com/11563269/52433019-e9dd4700-2b03-11e9-90b8-95c4d33cdb87.png">

I don't know if it's relevant but I was also having another issue with sets.
[https://www.concrete5.org/developers/bugs/8-4-4/assigning-a-user-attribute-set-stops-user-attribute-options-chan/](url)

**Comment by Mesuva** [comment]
Somewhere along the line the installer for Community Store was set to modify user attributes to be able to appear in multiple sets. I can't actually recall why this was done.

But the fix appears to be quite simple. In the AttributeKeyCategories database table the row for the handle 'user' ends up with a value in the akCategoryAllowSets column of 2. Changing that back to 1 makes the set dropdown reappear.

I think I'll probably just be able to take that line in the installer out without any repercussions, but if you notice anything weird after this tweak please let me know.

**Comment by rosie607** [comment]
Great, thanks, I've made the change and the Set field is back. Will let you know if I run into any issues :)
