### ISSUE TITLE
Chainging Option List from Dropdown to Radio Buttons fail on save

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#416]
It seem that the function to choose Radio Buttons is not saved when saving the product. I have tried various ways to make the radio buttons stick when saving with no luck.

Concrete5 version 8.4.4
Community Store version 2.0.6 latest git

Explanation:

**1. The database table before the save (I changed things in the database directly to make it work)**

![screenshot_347](https://user-images.githubusercontent.com/1224538/52487490-0d64c800-2bbe-11e9-9ccf-5d0a9f80f412.jpg)

**2. I am saving the radio button option**

![screenshot_348](https://user-images.githubusercontent.com/1224538/52487865-de028b00-2bbe-11e9-913d-bee413c44fc3.jpg)

**3. After I have saved I go back to have a look (the dropdown is back)**

![screenshot_349](https://user-images.githubusercontent.com/1224538/52487879-e3f86c00-2bbe-11e9-8880-cd771f524845.jpg)

**4. The database after the save (the radio is saved 2 rows above in a text field box).**

![screenshot_350](https://user-images.githubusercontent.com/1224538/52487886-e78bf300-2bbe-11e9-842f-285c367c8267.jpg)

It acts kind of strange.

**Comment by MichaelMaar** [comment]
Just to add to this.
I moved the option with the radio buttons to the top of the option list. Now I am able to save OK.

**Comment by Mesuva** [comment]
I think I know why this is happening, will fix early next week.

**Comment by MichaelMaar** [comment]
@Mesuva did you find time to find a solution to fix this?

**Comment by Mesuva** [comment]
Sorry, slipped my mind, try the addition here:
https://github.com/concrete5-community-store/community_store/commit/89b7793bbe1a0c3911441fe0f37afde1cd750d58

**Comment by MichaelMaar** [comment]
That seemed to make it work as expected... Thanks...
