### ISSUE TITLE
What's the difference between VividStore & CommunityStore, which one do we use?

### ISSUE THREAD

**Issue by ramonleenders** [concrete5-community-store/community_store#42]
Haven't really been following VividStore, but now I see this one that looks much alike. Is VividStore going it's own way, or is that project being left behind or what happened here?

(https://github.com/VividWeb/vivid_store)

So best question would be, which one to use of the 2?

**Comment by Remo** [comment]
Ryan has rewritten pretty much most of the code by now. I can't speak for him, but as far as I know he and others needed some changes that didn't happen to VividStore so that community store was born.

Unlike VividStore we have several people who have access to this repo. In the end it's more like a community project, eventhough Ryan does pretty much most of the work at the moment. I switched to community store mostly because it's more active, pull requests get reviewed and merged much faster and new features get added more frequently.

I've seen some changes in VividStore lately, guess Michael has a bit more time again.

**Comment by Mesuva** [comment]
Remo has summarised that quite well.

Feature wise the two are pretty similar and achieve the same goal, but as Remo has mentioned the code underlying most of it has been quite heavily rewritten - pretty much every file has been reworked substantially. It really just shares some history, but they're very different code bases now.

The significant feature differences:
- Blocks and single pages are by default marked up with bootstrap styling, so it's directly compatible with Elemental. It doesn't have it's own style as such. 
- Code wide it mostly uses Doctrine for models, with entity relationships defined more heavily. 
- Dashboard pages are styled as per default concrete5 dashboard styles
- Shipping methods are structured differently, with each method able to return multiple 'offers'
- Product blocks output Structured Data (for Google to pick up)
- There is a Duplicate Product feature
- There is a compatible Stripe add-on available
- There are different/more event hooks
- Community Store and the other components in the organisation are MIT licensed.

It's simply not for me to suggest which one to use. One is available on the marketplace and supported by Vivid, this one is a community driven project that lives on github and is intended more as a platform for developers.

If you haven't seen it already I've tried to document the project goals (and other important aspects) in the wiki - https://github.com/concrete5-community-store/community_store/wiki

**Comment by ramonleenders** [comment]
OK, got it. But that means some still stay/stick with VividStore (as developers), right? Wouldn't it make more sense to have as much people as possible on the same ship, instead of taking 2 directions?

eCommerce for 5.7 is a good thing, but even I as a developer got confused what happened here. I'm not following VividStore at all, but just came across a tweet of Ryan and thought I should take a look (since when I looked at VividStore last time, I didn't see much commits/activity). If a project has a lot of inactivity, I lose faith in it. It seems you guys are trying to build something active here, but have the others been informed as well about this one? A lot of time may be going in 2 different projects, where it could be spend into just "this" one.

**Comment by Mesuva** [comment]
I certainly agree that it's important to focus energies, and I didn't take the decision to rework the store lightly.  But as the goal of this project is arguably different from that of Vivid Store, the codebase is quite different and the licenses are different, I don't think there'll be any developmental overlap.
