### ISSUE TITLE
New Order Notification E-mail

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#421]
I was wondering how to change the From: line of the email to show the address of the buyer. So, if I hit reply to an order it will reply to their email, instead of mine.

**Comment by dbuonomo** [comment]
In src/CommunityStore/Order/Order.php, the from e-mail address is pulled from the Community Store config, which is set under Store -> Settings -> Notifications & Receipts:

$fromEmail = Config::get('community_store.emailalerts');

So it looks like you will need to override Order.php to use the customers e-mail, or just the sendNotifications() method, if that is possible.

**Comment by Mesuva** [comment]
I think this is best handled with a Reply-To header, instead of directly changing the From.
This is perhaps a good addition to the store as an option.

**Comment by Mesuva** [comment]
I've added this in via this commit:

https://github.com/concrete5-community-store/community_store/commit/5a8681845aae07094423ebfb06eaeb4aad2b790d
That line should be safe to apply to an older version of the store manually.
