### ISSUE TITLE
StoreOrderSearchIndexAttributes

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#424]
Following upgrade to the pre-release-dev version I get an error on checkout as follows:

An exception occurred while executing 'select count(oID) from CommunityStoreOrderSearchIndexAttributes where oID = 6': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_receiptbookcodb.CommunityStoreOrderSearchIndexAttributes' doesn't exist

The table has not been created and refreshing database entities does not create it.

**Comment by Mesuva** [comment]
I've pushed up what I'm hoping is a fix for this:
https://github.com/concrete5-community-store/community_store/commit/13d4c87e6469488b968a4ea8d09493ddca093e64

Do another upgrade and you should find the table is created.
It doesn't create any additional columns, but I don't believe the search table is actually being used by community store anywhere. It might just be disabled in the future.  (also a GDPR consideration)

**Comment by katalysis** [comment]
Thanks that moves me on, next issue is now a problem with a custom shipping type. Not sure if this is just me or this needs a separate issue re. shipping subclasses.

No identifier/primary key specified for Entity "Concrete\Package\KatalysisMotaprintShipping\Src\CommunityStore\Shipping\Method\Types\MotaprintShippingMethod" sub class of "Concrete\Package\CommunityStore\Src\CommunityStore\Shipping\Method\ShippingMethodTypeMethod". Every Entity must have an identifier/primary key.

**Comment by Mesuva** [comment]
Custom shipping methods do have to be updated for version 2. Unfortunately I don't know of a way to just make it seamless, but it shouldn't take long. I'd uninstall your existing shipping method, and then update it. 

So for your MotaprintShippingMethod class it would be case of:

- Adding a use statement at the top of `use Doctrine\ORM\Mapping as ORM;`
- Changing all your @ references to `@ORM\`, so for example you would change `@Entity` to `@ORM/Entity` and  `@Column` to `@ORM\Column`

You can compare this
https://github.com/concrete5-community-store/community_store_shipping_example/blob/master/src/CommunityStore/Shipping/Method/Types/ExampleShippingMethod.php
With the older v1 version here as an example:
https://github.com/concrete5-community-store/community_store_shipping_example/blob/1.x-compatible/src/CommunityStore/Shipping/Method/Types/ExampleShippingMethod.php

It _might_ just work if you update the file directly and refresh the database entities and clear the cache.

**Comment by katalysis** [comment]
Thanks Ryan, I'd missed that - a little messy to uninstall etc. but good now.

**Comment by Mesuva** [comment]
Apologies for the mess/confusion, this should hopefully be a once-off, now that pretty much all code is the 'V8 way'. We're just doing some clean-up before a release now. Appreciate the testing.
