### ISSUE TITLE
Clicking 'Manage' on a product in the Community Store displays SQL error

### ISSUE THREAD

**Issue by krumholz** [concrete5-community-store/community_store#431]
I just updated Community Store from version 2.0.5 to 2.1.2 and I'm getting the following error:
```
An exception occurred while executing 'SELECT t0.poID AS poID_1, t0.pID AS pID_2,
t0.poName AS poName_3, t0.poType AS poType_4, t0.poDisplayType AS
poDisplayType_5, t0.poHandle AS poHandle_6, t0.poRequired AS poRequired_7,
t0.poIncludeVariations AS poIncludeVariations_8,t0.poSort AS poSort_9,
t0.pID AS pID_10 FROM CommunityStoreProductOptions t0 WHERE t0.pID = ?
ORDER BY t0.poSort ASC' with params [1]: SQLSTATE[42S22]: Column not found:
1054 Unknown column 't0.poHandle' in 'field list'
```
Here's the url - /dashboard/store/products/edit/1

And digging further into that error, I can confirm that I'm not seeing `poHandle` as a field in my `communitystoreproductoptions` table in the database.

**Comment by Mesuva** [comment]
I think may have been to do with caching settings at the time of the update.
A fix should be to go to /index.php/dashboard/system/environment/entities and hit the Refresh Entities button in the lower left. 

You may also need to clear your cache as well.

**Comment by krumholz** [comment]
That was the solution. Thank you for the help!
