### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#434]
We now have Concrete5 v8.5.0 which is PHP 7.3 compatible so I wondered if Community Store works with PHP 7.3 too?

**Comment by Mesuva** [comment]
I personally haven't tried it on PHP7.3, but there's really nothing exotic about the codebase to suggest that it wouldn't just work the same as it does on PHP7.2.

**Comment by madesimplemedia** [comment]
Thanks, I'll try it out soon no doubt.
