### ISSUE TITLE
After testing new tax roules (I think) I found an error

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#438]
I was trying to test the new multiple countries tax rates. When I go to fx. Denmark or United Kingdom, the American states is shown (and used). Denmark has no states/regions and should reflect that.

![billede](https://user-images.githubusercontent.com/1224538/54867609-58a7f400-4d82-11e9-847b-126c24911cb0.png)

Just funny when I choose Denmark it defaults to Alabama state, and no way to choose "no state"! When I buy something, tax is not applied.

![billede](https://user-images.githubusercontent.com/1224538/54867620-8f7e0a00-4d82-11e9-86bf-0e01567c06c4.png)

![billede](https://user-images.githubusercontent.com/1224538/54867654-fd2a3600-4d82-11e9-9e1c-1231d1478d78.png)

![billede](https://user-images.githubusercontent.com/1224538/54867746-1aabcf80-4d84-11e9-9417-1377a1396dcd.png)

![billede](https://user-images.githubusercontent.com/1224538/54867761-4dee5e80-4d84-11e9-9c16-6b355883dcba.png)

I'm not sure if it's me doing something wrong.

**Comment by MichaelMaar** [comment]
The AutoComplete.js might not be related!

**Comment by mnakalay** [comment]
I will check soon.
Can you confirm that you attached your tax rates to a tax class and that you attached that tax class to your products?
This is necessary for taxes to be applied to products during checkout.

**Comment by MichaelMaar** [comment]
When I edit the tax rules for a country I get the following error in the console:

![billede](https://user-images.githubusercontent.com/1224538/54867893-28faeb00-4d86-11e9-920f-019a37c9fcbf.png)

**Comment by MichaelMaar** [comment]
Yes, I can confirm. Using Default Class and added DK and UK tax rules to that class.

**Comment by mnakalay** [comment]
Last question: you downloaded the master right?

**Comment by mnakalay** [comment]
I tested again from the master and everything is working as it's supposed to. Could you give me access to your website's dashboard so I can have a look around?

**Comment by Mesuva** [comment]
I think this one was corrected, let me know if it's still an issue
