### ISSUE TITLE
Updated two copies, one failed

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#439]
I have both a staging site and a live site. I upgraded the staging site with C5 8.50 from 8.4.5, and then I upgraded Community Store from 1.4.2 to 2.1.3, and it worked fine. So I went to perform the same on the live site. However, I upgraded Community Store first and then upgraded C5. I got this error:
Entity 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreProductKey' has to be part of the discriminator map of 'Concrete\Core\Entity\Attribute\Key\Key' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Concrete\Package\CommunityStore\Entity\Attribute\Key\StoreProductKey' an abstract class to avoid this exception from occurring.
And now the live site no longer loads at all... help!

**Comment by Mesuva** [comment]
I saw this error reported the other day (https://github.com/concrete5-community-store/community_store/issues/422) and we weren't really able to pin it down to how or why it happens. Earlier I was able to trigger the error by upgrading things in the order you've said, shop first, then concrete5. 

On another two sites, I did the 8.5.0 upgrade and no issues occurred at all, and they were ones with lots of attributes in place, so my only thought at this point is that it's something to do with the upgrade to 8.5.0 failing at some point.

With the install that did break, I started to try out a few things just to see what would happen.
I added the word abstract to the start of line 11 of:
packages/community_store/src/Concrete/Entity/Attribute/Key/StoreProductKey.php
That then threw an expected error. I then put something else in, but it was a true syntax error and that throw a normal kind of PHP error. But, when I reverted it back to before and refreshed the site everything then worked fine and the discriminator map error was gone.. Maybe something in throwing the latter error caused some sort of re-assessment of the class.

It's really strange, but maybe you could try that to get things up and running again.

**Comment by teknoziz** [comment]
I tried what you suggested, no change. Then I tried moving the generated_overrides and doctrines folders out and the site came up – not correctly, but it did work. I am troubleshooting now to see if I can locate the file(s) causing the problem.

**Comment by teknoziz** [comment]
I replaced the generated_overrides one by one and now I see this:
Property Concrete\Core\Entity\File\Image\Thumbnail\Type\Type::$ftKeepAnimations does not exist

**Comment by Mesuva** [comment]
I think you are going to hit issues if you remove the doctrine folder and you have Doctrine Development Mode set to off, i.e the setting on this page: /index.php/dashboard/system/environment/entities/view

**Comment by Mesuva** [comment]
I also don't think the generated_overrides folder is going to be related to this issue, as that's all to do with config settings, whereas this is more of Doctrine related issue.

**Comment by teknoziz** [comment]
Ok... now it's weird, I never returned the doctrines folder and copied the config files and generated_overrides over from the other site – now it's working...

**Comment by Mesuva** [comment]
Very strange!

Really not what else to suggest here, apart from to enjoy the rest of your Sunday!

**Comment by teknoziz** [comment]
Spoke too soon, the site is up, but when I try to add a product, I just get the spinner. I'll play around with it some more and let you know. I am off to church. Have a good one.

**Comment by teknoziz** [comment]
Update... I tried both the staging site and live site and the sites both work, but I am unable to add a product to the cart in either, just get the wheel of infinity.

**Comment by Mesuva** [comment]
When you add something to the cart you'll need to check the developer console and the request that fails - it hopefully will show the error that is being thrown:

<img width="828" alt="Screen Shot 2019-03-24 at 6 48 11 pm" src="https://user-images.githubusercontent.com/1079600/54884153-6b472980-4e65-11e9-942e-74cd8f3e1f20.png">

(my example being a successful add to cart)

**Comment by Mesuva** [comment]
Oh, do you have custom product block templates in play?
If you upgraded from 1.4.2, that is going to be _before_ CSRF tokens were introduced, and you may need to add them in. See the notes about that on this release:
https://github.com/concrete5-community-store/community_store/releases/tag/v1.4.7

**Comment by teknoziz** [comment]
Yep, I did. I had to update the template with the new info plus my changes, and have most of it worked out. Thanks for your help.
Sincerely,

 



David Zizza, TeKno Ziz
(617) 543-3971 cell     (978) 663-0951 home office
david@teknoziz.com <mailto:david@teknoziz.com> teknoziz.com <https://teknoziz.com/>
