### ISSUE TITLE
Product list eror

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#441]
I have started to see an error on a product list block: 

Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/home/cncdesignco/public_html/application/config/doctrine/proxies/__CG__ConcretePackageCommunityStoreSrcCommunityStoreGroupGroup.php' (include_path='/home/cncdesignco/public_html/concrete/vendor:.:/opt/cpanel/ea-php70/root/usr/share/pear')

Client says they haven't changed anything, anyone have any ideas what I should look for? It's working on the development site but not the live site, not sure if it might be a server issue rather than a C5/store issue?

thanks

**Comment by Mesuva** [comment]
I think this should be able to be resolved via a Refresh Entities, via /index.php/dashboard/system/environment/entities - the red the Refresh Entities to the lower left

**Comment by pvernaglia** [comment]
Wow, that did it! Thanks so much, I have never even looked at that dashboard page before, that really saved a lot of hair pulling

**Comment by Mesuva** [comment]
It's a bit of a strange one why that error happens out of the blue like that.  I've seen it happen for other packages too, not just community store.
