### ISSUE TITLE
attributes groups not sorting

### ISSUE THREAD

**Issue by xb385** [concrete5-community-store/community_store#442]
Hi,

When creating product attributes its possible to place them in sets and sorting them but when creating products, under the tab attributes it only listing attributes in order of creation. is it possible to show them by set and with the proper sorting?

**Comment by SpatialAnomaly** [comment]
I am also looking for this. It would be great it if it kept the sets, set name and the order of the attributes in there.

**Comment by ebell14** [comment]
just bumped into this last week and my custom attributes got all mixed up

**Comment by Mesuva** [comment]
I've pushed up this commit - https://github.com/concrete5-community-store/community_store/commit/6efcfd693dc0507d5b08243e642d86e5ef49503d

It outputs them in the sets, in they order they are managed

**Comment by Mesuva** [comment]
(should be safe to hotfix that code into an existing install instead of upgrading the entire package)
