### ISSUE TITLE
Unable to add CC details for square

### ISSUE THREAD

**Issue by GlennMallon** [concrete5-community-store/community_store#446]
I have installed concrete5, community store and community store square integration. I have also installed the Pixel2 theme if that matters.

When i got to buy this item, it see a buy button. http://www.widp.org/index.php/buy-widp

I click this button, and it takes me to the checkout.

I fill in address details correctly, and click next.

I am scrolled to credit card details (which are now populated on the same page) with no boxes to input the details. I submit anyway (because I thought this might be how it worked for sandbox mode...but i have now tried this is both modes, same result) and get an error that data is missing. When I check the log, I see:

JSON from response body: {"errors":[{"category":"INVALID_REQUEST_ERROR","code":"MISSING_REQUIRED_PARAMETER","detail":"Missing required parameter.","field":"card_nonce"}]}

I have re-installed the store, theme and square integration just in case but am getting the same.

**Comment by Mesuva** [comment]
I'm not very familiar with this add-on, so I might be of limited help.
When it comes to the checkout screen, do you have any javascript errors on the page?

**Comment by GlennMallon** [comment]
That was it, thank you.  The cert I had wasn't trusted.  I generated a new signed cert and now the boxes show!
