### ISSUE TITLE
Upgraded store, getting 404 when going to translate product

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#447]
Hi

I upgraded an old version of CS, but now when I click the Manage button next to a product and choose Translate, it goes to a 404 page.
This is the final URL: /index.php/dashboard/store/multilingual/products/translate/4

What could the issue be?

Thanks
Dave

**Comment by Mesuva** [comment]
What about this path, does it pull up a page?   
/index.php/dashboard/store/multilingual/products

As part of the upgrade it should be checking for these single pages in the dashboard and adding them if they don't exist. You've been able to successfully trigger the package upgrade?

**Comment by madesimplemedia** [comment]
That causes a 404 too.

I had a couple of errors, but got round them.  It's saying it has successfully upgraded to v.2.1.4

**Comment by Mesuva** [comment]
What you could try is manually adjusting the version in the Packages table for Community Store to something a little lower than the version and triggering the upgrade again. The upgrade process is repeatable, and maybe it never fully completed previously.

**Comment by madesimplemedia** [comment]
Thanks, I tried that and then when I clicked to update I get an error:

An exception occurred while executing 'DROP INDEX IDX_48450E69B6561A7E ON CommunityStoreOrderAttributeValues':

SQLSTATE[HY000]: General error: 1553 Cannot drop index 'IDX_48450E69B6561A7E': needed in a foreign key constraint

**Comment by Mesuva** [comment]
Ahh, I heard about that issue earlier today and we couldn't work out the reason. 
Working through it again now.

**Comment by madesimplemedia** [comment]
Thanks mate, seems to be an empty table.

**Comment by Mesuva** [comment]
I haven't been able to find a programatic cause for this, but I've found that you can delete the indexes manually from the CommunityStoreOrderAttributeValues table, and they'll be recreated during an upgrade (or a 'Refresh Entities' through the dashboard)

I'm thinking that might solve the problem here, as there may be an index on that table that is no longer used, and you have to manually delete it.

**Comment by madesimplemedia** [comment]
There is literally no rows in that table.

**Comment by Mesuva** [comment]
The error message isn't complaining about data, it's complaining that there is an index on the table that is used by a foreign key, so it can't be deleted. It's table structural thing.

**Comment by madesimplemedia** [comment]
Gotcha, but it won't let me delete the last index
![image](https://user-images.githubusercontent.com/10834004/56676567-797fa400-66b6-11e9-9fa3-5ec25f588349.png)

**Comment by Mesuva** [comment]
According to that screenshot you don't have any index on the table, only the primary key (which you wouldn't delete).

So try an upgrade now.

**Comment by madesimplemedia** [comment]
Yeah I dropped the other indexes.

Just tried again, no luck:

An exception occurred while executing 'ALTER TABLE CommunityStoreOrderAttributeValues ADD CONSTRAINT FK_48450E69ECC024CA FOREIGN KEY (oID) REFERENCES CommunityStoreOrders (oID)':

SQLSTATE[HY000]: General error: 1005 Can't create table `woolondon_dev`.`#sql-965b_26d0f8` (errno: 121 "Duplicate key on write or update")

**Comment by Mesuva** [comment]
That's weird, it's trying to create a foreign key again on the table where it already exists.
You could also try removing all foreign keys on CommunityStoreOrderAttributeValues (after removing the two indexes, I'd expect only one foreign key to be present, for oID)

**Comment by madesimplemedia** [comment]
Still didn't like it, hmmm

**Comment by Mesuva** [comment]
What about if you hit Refresh Entities on /index.php/dashboard/system/environment/entities, _then_ try the upgrade?

**Comment by madesimplemedia** [comment]
Just tried that, still get the same error

**Comment by Mesuva** [comment]
I can't replicate this locally, no matter what I do with indexes or foreign keys, they simply get recreated after an update.

If the table is empty, you could try completely deleting it and seeing if it resolves when it creates it fresh..

**Comment by madesimplemedia** [comment]
Didn't work, I think I'll go for a fresh install.

**Comment by mnakalay** [comment]
@madesimplemedia when deleting stuff in phpmyadmin and getting complaints about indexes and linked tables you actually have an option to ignore those warnings before triggering the action.

**Comment by madesimplemedia** [comment]
@mnakalay ok thanks, although I seem to be able to delete things ok, but it still throws the error when trying to upgrade the package in C5.
Luckily this is a new site so I think I can just delete CS and install the latest version from scratch.
