### ISSUE TITLE
Fix for: CommunityStore/Tax/TaxRate.php:295 A non-numeric value encountered (2)

### ISSUE THREAD

**Issue by losttheplot** [concrete5-community-store/community_store#450]
If a product is configured as not being shippable and you then try to delete the item from the basket modal, the following error is encountered: 

Exception Occurred [snip] /packages/community_store/src/CommunityStore/Tax/TaxRate.php:295 A non-numeric value encountered (2)

**Fix:** /community_store/src/CommunityStore/Tax/TaxRate.php wrap the getFloat() call on line 287 in a floatval() as follows:
```
$shippingTotal = floatval(StorePrice::getFloat(StoreCalculator::getShippingTotal()));
```

**Comment by Mesuva** [comment]
Thank you for this one, I've tracked this down and pushed a fix for this (plus a bit of cleanup):
https://github.com/concrete5-community-store/community_store/commit/dc1628adb1414e938573a02bec52b1a14060938a
