### ISSUE TITLE
Fix for: quantity (1) not shown in checkout cart if 'offer quantity selection' set to 'No'

### ISSUE THREAD

**Issue by losttheplot** [concrete5-community-store/community_store#452]
If a product's 'offer quantity selection' is set to 'No', the item does not show '1' in the checkout cart quantity column as per the rest of the module's interfaces.

**Fix:** /community_store/elements/cart_list.php change line 133 to:
```
} else { echo "1"; } ?>
```

**Comment by Mesuva** [comment]
That one is intentional

**Comment by losttheplot** [comment]
It looks wrong when the cart column simply shows the item type e.g. "widgets" instead of "1 widgets" (grammar issues aside). This is also inconsistent with the other cart instances.

I'm very grateful for all the work you are doing on this project, by the way :)

**Comment by losttheplot** [comment]
If you don't show a quantity of one, and there is no quantity label, I think I'm right in saying that the quantity cell will be blank. This then leads to ambiguity i.e. have I ordered one item, two or none? So my opinion, FWIW, is that you made the right call elsewhere (adding '1') but the wrong call in the checkout cart.

**Comment by Mesuva** [comment]
I believe the option to turn off the quantity was more along the lines of handling things like digital access to things, like memberships. Things that _aren't_ items as such. You might have a product '12 months access to digital resource', and in that case you don't really want a quantity displayed. 

Something like a 'widget' is more of an 'object' so a quantity makes sense to display in that context.
If you have a physical object, but don't want to customers to buy more than one, you'd use the 'Maximum Quantity (as single cart item)' field.

(that all being said, that's the context I had in mind, I'm sure there are other ways to look at this!)

**Comment by Mesuva** [comment]
I agree here that the default should be that it always shows one - if someone doesn't want it there they can override the template. I've pushed up a change for this, plus a few other styling tweaks.
