### ISSUE TITLE
Duplicating a product

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#460]
Hi, just tried duplicating a product with a new install of concrete 8.5.1 and Community Store 2.1.6.1, I get a database error:

An exception occurred while executing 'UPDATE atSelect SET avID = ? WHERE avID = ?' with params [452, "430"]: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`c5sites_fish`.`atSelectOptionsSelected`, CONSTRAINT `FK_40C97EC3A2A82A5D` FOREIGN KEY (`avID`) REFERENCES `atSelect` (`avID`))

The item is added to the store, but when I click on Manage I get another error:

Call to a member function getVariationPackageData() on null 

from /packages/community_store/single_pages/dashboard/store/products.php Line 1344

<?= $form->textarea('pvPackageData[' . $varid . ']', $variation->getVariationPackageData(), ['rows' => 4, 'placeholder' => t('%s LENGTHxWIDTHxHEIGHT', strtoupper(Config::get('community_store.weightUnit')))]) ?>

**Comment by Mesuva** [comment]
I'm not sure of the cause of the first issue, that seems a bit more core related to me.

But for the second one, try changing the line as per this fix here: https://github.com/concrete5-community-store/community_store/commit/ebf3079bf0900f7c97a1b7749725dbce43a55732

**Comment by pvernaglia** [comment]
That fixed the second error

**Comment by pvernaglia** [comment]
Attribute values do not get copied over when I make a duplicate product.

**Comment by Mesuva** [comment]
I've been able to replicate the same initial bug and I've pushed up a potential fix - it worked for me at least with some select attributes and plain text.

https://github.com/concrete5-community-store/community_store/commit/ea7a8aa585b841e75b57de75581bf4a3d90e98fc

Give that fix a try and let me know how you go

**Comment by pvernaglia** [comment]
That's working now, thanks for looking into it so quickly, appreciate it!

**Comment by Mesuva** [comment]
Great, good one to get fixed!
