### ISSUE TITLE
Issues with Search Index jobs

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#462]
Hi

I upgraded a client from C5 8.4 to 8.5.1 and now have an error running the Search Engine jobs under Automated Jobs in the Dashboard:

When I run either job I get:

Call to a member function getCollectionID() on null

/home/[sitename]/dev.[sitename].us/packages/community_store/blocks/community_product/controller.php(138): Error->null

Thanks
Dave

**Comment by Mesuva** [comment]
Here's what I hope is a fix for this, at least to be able to complete the search engine job correctly:
https://github.com/concrete5-community-store/community_store/commit/c27fe26504ed182914b7eff46c54e8227c21b03c

What I can't work out is why it would be looking at a block and then not able to found the page it's one. I might be misunderstanding that process, but this should at least prevent errors.

**Comment by madesimplemedia** [comment]
I nearly did that but thought, oh no it'll be more complicated than that! :D
Thanks!

I can confirm the jobs both finish and the products are indexed.
