### ISSUE TITLE
cstore:reset console command fails to delete orders

### ISSUE THREAD

**Issue by markbennett1973** [concrete5-community-store/community_store#463]
Running the console command `cstore:reset` gives an error if you have any orders: 

```
 Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sg_website`.`CommunityStoreOrderAttributeValues  
  `, CONSTRAINT `FK_48450E69ECC024CA` FOREIGN KEY (`oID`) REFERENCES `CommunityStoreOrders` (`oID`))
```

Looks like the command class (Concrete\Package\CommunityStore\Src\CommunityStore\Console\Command\ResetCommand) is calling `$order->delete()` when it should be using `$order->remove()` (line 72 in the current version of https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Console/Command/ResetCommand.php)

**Comment by Mesuva** [comment]
That makes sense to me - I've pushed up the change for this.

**Comment by markbennett1973** [comment]
Nice - thanks!
