### ISSUE TITLE
Adding List Block Crashes C5

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#464]
Using new install of C5 8.5.1 and 2.1.7 of Community Store. Trying to add a list block on a category page I get the dialog box and fill it out and when I save it shows nothing on the page and then when I refresh it crashes C5. The other blocks seem to work ok. Error received is: 

.../Lincoln Labs2/packages/community_store/blocks/community_product_list/view.php96

Sample page: http://lincolnlabs2.teknoziz.com/products/hplc-solvents (error removed)

**Comment by Mesuva** [comment]
Any chance you could post or screenshot the full error message?

**Comment by teknoziz** [comment]
Here you go.
<img width="1573" alt="Screen Shot 2019-06-20 at 10 29 35 AM" src="https://user-images.githubusercontent.com/7119442/59857516-196c4d80-9347-11e9-90b0-9c8794ded769.png">
<img width="1573" alt="Screen Shot 2019-06-20 at 10 29 52 AM" src="https://user-images.githubusercontent.com/7119442/59857517-196c4d80-9347-11e9-8eb9-89bf35f1f175.png">
<img width="1573" alt="Screen Shot 2019-06-20 at 10 34 27 AM" src="https://user-images.githubusercontent.com/7119442/59857518-196c4d80-9347-11e9-9ab4-d69dcbb50d70.png">

**Comment by Mesuva** [comment]
That helps lots.  Try this adjustment and let me know if that fixes it for you:
https://github.com/concrete5-community-store/community_store/commit/e4fe63254a4c49103fa5d3372092b460bccf6b1e

**Comment by teknoziz** [comment]
Yep, that works now, thanks! A UI thing I noticed when it began working. When I selected (by mistake) "Customer can enter price", even though I had "Display Price" checked off, it still appeared on the list. Maybe that option should be greyed out when you check "Customer can enter price". Or vice versa. Or maybe AND vice versa...

**Comment by Mesuva** [comment]
It could be because I need another coffee, but I'm not quite following your description of the 'Allow customer to enter price' UI issue you're describing. Would you be able to expand this a little, maybe with a screenshot?

**Comment by teknoziz** [comment]
No, maybe I am the one who needs the coffee, I have _no idea_ what I was referring to. I went back to look it over and couldn't find what I was talking about... lol. Maybe I was looking at something else.
