### ISSUE TITLE
JS Error on checkout

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#466]
Hi

I am getting a js error when entering billing details and clicking next during checkout:

Uncaught SyntaxError: Unexpected token < in JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.success (communityStore.js?v=2.1.6.1&ccm_nocache=f912c4019b52a41eda152905caa30d5f197a5cb6:629)
    at i (jquery.js?ccm_nocache=ca17add95b11d1baf3d74fcd3fa4637fb02c14ba:2)
    at Object.fireWith [as resolveWith] (jquery.js?ccm_nocache=ca17add95b11d1baf3d74fcd3fa4637fb02c14ba:2)
    at y (jquery.js?ccm_nocache=ca17add95b11d1baf3d74fcd3fa4637fb02c14ba:4)
    at XMLHttpRequest.c (jquery.js?ccm_nocache=ca17add95b11d1baf3d74fcd3fa4637fb02c14ba:4)

It looks like it's trying to read html as json, please see attached.

![independant-js-checkout-error](https://user-images.githubusercontent.com/10834004/60003000-b25dda00-9661-11e9-9b31-af66c37a7ea9.jpg)

**Comment by Mesuva** [comment]
Might need a bit more detail here to work out the problem.
When you trigger that error, what can you see being returned in the web request?

This kind of Javascript error is generally because JSON wasn't returned from the server but some sort of error page/response.

**Comment by madesimplemedia** [comment]
Wow you're quick, I just updated the post with more info, need anything else?

**Comment by Mesuva** [comment]
Take a look in the network tab and see if you can spot the request that isn't working right. It _might_ be in red.

**Comment by madesimplemedia** [comment]
It's not red, but this it the request that appeared when I recreated the issue
![independant-js-2](https://user-images.githubusercontent.com/10834004/60003260-39ab4d80-9662-11e9-98e1-4bc99ec38213.jpg)

**Comment by madesimplemedia** [comment]
Request url https://dev.independantjewellery.com/checkout/updater

**Comment by Mesuva** [comment]
Yep, for that request, what do you see in the 'Response' tab?

**Comment by madesimplemedia** [comment]
Attached
![js-response](https://user-images.githubusercontent.com/10834004/60004262-2b5e3100-9664-11e9-846d-974e828149bb.jpg)

**Comment by Mesuva** [comment]
And what about the Preview tab?

**Comment by madesimplemedia** [comment]
Attached, looks like it's renderin
![independant-js-previewtab](https://user-images.githubusercontent.com/10834004/60005043-ac69f800-9665-11e9-8c51-091750adda44.jpg)
g the html.

**Comment by Mesuva** [comment]
Is this a store you've updated from an older version?
I'm wondering if you are missing the tokens from the checkout page (if you've overridden it)

**Comment by madesimplemedia** [comment]
I ended up uninstalling the old version and installing the new one, so there could be missing data.  How would I check and fix that?

**Comment by Mesuva** [comment]
If you've overridden your checkout single page template, it's these kinds of token lines I'd be checking that you have in place:
https://github.com/concrete5-community-store/community_store/blob/master/single_pages/checkout.php#L61

**Comment by madesimplemedia** [comment]
Ah yes it is that override, I have removed it and now it works thanks!

**Comment by Mesuva** [comment]
Great, glad to hear it wasn't something more troublesome
