### ISSUE TITLE
Product Options - New Option "Static Text"

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#467]
I would like to have the option to add a "Static Text" option in product options like this one:

![billede](https://user-images.githubusercontent.com/1224538/60184871-27c7d700-9829-11e9-9af9-a2daa3c88d7e.png)

This should simply render static text to the position inserted in the product options. It should also render html code inserted in to the "Static Text" box.

**Comment by Mesuva** [comment]
This is in the master now
