### ISSUE TITLE
Valid fix? - Exception Occurred: /[sitename]/packages/community_store/single_pages/dashboard/store/orders.php:627 Call to a member function getHandle() on null (0)

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#468]
Hi

I was getting the error when going to View Orders:

/[sitename]/packages/community_store/single_pages/dashboard/store/orders.php:627 Call to a member function getHandle() on null (0)

The line is:
```
<li <?= (!$status ? 'class="active"' : ''); ?>><a href="<?= \URL::to('/dashboard/store/orders/all/' . $pm->getHandle() . '/' . $paymentStatus.$keywordsparam)?>"><?= t('All Fulfilment Statuses')?></a></li>
```

Which I changed to:
```
<?php if($pm) { ?>
<li <?= (!$status ? 'class="active"' : ''); ?>><a href="<?= \URL::to('/dashboard/store/orders/all/' . $pm->getHandle() . '/' . $paymentStatus.$keywordsparam)?>"><?= t('All Fulfilment Statuses')?></a></li>
<?php } ?>
```

Working now, you might want to add this if you agree it's ok for the next release.

**Comment by Mesuva** [comment]
I think the fix for this is actually this:
https://github.com/concrete5-community-store/community_store/commit/f7eed2cac390f99c4258cd1d8f09735e33c70b09

Could you try that and confirm with me that it solves the issue for you?

**Comment by madesimplemedia** [comment]
Yes that works.

**Comment by Mesuva** [comment]
Excellent, I'll be doing a release someone soon, maybe this weekend.

**Comment by madesimplemedia** [comment]
ok great thanks
