### ISSUE TITLE
Class 'Concrete\Package\CommunityStore\Src\Attribute\Key\StoreOrderKey' not found

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#469]
Error occurs when click View Order next to one of the orders on the order page.

Error:
/home/[sitename]/dev.[sitename].com/application/controllers/single_page/dashboard/store/orders.php231

![image](https://user-images.githubusercontent.com/10834004/60350103-c8013580-99ba-11e9-8667-5ce1e5ca59e9.png)

**Comment by Mesuva** [comment]
If it's a file in the /application folder, that's on that has been overridden.
That also looks like the namespace of the StoreOrderKey class in version 1.x of community store - are you running that, or version 2.x?
