### ISSUE TITLE
Product options not taking into account stock levels

### ISSUE THREAD

**Issue by agentsquidflaps** [concrete5-community-store/community_store#470]
So let's say I have a product with a stock level of 1 and this product has a checkbox option of 'Gift wrapping'. The store currently allows you to add the product twice to your basket, one with 'Gift wrapping: yes' and one with 'Gift wrapping: no'

**Comment by Mesuva** [comment]
I've had a look at this one - it's unfortunately a tricky one to solve with the current way the cart is managed.

Some things may need refactoring - will try to look at this sooner rather than later.

**Comment by agentsquidflaps** [comment]
Yes, it is a tricky one! I wasn't sure on what the best way to handle it would be for every scenario, as I'm not sure if there's a one size, fits all situation. So I'd thought I'd leave with you and hence why there's no pull request for this one ;)

**Comment by Mesuva** [comment]
I've addressed this in a recent commit to master - it needs lots of testing, which is underway
