### ISSUE TITLE
Display Current Category in Product List

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store#473]
I would like to display the current Category being used to filter the Product List block. I'm not sure how to go about that. Any help would be appreciated.

Side Note: This may be a good feature to have, maybe as a checkbox while adding a Product List Block. Or in a more manual but what I think may fit scenarios, the ability to give the Product List Block a name that would displayed above the Product List Block.

**Comment by Mesuva** [comment]
As the product list block is just another block on the page, would it make sense to just manually add a content block above it to display a category title?

If you're using the page list block on a custom page type for categories, wouldn't the category filter be just the current page name?  

Maybe describe your scenario a bit further so I can understand why you'd want to do this automatically.

**Comment by drumrby** [comment]
I'm using the Community Store and the Product List block to build a digital menu. Each page has several Product List Blocks on it, and each block displays one category. Which gives me the modularity I was looking for, because the page will need to be somewhat animated to help attract attention and also to prevent burn in.

Using the content block is my backup option.

For this project in general, it would be nice to be able to have one block that contained all of the necessary information, so it would be easy to move around, even for the client.

I was thinking the simplest way to achieve that was to pass the $targetpage variable from the controller to the view, but I have not been about to figure out how to make that happen. This would at least allow me to use a Custom Template that would display that variable on the Product List Blocks.
