### ISSUE TITLE
Display Product Date Added

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store#474]
I am trying to retrieve and display the Date Added for a Product. I haven’t been able to figure out a method that already exists to do that. How would I go about that?

**Comment by Mesuva** [comment]
In either of the product list or product block templates I'm able do something like this:
` echo $product->getDateAdded()->format('m/d/Y');`
Main thing to note is that getDateAdded() returns a DateTime, so you have to call format on it to turn it into a formatted date string.

**Comment by drumrby** [comment]
Awesome, thank you! I could've sworn I just guessed and tried that same method, but it didn't work. But no matter, that works just like I was wanting. Thanks again!
