### ISSUE TITLE
Display Options - Options

### ISSUE THREAD

**Issue by tbrown-hub** [concrete5-community-store/community_store#478]
It appears that the options are tied to all aspects for the "Display Options" block. I tried to make a two column product page with different items to display in the respective areas of the page. As you can see the test displays the options with the following items checked "Show Product Name, Show Price and Short Description". I also added a product block with only the "Show Product Image" and it also displays the options that I created. Could options be it's own check box. Thank you for continued work on this product.

![Screen Shot 2019-07-11 at 2 48 35 PM](https://user-images.githubusercontent.com/45441143/61087656-1c5cda00-a3eb-11e9-96b3-3862f656d4d1.png)
![Screen Shot 2019-07-11 at 2 36 51 PM](https://user-images.githubusercontent.com/45441143/61087657-1c5cda00-a3eb-11e9-9405-763be9bc0473.png)
![Screen Shot 2019-07-11 at 2 34 48 PM](https://user-images.githubusercontent.com/45441143/61087658-1cf57080-a3eb-11e9-8584-7013ccce0b63.png)

**Comment by Mesuva** [comment]
I don't think it's a good idea to allow the options to be selectively turned on and off, as much of the time the options are required to add the product to the cart. So I'm closing this one for now.
