### ISSUE TITLE
StoreProduct needs getFormattedTax()

### ISSUE THREAD

**Issue by krebbi** [concrete5-community-store/community_store#48]
would be great to have something like that as here in germany we have to show the taxes on a product page in the first place.

**Comment by Mesuva** [comment]
We could look to add something like this in, it really would be shorthand for doing something like:

$taxRate = new TaxRate();
$tax = $calculateProduct($product, 1);
echo StorePrice::format($tax);

**Comment by Mesuva** [comment]
I might close this one - there's other discussion at the moment about enhancing the tax options available anyway.
