### ISSUE TITLE
Error on Product Page Front and Back End

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#480]
Here it is. In version 2.1.7 and 2.1.8.

An exception occurred while executing 'SELECT t0.pID AS pID_1, t0.cID AS cID_2, t0.pName AS pName_3, t0.pSKU AS pSKU_4, t0.pBarcode AS pBarcode_5, t0.pDesc AS pDesc_6, t0.pDetail AS pDetail_7, t0.pPrice AS pPrice_8, t0.pWholesalePrice AS pWholesalePrice_9, t0.pSalePrice AS pSalePrice_10, t0.pCustomerPrice AS pCustomerPrice_11, t0.pPriceMaximum AS pPriceMaximum_12, t0.pPriceMinimum AS pPriceMinimum_13, t0.pPriceSuggestions AS pPriceSuggestions_14, t0.pQuantityPrice AS pQuantityPrice_15, t0.pFeatured AS pFeatured_16, t0.pQty AS pQty_17, t0.pQtyUnlim AS pQtyUnlim_18, t0.pBackOrder AS pBackOrder_19, t0.pNoQty AS pNoQty_20, t0.pAllowDecimalQty AS pAllowDecimalQty_21, t0.pQtySteps AS pQtySteps_22, t0.pQtyLabel AS pQtyLabel_23, t0.pMaxQty AS pMaxQty_24, t0.pTaxClass AS pTaxClass_25, t0.pTaxable AS pTaxable_26, t0.pfID AS pfID_27, t0.pActive AS pActive_28, t0.pDateAdded AS pDateAdded_29, t0.pShippable AS pShippable_30, t0.pWidth AS pWidth_31, t0.pHeight AS pHeight_32, t0.pStackedHeight AS pStackedHeight_33, t0.pLength AS pLength_34, t0.pWeight AS pWeight_35, t0.pNumberItems AS pNumberItems_36, t0.pSeperateShip AS pSeperateShip_37, t0.pPackageData AS pPackageData_38, t0.pCreateUserAccount AS pCreateUserAccount_39, t0.pAutoCheckout AS pAutoCheckout_40, t0.pExclusive AS pExclusive_41, t0.pVariations AS pVariations_42, t0.pNotificationEmails AS pNotificationEmails_43, t0.pManufacturer AS pManufacturer_44 FROM CommunityStoreProducts t0 WHERE t0.pID = ?' with params ["52"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.pSalePrice' in 'field list'

**Comment by Mesuva** [comment]
Just looks like you're missing the pSalePrice field from the CommunityStoreProducts table.
You could try hitting the red Refresh Entities button on /index.php/dashboard/system/environment/entities, which should then create that field if it's missing

**Comment by teknoziz** [comment]
You, sir, are a rock star. Thanks.
