### ISSUE TITLE
If I set stock to 0 it disappears from product list

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#482]
Hi

If I set a product stock to 0 it disappears completely from the stock list.
I want it to remain in the list but obviously say out of stock when the product is viewed.
Is there a code change I can do to achieve this?

Thanks

**Comment by Mesuva** [comment]
Product list blocks have a 'Include Out of Stock Products' checkbox option, do you have that checked?

**Comment by madesimplemedia** [comment]
Ah!  Got it, no issue there then, thanks
