### ISSUE TITLE
Order Shipped!  Email

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#483]
Hi

More of a question than an issue, does Community Store send an Order Shipped email to the customer when the status is changed to Shipped?

Thanks
Dave

**Comment by Mesuva** [comment]
Not automatically, no.
It was a conscious decision not to include that functionality, as many shipping companies send their own notifications to customers anyway, and it can be handled in quite a few ways (i.e. including a tracking code or not, showing delivery dates, that kind of thing)

There is an event hook that could be used to trigger something.

**Comment by madesimplemedia** [comment]
Thanks for the info, much appreciated.
