### ISSUE TITLE
AbstractProxyFactory Error

### ISSUE THREAD

**Issue by teknoziz** [concrete5-community-store/community_store#489]
Whoops\Exception\ErrorException 
…/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209

https://lincolnmfg-usa.com/

Thoughts?

**Comment by teknoziz** [comment]
Whoops\Exception\ErrorException thrown with message "Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/home/lincolnfineingredients/lincolnmfg-usa.com/application/config/doctrine/proxies/__CG__ConcreteCoreEntitySiteType.php' (include_path='/home/lincolnfineingredients/lincolnmfg-usa.com/updates/concrete5-8.5.1_remote-updater/concrete/vendor:.:')"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home/lincolnfineingredients/lincolnmfg-usa.com/updates/concrete5-8.5.1_remote-updater/concrete/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209

**Comment by Mesuva** [comment]
Doesn't actually look to be community store related. Try the 'refresh entities' button trick at /index.php/dashboard/system/environment/entities

**Comment by teknoziz** [comment]
Gah! Can't get there, it throws the exception...

**Comment by Mesuva** [comment]
Check to see if that __CG__ConcreteCoreEntitySiteType.php file actually exists in the path it's complaining about. If it does exist, check the permissions. If it doesn't, I'm pretty sure you can copy in a copy of that file from any other concrete5 install of the same version.

**Comment by teknoziz** [comment]
The file existed, the permissions are 644, and I synced the files from my local install to the live site, copied about 34 files. Still the same error. Checked the htaccess file too. Now it says __CG__ConcreteCoreEntitySiteType.php is missing, but it's there, too.

**Comment by Mesuva** [comment]
Maybe try changing your PHP version temporarily, or the CLI command mentioned in this thread: https://www.concrete5.org/community/forums/customizing_c5/c5.8.1.0-an-unexpected-error-occurred

**Comment by teknoziz** [comment]
Ha! Don't laugh, I was editing the wrong copy all the time. I added the missing files and everything worked! Thanks for your patience.
