### ISSUE TITLE
PHP 7.0 to 7.2 Upgrade, will not complete Check out

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#490]
PHP updated on my new server, it went from 7.0 which worked only when PHP-FPM was added to the 7.0, but the upgrade used 7.2 which works on everything but the check out process.

Go ahead and try:
https://www.mytinytown.com/products/tilt-switch-1-amp-valox-case-06-inch-leads
During check out it hangs when trying to add shipping details.

**Comment by Mesuva** [comment]
I'm actually hitting an error before the checkout:

<img width="1514" alt="Screen Shot 2019-09-17 at 9 08 22 pm" src="https://user-images.githubusercontent.com/1079600/65075697-57513000-d98f-11e9-888f-6b15bd6cd855.png">

In my screenshot i've highlighted where it's going wrong, where it's different to what is in the default install - I think you need to replace that line just with:
`<a class="btn btn-default" href="<?= Url::to('/login') ?>"><?= t("Sign In") ?></a>`

Once that is fixed, I can take a look at the shipping details section

**Comment by mdius** [comment]
Wow, I am usually logged in and never seen that error, wonder how long that's been happening. It used to work, I liked it cause it would help redirect you back to the page you were at once you logged in. The community_utility_links does it and works. I believe Nour helped me with that a while back.
https://www.concrete5.org/community/forums/usage/login-redirect/#923897
That is the page with the redirect info.

Anyway the copy of the checkout.php is pretty much the exact copy of the php that came out of release 1.4.7. That error is gone, but it still hangs when trying to load the shipping info.

You might have login info still for this site too, use it if you have/need it.

Thank you.

**Comment by Mesuva** [comment]
The issue with checkout is the EasyPost add-on:
<img width="1526" alt="Screen Shot 2019-09-18 at 5 38 30 pm" src="https://user-images.githubusercontent.com/1079600/65168112-c2f0d700-da3b-11e9-977c-b5dbc706ad29.png">

This error is something that didn't trigger in PHP7.1, but in 7.2 and above it's a strict error.
So for the moment, you can simply wind your PHP version back to 7.1.

But going forward, this would be a case of swapping out the easy post package with an updated one. I've just updated the package and pushed a release with up-to-date libraries. I simply wasn't aware of the need to update the library because of PHP issues.

So perhaps trying swapping to this release: https://github.com/concrete5-community-store/community_store_easypost/releases/tag/v2.1

**Comment by mdius** [comment]
OK so the EasyPost 2.1 seemed to clear it up. This is on the test site, the main mdius.com site is using php7.0 because it was good. Is there a big noticeable difference between 7.0 and 7.2?
If 7.0 is working good is it worth upgrading?

**Comment by Mesuva** [comment]
It's probably not likely that you'll spot performance improvements between the 7.x versions, compared to the jump in performance between PHP5 and 7.  But each 7.x version has been faster, with 7.3 being 30% faster than 7.0.

Maybe more importantly though, PHP7.0 is actually at end of life, and 7.1 is only security fixes only, while 7.2 and 7.3 are the only versions actively supported: https://www.php.net/supported-versions.php. 

I've been running concrete5 with community store on all PHP 7 versions without issues and tend to pick 7.2 or 7.3 if I can for new installs.

**Comment by mdius** [comment]
Ahhh ok.
So, worth it, but not to big a deal if you cannot.
But saying that 7.3 is 30% faster than 7.0 I tried 7.3 on my site and get some real concrete5 errors.
Going to post this on the Concrete5 forum and see what they say.
www.mytinytown.com take a look if you want.
You are a really good guy, thank you for all your help.

**Comment by Mesuva** [comment]
I think the answer you'll get for that error is to upgrade your concrete5 version to the latest.

That line it's throwing the error on is a `break` in the latest version and not `continue`, for example. I'm pretty sure it's 7.3 ready. 

Upgrading concrete5 from version 8.4.5 to 8.5.1 should be pretty painless.

**Comment by mdius** [comment]
Oh, I didn't realize there was a new version. Apparently it is not a self update.
Thank you again.
I will close this though.
