### ISSUE TITLE
Hide Dimensions == 0

### ISSUE THREAD

**Issue by lota** [concrete5-community-store/community_store#493]
In some case, we have products with 2 dimensions only, third dimension is always zero.
![Schermata 2019-10-01 alle 15 04 40](https://user-images.githubusercontent.com/956392/65964840-f9781a00-e45d-11e9-8d44-2e3d34e6e95a.png)

I make a bad patch in src/CommunityStore/Product/Product.php
to get wished result

        // RHX
        $length = ($length > 0 ? $length : '');
        $length_x = ($length > 0 ? $length.'x' : '');

            default:
                return $length_x . $width . "x" . $height;
                break;

![Schermata 2019-10-01 alle 15 14 22](https://user-images.githubusercontent.com/956392/65965005-32b08a00-e45e-11e9-8b24-0436968d3bba.png)

can you provide a better solution for this issue?

TIA
Alessandro

**Comment by Mesuva** [comment]
I would avoid editing files directly in the package folder.
Could you do something very quickly in the product block template, such as:
`<?= preg_replace('/^0.00x/', '', $product->getDimensions()); ?>`
That should remove 0.00x from the start, while leaving something like 10.00x

**Comment by lota** [comment]
The goal is hide measures that are zero. I can't think of any cases where zero has meaning for an object.

I.e.  if I sell a sheet of paper i wish "210x297mm" and not "210x297x00mm"

![misure_pendenti](https://user-images.githubusercontent.com/956392/66739234-97151580-ee70-11e9-89fd-5257bcc4dcff.png)

**Comment by Mesuva** [comment]
I've made an update in the core to address this. 
https://github.com/concrete5-community-store/community_store/commit/32e10cde4c6d0b2f21fd5f6a42b3e34de0b86ef2
