### ISSUE TITLE
Product Filter does not filter unless logged in as Admin

### ISSUE THREAD

**Issue by barkingtuna** [concrete5-community-store/community_store#497]
I don't get any Javascript errors in Chrome... but when logged out on the live site it just refreshes the page with none of the products filtered. However, if logged in, it does filter as intended. https://www.skilcheck.com/products

https://www.concrete5.org/community/forums/usage/community-store-product-filter-not-working-unless-logged-in/

I'm not a developer... just know enough to get the basics done. Is this a case of some script not being loaded on the live site but loaded when logged in? If so, how can I preload the script on the live site to fix this?

**Comment by Mesuva** [comment]
I've shot you an email about this - it's quite a strange one, as if the GET parameters are being stripped before they can be used.
