### ISSUE TITLE
Product Quantity of 999999999

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#498]
When I put this qty in I get:
`An exception occurred while executing 'UPDATE CommunityStoreProducts SET cID = ?, pFeatured = ?, pQty = ?, pBackOrder = ?, pNoQty = ?, pAllowDecimalQty = ?, pTaxClass = ?, pTaxable = ?, pfID = ?, pActive = ?, pDateAdded = ?, pShippable = ?, pWidth = ?, pHeight = ?, pLength = ?, pWeight = ?, pNumberItems = ?, pSeperateShip = ?, pExclusive = ?, pVariations = ? WHERE pID = ?' with params ["922", "0", "999999999", "1", "0", "0", "1", "1", "72", "1", "2017-05-30 07:53:00", "1", 18, 18, 18, 1.25, "1", "0", false, 0, 3]: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'pQty' at row 1`

I can fix it by changing the pQty field from 12,4 to 14,4, but it then messes up my Database Entities.
Where do you adjust the size of pQty in Concrete?

**Comment by Mesuva** [comment]
This looks like the saving is not doing enough validation on the quantity field, something that's not a problem on older version of MySQL, but is going to cause trouble on newer ones.

We can add further validation in, as well as adjust the pQty field to be larger.
When you say it messes up your Database Entities, what's happening in that regard?
You should be able to change it in the code from 12,4 to 14,4 and then do a 'Refresh Entities' via the dashboard page and I'd expect it to work.

Out of curiosity, why are you entered in 999999999 as a quantity, instead of using the unlimited checkbox?

**Comment by mdius** [comment]
I set it up so I could have different delivery times, some items are dropped shipped, so 2-3 days, some are in stock 1-2 days, some are made to order so 4-6 days, and some 1-6 weeks.
So I did this:
`<?php if ($product->getPrice() == 0) {
	} elseif ($showDimensions) {
	if ($product->isUnlimited()) {
	echo '<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> In Stock</div><p><strong>Delivery:</strong> Ships in 2-3 Business Days</p>';
	} elseif ($product->getQty() > 9999 && $product->getQty() < 100000) {
	echo '<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> Made to Order</div><p><strong>Delivery:</strong> Ships in 3-5 Business Days</p>';
	} elseif ($product->getQty() > 999999 && $product->getQty() < 10000000) {
	echo '<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> Ships in 4-10 Business Days</p>';
	} elseif ($product->getQty() > 99999999) {
	echo '<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> 1 - 2 weeks</p>';
	} elseif ($product->getQty() == 0 && $product->allowBackOrders() == 1) {
	echo '<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> 1 - 6 weeks</p>';
	} elseif ($product->getQty() == 0) {
	echo '<meta itemprop="availability" content="OutOfStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> Out of Stock</div>';
	} else {
		if ($product->getQty() > 0 && $product->allowBackOrders() == 1) {
		echo '<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> ' . bcdiv($product->getQty(), 1, 0) . '<br><b>Inventory Fluctuates Daily - Could Delay Shipping</b></div><p><strong>Delivery:</strong> Ships in 1-2 Business Days</p>';
		} elseif ($product->getQty() < 0 && $product->allowBackOrders() == 1) {
		echo '<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> 1 - 4 weeks</p>';
		} elseif ($product->getQty() < 0 && $product->allowBackOrders() == 0) {
		echo '<meta itemprop="availability" content="OutOfStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> Out of Stock</div>';
		} else {
		echo '<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> ' . bcdiv($product->getQty(), 1, 0) . '</div><p><strong>Delivery:</strong> Ships in 1-2 Business Days</p>';
		}
	}
?>
<?php } ?>`

I'm sure this is more of a hack, but it seems to be working.

**Comment by mdius** [comment]
I knew it was someplace in the programming like that, I just could not figure out where.

I simply don't know how to use attributes like that. Maybe I'll play around with that and see what I could figure out.

Thank you again!

**Comment by Mesuva** [comment]
You can use product attributes very similarly to how you would use page or user attributes in concrete5. 

So if you have an attribute with the handle 'est_delivery' (like an option list), you can fetch the value with something like $product->getAttribute('est_delivery'). 

Instead of using the qty field, you could use something like numbers in a field, and then in your logic to work out what delivery time, you could just look at the numbers to work out what to display. Not really different to using the quantity field really, just an cleaner place to store such info.

**Comment by mdius** [comment]
I think I figured out how to do attributes. It'll look a lot like how I have it programmed, but a whole lot less confusing when adding or changing product shipping times.

Thank you again, I'll close this.

**Comment by Mesuva** [comment]
I'm actually going to keep it open, since we need to put some better validation in for the quantity field.

**Comment by mdius** [comment]
Took your advice and did the attributes for the shipping times. I think I worked out all the bugs and this is so much cleaner!
Attributes
`	$instock = $product->getAttribute('in_stock');
	$madetoorder = $product->getAttribute('made_to_order');
	$weeks12 = $product->getAttribute('1_2_weeks');
	$weeks14 = $product->getAttribute('1_4_weeks');
	$weeks16 = $product->getAttribute('1_6_weeks');`

Programming to make them work.
`	if ($product->isUnlimited() || $product->allowBackOrders() == 1 && $product->getQty() < 1) {
		if ($instock) { ?>
<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> In Stock</div>
<p><strong>Delivery:</strong> Ships in 2-3 Business Days</p>
		<?php } elseif ($madetoorder) { ?>
<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> Made to Order</div>
<p><strong>Delivery:</strong> Ships in 3-5 Business Days</p>
		<?php } elseif ($weeks12) { ?>
<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> Ships in 4-10 Business Days</p>
		<?php } elseif ($weeks14) { ?>
<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> 1 - 4 weeks</p>
		<?php } elseif ($weeks16) { ?>
<meta itemprop="availability" content="InStock" /><p><strong>Delivery:</strong> 1 - 6 weeks</p>
		<?php } else { ?>
<p>Sorry, But Delivery Time is currently Unknown on this Item</p>
		<?php } ?>
	<?php } elseif ($product->getQty() < 1) { ?>
<meta itemprop="availability" content="OutOfStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> Out of Stock</div>
	<?php } else { ?>
<meta itemprop="availability" content="InStock" /><div class="store-product-weight"><strong>Stock Quantity:</strong> <?= bcdiv($product->getQty(), 1, 0) ?></div>
<p><strong>Delivery:</strong> Ships in 1-2 Business Days</p>
	<?php }
	}`

It took a minute to figure out how to get the logic part to work, my programming skills are self taught and not really good.

**Comment by mdius** [comment]
Wow, it didn't really show the coding at all that time.

**Comment by Mesuva** [comment]
hehe, I've had that happen more than once!

Great to hear you've worked out a solution. I've always thought attributes are great in concrete5, and being able to tie them to more objects than just pages, users and files is awesome.
