### ISSUE TITLE
Cart amount is zero when sent to payment provider

### ISSUE THREAD

**Issue by simonchilton** [concrete5-community-store/community_store#499]
My store has stopped functioning suddenly. All transaction amounts are zero when they hit the payment provider (SagePay). Started a few days ago with no warning, updates or changes at our end.

Am liaising with the SagePay gateway developer but wondered if anyone has seen this or a similar issue? I believe the transaction amount is calculated by Community Store and not the payment gateway?

Thanks, Simon.

**Comment by Mesuva** [comment]
Against each of the orders in the dashboard, what does the order total show?

**Comment by simonchilton** [comment]
Thanks for the fast reply. It shows the correct amount.

**Comment by Mesuva** [comment]
If it shows the correct number there, I'd be leaning towards it being something to do with the SagePay add-on. Some updates were made to that add-on 4-5 months ago, are you running the latest code?

**Comment by simonchilton** [comment]
I've run an update of the payment gateway and seems to have fixed the issue. I thought it was up to date but the gateway doesn't have version numbers so hard to tell. Sorry to bother you and thanks for the help! Simon.
