### ISSUE TITLE
Discounts on Tiered Pricing Based on Quantity

### ISSUE THREAD

**Issue by pinecreativelabs** [concrete5-community-store/community_store#50]
This is a feature suggestion. 

On the product options, there should be a discount (or custom price) for various ranges of quantities. 

For example: 

Product Name
- 1-5 ($50)
- 6-20 ($45)
- 21+ ($40) 

So if a customer selects 5 as the quanity, the total would be $250.

**Comment by pinecreativelabs** [comment]
Is anyone interested in tackling this?

**Comment by pinecreativelabs** [comment]
I'm thinking this could also be a discount rule, too.

**Comment by pinecreativelabs** [comment]
Any chance this will be added?

**Comment by Mesuva** [comment]
I don't have any immediate need to add this feature myself. I can certainly see how it could be handy in some situtations, but I've just never had a client that needed it. 

Generally I've found that shop keeps sell things in packs, not as individually counted items, which could be handled at this point with product variations. (not saying there aren't cases, I'm just saying I've never encountered a real-world use for it so far).

**Comment by pinecreativelabs** [comment]
I need this feature for a client project I'm working on. They sell books (both digital and physical), and need to be able to offer a lower price per item the higher the quantity for that product.

**Comment by Mesuva** [comment]
I wouldn't wait for someone to add this feature in, it's not something I've discussed with others.
You may need to investigate adding the feature in yourself, or look to convince your client to handle things slightly different, by using variations.

Sometimes people worry about their shops handling all sorts of different pricing structures, but when you actually look at their sales 99% of the time they are selling single items.

Perhaps you could convince them to use something like 5 or 10 packs to handle the occasional bulk purchase. I guess schools may purchase books in bulk, but I'm thinking they're then more likely to manually process such orders anyway.

**Comment by pinecreativelabs** [comment]
Has this feature been added yet?

**Comment by Mesuva** [comment]
Not at this stage, there have been quite a lot of other important features to consider first.

**Comment by pinecreativelabs** [comment]
Is there an ETA on this? 

How complicated would it be to add this feature?

**Comment by Mesuva** [comment]
I'd say it's quite fiddly. It's not just the case of adjusting the Product class to be able to return a different price based on a quantity, there's also the consideration of how the actual product editing interface would work.  I never used the feature myself in eCommerce, so I'm not completely sure how it works, I simply knew the feature was there.

So there's no ETA on it, it comes down to there being a business case for putting the time into the development of the feature.

**Comment by pinecreativelabs** [comment]
I have a project for a non-profit that has needed this feature for the past year now, so I have been unable to complete it due to the lack of this feature. They sell books and digital downloads, and need to be able to have pricing based on the quanity. For example, 5 books at $2 each, or 6 - 10 books at $1.50 each... etc. 
 
I really think this would be a very useful feature to have.

**Comment by JohntheFish** [comment]
@pinecreativelabs. For an application like that, you would be looking at price break points across a range of products. Not for multiple copies of one product. So rather than tiered pricing, you should be looking at implementing a discount.

**Comment by mnakalay** [comment]
I wanted to say thank you guys! I am learning a lot with this conversation.

**Comment by pinecreativelabs** [comment]
I already tried the discount approach, but it doesn't do what I need. What I'm needing is on a per-product basis.

**Comment by jasteele12** [comment]
Sounds more like an addon to me.  In over 15 years of creating custom shopping carts for clients I've had this sort of thing come up a total of once (around 2009).

It was a osCommerce based site and here was the Addon used (kind of) as the base:
[Quantity Discounts by That Software Guy](http://addons.oscommerce.com/info/6751)

Just thought I'd throw that out there FYI...

**Comment by pinecreativelabs** [comment]
Is there anything happening with this? 

If not, what would be needed to develop an addon like this?

**Comment by Mesuva** [comment]
Nothing to report here, if the feature gets added I'll certainly make it known via this issue thread.

I don't think they'd be enough hooks in the process to handle this with an add-on, it would likely require adding it as a feature to the community store package itself.

The question then is where to add the feature, whether it should be on the product itself (like in ecommerce for 5.6.x), or if it should be implemented as a discount rule option.

I believe the former would be easier to add at this point, but I think the latter may be potentially be more useful going into the future. What the discount rules need is the ability for the discount to be applied against one or more specified products or product groups. Then it would need the option to apply tied percentage/value discounts and apply those to the prices of products in the cart.  So adding this kind of feature into the discounts system also starts to improve the discounts features for other purposes anyway. It might also allow for discounts on orders based on quantities of products within groups - 'buy 5 t-shirts and receive 20% of your order'.

**Comment by Mesuva** [comment]
Now available in version 1.3
