### ISSUE TITLE
Call to a member function isSellable() on null

### ISSUE THREAD

**Issue by pvernaglia** [concrete5-community-store/community_store#500]
HI, just downloaded Community Store, installed it on an 8.5.2 site and added a few sample products.  The product list block is working fine but clicking for more info is throwing an error:

Call to a member function isSellable() on null
                           
$stockstatus = $variation->isSellable() ? 'http://schema.org/InStock' : 'http://schema.org/OutOfStock';

Any suggestions? thanks

**Comment by Mesuva** [comment]
Just looks like the wrong variable snuck into a recent commit:

Try this simple fix: https://github.com/concrete5-community-store/community_store/commit/f2ff3d58a8ebcd83ef16cf60f4072ccc39099a1e

**Comment by pvernaglia** [comment]
Thanks!
