### ISSUE TITLE
 [Feature Request] Functionality to handle orders cancelled, rejected or timed out at payment provider stage

### ISSUE THREAD

**Issue by simonchilton** [concrete5-community-store/community_store#502]
Currently there is no provision for handling orders that are cancelled, rejected or timed out at payment provider stage?

So if a customer orders an item and doesn't go through with payment for whatever reason, the items are not re-stocked leading to incorrect stock levels.

Could this be added to core code? Thanks.

**Comment by Mesuva** [comment]
Certainly would be great to address this - will look at some stage, just can't immediately jump into this.

**Comment by edbeeny** [comment]
I've had a quick look at this and made a quick hack in the checkout.php contoller file.

`    public function addStock($cart)
    {
        foreach ($cart as $cartItem) {
            $product = $cartItem['product']['object'];
            $qty = $cartItem['product']['qty'];
            $inStock = $product->getQty();
            $newStock = $inStock + $qty;

            $variation = $product->getVariation();

            if ($variation) {
                if (!$variation->isUnlimited()) {
                    $product->updateProductQty($newStock);
                }
            } elseif (!$product->isUnlimited()) {
                $product->updateProductQty($newStock);
            }
        }
    }

    public function failed($guest = false)
    {
        //Add the stock back against the product
        $this->addStock(StoreCart::getCart());`

This does put the stock back in, however if the stock level is 1 on the 1st attempt, it removes the product from before stock is added back in.

**Comment by Mesuva** [comment]
I've reworked the logic of this so that quantities are only decremented when an order actually gets turned into a real order and is visible in the dashboard (so an invoice order, or when an order is placed _and_ paid for via a payment gateway). In the master now, and will be in the next release.

**Comment by simonchilton** [comment]
Awesome, thanks for the hard work guys, much appreciated!
