### ISSUE TITLE
Multilingual Common translations copy string option

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#503]
It would be a good idea to be able to click a button (right arrow) to copy over the original text (also including html code to the translation field.

You can see my idea here:

![Screenshot_384](https://user-images.githubusercontent.com/1224538/68478123-76519d00-022f-11ea-94c3-c0081925a0d2.jpg)

**Comment by Mesuva** [comment]
This has been pushed up via https://github.com/concrete5-community-store/community_store/commit/1796717bbe4a3f1add581a15aba4f0d0e9707f0f
