### ISSUE TITLE
Creating a new product does not populate to all language trees while creating the detail page

### ISSUE THREAD

**Issue by MichaelMaar** [concrete5-community-store/community_store#504]
I have discovered that I have to manually create/copy the product page to all language trees after creating the product. It is only created under the default language at the moment. It should be populated under all language trees.

![billede](https://user-images.githubusercontent.com/1224538/68478489-49ea5080-0230-11ea-801f-3fa0ba37d2b7.png)

**Comment by goesredy** [comment]
Any update in here ? Thanks

**Comment by Mesuva** [comment]
Not yet sorry, but it's not been forgotten!

**Comment by Mesuva** [comment]
I've pushed up some code into a feature branch for this.
https://github.com/concrete5-community-store/community_store/commit/432b95a47199638f7ca5d6fa7bdfe1b686ee3eaf

It's not that hard to apply directly if you wanted to to test it out. Just be aware it's very fresh code, so use with caution.

**Comment by jcrooke** [comment]
I've been testing the multi-lingual features and they don't appear to work 100%.  Please take the following steps;

1) A fresh install with UK (default) and US languages
2) Create product "Product ABC" with description "Product ABC"
3) Product is created at `/product-abc` and `/us/product-abc`
4) Go to translate product "Product ABC", calling it "Product XYZ" on us, Save:

![image](https://user-images.githubusercontent.com/1670117/76637656-0cc9fe00-6543-11ea-9a6a-828af0a37fa4.png)

5) The product slug *isn't* renamed to `/us/product-xyz` and at `/us/product-abc` it is still called "Product ABC".  Furthermore, after adding to cart, it's still known as "Product ABC" in `/us/cart`

![image](https://user-images.githubusercontent.com/1670117/76638274-1738c780-6544-11ea-9cd2-a84c4302b1da.png)

Am I doing something wrong?  How are the translations supposed to work?

**Comment by goesredy** [comment]
@jcrooke try visit the page without login
