### ISSUE TITLE
Changing shipping address country loses classes and data elements on state input/select

### ISSUE THREAD

**Issue by markbennett1973** [concrete5-community-store/community_store#506]
When changing the billing address country, the state input or select form element (store-checkout-billing-state) gets replaced with values for the new country, and retains any custom classes or data elements added to that element.

When changing the shipping address country, any custom classes or data elements which were added to the state form field (store-checkout-shipping-state) get lost.

**Comment by markbennett1973** [comment]
In `communityStore.js`, the `updateBillingStates` function gets the classList and dataList of the existing element, and passes that as part of the data array to the stateprovince/getstates helper.

In the `updateShippingStates`, this does not happen. Copying those lines from the `updateBillingStates` function seems to resolve the problem.

**Comment by Mesuva** [comment]
Thanks for this - I've pushed up this update:
https://github.com/concrete5-community-store/community_store/commit/c76ab9d28c2f15eb21ffd8f2dae4e36d05c77701

Does that reflect what you were saying in terms of copying the same code from the billing side of things?  (and fix your issue!)
