### ISSUE TITLE
From address in settings not validated as email

### ISSUE THREAD

**Issue by TeddyNovak** [concrete5-community-store/community_store#509]
Set up a new site to test a theme I’m looking to upload to the concrete5 mp. Getting this error in the logs when emails fail to turn up: "Community Store: a receipt email failed sending to Array"

Any ideas?
Do you need to see my server settings?

Test site: https://rgb-shop.55web.uk/
Regards
Steev

**Comment by Mesuva** [comment]
The debug line that is outputting the message was actually coded wrong, I've both fixed that and adjusted it to actually include the error message:  
https://github.com/concrete5-community-store/community_store/commit/2cbf7b7d41d5f5e7c1d0cfc1b7af8ac6ba5fad6c

Try adjusting those lines and sending some emails again - the log hopefully will then be helpful.

A resend of the receipt email of a existing order should trigger the same problem (instead of having to put through orders)

**Comment by TeddyNovak** [comment]
Thanks Ryan,
This is the new error message:
Community Store: a receipt email failed sending to editor@thundridge-wadesmill.co.uk, with error The input is not a valid email address. Use the basic format local-part@hostname

Community Store: a receipt email failed sending to editor@thundridge-wadesmill.co.uk

Community Store: a notification email failed sending to Array, with error The input is not a valid email address. Use the basic format local-part@hostname

Community Store: a notification email failed sending to Array

**Comment by Mesuva** [comment]
Looks like I still have some other logging lines to fix, and I should also make the existing ones even more detailed.

But in terms of this particular issue, my first question would be: what do you have set as your _Emails Sent From_ settings in the store config?    
These settings are at /index.php/dashboard/store/settings#settings-notifications

**Comment by TeddyNovak** [comment]
So sorry Ryan, my stupid mistake had a ',' instead of a '.' in the from email address?
May not have seen it if you hadn't asked the question.
Many thanks.

**Comment by Mesuva** [comment]
That means we're lacking validation on the field, at the very least marking the type of the field as email - I'll re-open this, and rename it as something to address.

**Comment by TeddyNovak** [comment]
Okay, makes sense.

**Comment by Mesuva** [comment]
I've adjusted the field type for this, plus have put in some warnings in the dashboard if the field isn't filled in.
