### ISSUE TITLE
Group Store Customer is not added?

### ISSUE THREAD

**Issue by jacintoo** [concrete5-community-store/community_store#51]
In the file /src/CommunityStore/Order/Order.php line 538
it commented:
//add user to Store Customers group

But actually it is not added:
I think it is probably because the following code on line 541:
`$user->enterGroup($group);`

but it should be the same as line 547:
`$user->getUserObject()->enterGroup($g);`

It is not very important but it would be helpful for debugging to see the users who purchased any orders.

Thank you

**Comment by Mesuva** [comment]
Thanks for this, should be fixed by https://github.com/concrete5-community-store/community_store/commit/50eb1b47bab097e99a8d7ce89825f7fa3fc9cbc4
