### ISSUE TITLE
"There are currently no payment methods available to process your order."

### ISSUE THREAD

**Issue by zpartakov** [concrete5-community-store/community_store#510]
Using the excellent community_store since a long time on a website, I have an issue on an install on a new website; the C5 is a core Version - 8.5.2, running php 7.2.26, community store Version 2.1.10
When I submit an order, system returns 
"There are currently no payment methods available to process your order."
But the standard invoice is activated.
The problem  comes maybe from the fact that, in the beginning, I've installed package community_store_paypal_standard, then disabled it.
I've tried to deactivate both packages community_store and community_store_paypal, cleaned the database from all the tables including "community", cleared cache, re-installed package.
Problem remains
Maybe you have a clue for me?

**Comment by Mesuva** [comment]
In the settings for the Invoice payment method, do you have any values in the _Minimum Order Value_ and _Maximum Order Value_ fields?

The Invoice payment method should be offered regardless of any other payment method installed, as long as it is enabled and it meets the Min/Max order requirements (if set)

**Comment by zpartakov** [comment]
Thanks Mesuva, unfortunately no changes - I've tried both setting the two fields (1-99) and unsetting, msg remains  "There are currently no payment methods available to process your order."

**Comment by Mesuva** [comment]
That's very odd - I've never seen that happen, and I can't think of a way the code for the Invoice payment method would do that.

Feel free to email me at ryan@mesuva.com.au and I'm happy to take a look at your setup.

**Comment by zpartakov** [comment]
ok fine thanks I'll send you a pm
