### ISSUE TITLE
Fix for issue #506 breaks checkout process when not requesting shipping details

### ISSUE THREAD

**Issue by losttheplot** [concrete5-community-store/community_store#512]
### Problem:
When checking out and the shipping details form is not required, `updateShippingStates()` is called on line 580 of communityStore.js. `updateShippingStates()` then tries to reads the class of `#store-checkout-shipping-state`, which is not present on the page because the shipping details form is not required. `updateShippingStates()` then throws a critical error.

### Cause:
Code added by push #506 which, presumably, needs wrapping in a conditional.

### Temporary Fix:
Roll back commit c76ab9d28c2f15eb21ffd8f2dae4e36d05c77701

**Comment by Mesuva** [comment]
Thank you for this. I've pushed up a fix for this (I'm quite surprised this wasn't noticed sooner, but it wouldn't have made it into a release - something we are due for).
