### ISSUE TITLE
Temp fix for: Integrity constraint violation: 1048 Column 'cParentID' cannot be null

### ISSUE THREAD

**Issue by losttheplot** [concrete5-community-store/community_store#515]
### Environment:
concrete5: 8.5.2
community_store: 2.1.10 master as at 27-02-20
php: 7.2.27
mysql: 5.7.28 - Percona XtraDB Cluster (very strict)

### Error:
`An exception occurred while executing 'INSERT INTO Pages (cID, siteTreeID, ptID, cParentID, uID, cOverrideTemplatePermissions, cInheritPermissionsFromCID, cInheritPermissionsFrom, cFilename, cPointerID, cPointerExternalLink, cPointerExternalLinkNewWindow, cDisplayOrder, pkgID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1353, null, "24", null, "1", "1", null, "PARENT", null, 0, null, "0", "0", "30"]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cParentID' cannot be null`

### Circumstances:
When saving any new product of any data complexity. The basic product saves before the exception is thrown, but data such as images and grouping does not.

### Problem Traced to:
/html/packages/community_store/src/CommunityStore/Product/Product.php - line 1767 onwards - function generatePage()

### Summary:
If the c5 deployment is not operating in a multilingual environment, line 1768 ( `$mlist = Section::getList();` ) fetches a page list regardless and then iterates through that list. Line 1771 ( `$relatedID = $m->getTranslatedPageID($parentPage);` ) then attempts to find an ID for a non-existent page, and line 1775 ( `$parentPage = Page::getByID($relatedID);` ) overwrites the parent page ID with a null, which is then passed to an SQL record insertion action. I'm guessing that lines 1767 to 1791 need wrapping in a config conditional. 

### Temporary Fix:
Change line 1773: if ($targetCID != $relatedID) {
to: if (!empty($relatedID) && $relatedID != $targetCID) {

**Comment by Mesuva** [comment]
Thanks for this - the creation of multilingual product pages is very new, and I'd simply not tested it outside of that context!   I've pushed up a fix for this.
