### ISSUE TITLE
Multi-lingual translations doesn't seem to work

### ISSUE THREAD

**Issue by jcrooke** [concrete5-community-store/community_store#517]
I've been testing the multi-lingual features and they don't appear to work 100%.  Please take the following steps;

1) A fresh install with UK (default) and US languages
2) Create product "Product ABC" with description "Product ABC"
3) Product is created at `/product-abc` and `/us/product-abc`
4) Go to translate product "Product ABC", calling it "Product XYZ" on us, Save:

![image](https://user-images.githubusercontent.com/1670117/76637656-0cc9fe00-6543-11ea-9a6a-828af0a37fa4.png)

5) The product slug *isn't* renamed to `/us/product-xyz` and at `/us/product-abc` it is still called "Product ABC".  Furthermore, after adding to cart, it's still known as "Product ABC" in `/us/cart`

![image](https://user-images.githubusercontent.com/1670117/76638274-1738c780-6544-11ea-9cd2-a84c4302b1da.png)

Am I doing something wrong?  How are the translations supposed to work?

**Comment by Mesuva** [comment]
From what you've described, the only difference in expectation is that the multilingual handling _doesn't_ rename slugs at the moment. 

But I'd be expecting the product names to be changing in the different language section of the sitemap. **Are you testing the latest release or is this in master?**

I just quickly added a en_GB language to a test site (which was just en_US). I copied the site tree, translated a product, and found that when I jumped between sections it would update the product name on both the product page and in the cart.

So I'm wondering if this is something about a fresh install, or that it's done with en_GB first and en_US second.

**Comment by jcrooke** [comment]
@Mesuva this is the latest release, not master.  I will give master a go if that's the better option

**Comment by Mesuva** [comment]
I was under the impression that that latest release did handle the translations correctly.
Just to confirm, you aren't using any block template overrides at all?  (I'm not getting that impression, you said it's a fresh install).

But there's been a large number of fixes since the last release, most minor, but all adding up, so it's worth checking out the current master. I've been saying it for a while, but I'm _very_ close to finishing up a major feature to include and then put out another release.

**Comment by jcrooke** [comment]
I can confirm this is a fresh install, so no block template overrides at all.  I've not had a chance yet to test current master, but will let you know here the result.

**Comment by Mesuva** [comment]
Interesting - I'm wondering if it's to do with the languages both being seen as English, but with different localities. If you tried adding French for example, I'm wondering what will happen.

I will check this myself at some stage soon.

**Comment by Mesuva** [comment]
On a fresh install (of the master branch), I have multilingual product data swapping over for English, French and Danish.

So it might be worth testing this on the latest master.
