### ISSUE TITLE
PayPal Standard not working

### ISSUE THREAD

**Issue by onestone2023** [concrete5-community-store/community_store#520]
It seems to only be working when logged in and when invoicing is enabled. When logged out I get there is no payment gateway available, unless I change the order to allow invoicing which I don't really want.

**Comment by Mesuva** [comment]
I'm not finding this, I'm able to disable all payment methods except for Paypal, and have it offered as a payment option when checking out as a guest. (testing on the latest master at least)

Have you done any customisations of the checkout single page?

**Comment by onestone2023** [comment]
It strange, after 2 days of leaving the site idle all is now working as it should. Perhaps there was some type of caching issue or something, but I thought I'd checked all that. Thank you for your response. 

I'm now having issues with variants though. I'll post another ticket for that.
