### ISSUE TITLE
Error: Payment id is invalid

### ISSUE THREAD

**Issue by Mesign** [concrete5-community-store/community_store#522]
The payment works using the Mollie payment method. But when the user is getting redirected after paying, they see a fullscreen error:

```
An unexpected error occurred:
Error executing API call (request): The payment id is invalid.
```

The user is redirected to the url, see below (3 is the latest order). I also see that error when visiting that page. When entering "4 (none existing order)" I get redirected to empty shopping cart.  

`domein.ext/index.php/checkout/ordercompletion/3`

The order is valid because I see a succesfull order in Mollie and in the Community Store. The user also gets an e-mail that the order was made. But they see an error after payment.

Any Idea what is going wrong?

**Comment by Mesuva** [comment]
I think this one is best raised on the specific issues list for the Mollie payment method:
https://github.com/concrete5-community-store/community_store_mollie/issues

There's been quite a few updates to this payment method just recently, and a release put out, are you using latest release here?   https://github.com/concrete5-community-store/community_store_mollie/releases

I don't know a huge amount about this payment method - @Jozzeh may be able shed some light on this error.

**Comment by Mesign** [comment]
I cleared the cache and looked in their Mollie account for problems. At their websiteprofile they put in their domein.ext instead of shop.domein.ext. I made a test order and did not received any errors. I guess that was the problem. 

Thanks you for the information.
