### ISSUE TITLE
Gratuity on Checkout

### ISSUE THREAD

**Issue by onestone2023** [concrete5-community-store/community_store#524]
Might you have any ideas about how to create a gratuity option? Perhaps one of the following:

1) An open text payment field where a customer could enter the gratuity of their choice on checkout?

2) Or setup optional percentages on checkout.

3) Or direct the cart to a final product that offered gratuity percentages as optional variants?

Thank you for your time.

**Comment by Mesuva** [comment]
One option could be that you:
- Create a gratuity product, one that is configured to 'Allow customer to enter price' (with or without suggestions), also set the shipping to no
- You'd configure that product to 'Send customer directly to checkout when added to cart'

Then at the top of your checkout page, you could add a link to the gratuity product's page, with something simple like 'Would you like to add a gratuity?'

A more complex solution could be that you override the checkout's single page, and put in some logic for a link to that product, where it only shows if that product is not in the cart. 

So the customer would see that link, click on it if they wanted to add a gratuity, enter a price, and they'd return back to the checkout page with it sitting in their cart.

There is an option that only allows one of a product in a cart, and prevents it from being added twice. This seems to work when a fixed price product is added, but currently when the price is able to be entered.. I may need to review that

**Comment by onestone2023** [comment]
Your suggestions got me thinking. I'm realizing I could just hard code a link to a Gratuity Product on the cart popup just prior to Checkout. I wouldn't make it available by any other means, and would only allow the single instance as you've suggested above. I'll likely setup radio buttons on the product for optional percentage based gratuity.

I truly appreciate the brainstorming. You're a high caliber developer and contributor. Thank you!

**Comment by Mesuva** [comment]
I've addressed the issues I've described above, with the fix in the master branch now - and it'll be in the next release.
