### ISSUE TITLE
Filter out products in certain category

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#528]
Hi, 
I can filter out products with a certain Category (Event) easily enough but I need to do this before starting to write out the markup, because otherwise the pagination will be affected.  For example, if I have set 9 products per page and the first 2 are written out but the next 7 of them are filtered out, I will end up with 2 on page 1 and then the next unfiltered product will be on page 2.

So I had the idea of looping through the products and removing the product from the array if it matches a category.  Then I can loop through the remaining products and write out the markup as normal:

```
foreach ($products as $product) {
        $cats = $product->getLocationPages();
        $categoryNames = "";
        foreach ($cats as $cat => $val) {
             $pageID = $val->getCollectionID();
             $categoryPage = Page::getByID($pageID);
             $categoryNames .= ' ' . $categoryPage->getCollectionName();
        }

        if(strpos($categoryNames, "Event") !== false) {
            unset($products[$product->getPID()]);
        }
    }
```

This doesn't work no errors, just doesn't filter the list at all.  If I do this:
`unset($products[$product]);`

Throws the error: Illegal offset type in unset

How so I remove a $product from the $products array?

Thanks!

**Comment by Mesuva** [comment]
To filter out products and still have pagination working as expected, the filtering needs to be at the database query level, i.e in the logic contained with the ProductList.php class. Even if you filtered the list of products returned to loop through in the block, the pagination controls are still going to be looking at the original query used to fetch them.

There's currently not an option on the Product List block to exclude products that have been categorised under a certain page, only exclude products in particular product groups.  (and I'd say it's unlikely we'll add excluding by categorisation/page, that's quite obscure!)

Therefore could you simply use a product group to do the filtering, and just ensure that your event products are placed in that group?

To make it automatic, you could potentially listen to the events, `on_community_store_product_add` and `on_community_store_product_update`, and use that to fire some code that ensures that a new event product is automatically placed into the Event product group if it's been categorised under the Event page.

**Comment by madesimplemedia** [comment]
Thanks for this, yes that solution will work fine
