### ISSUE TITLE
Sudden 404 on /cart/add

### ISSUE THREAD

**Issue by simonchilton** [concrete5-community-store/community_store#532]
Up until Saturday our store was working fine. Since then we're gettign a 404 on /cart/add xhr request. Nothing has changed our end, no idea why this is happening. Hosting company say nothing has changed their end.

Any thoughts?

**Comment by Mesuva** [comment]
_Something_ has changed. 

Can you still view the `/cart` URL?

**Comment by simonchilton** [comment]
Yeah, don't know what though. I get a formatted 404 page for /cart

**Comment by Mesuva** [comment]
That suggests that the cart page has been moved or deleted.

All the adding and editing of the modal cart happens through the same `/cart` page, so if that's no longer available it's going to break the cart operations overall.

Happy to take a look if you send me a URL and some login credentials - ryan@mesuva.co.uk

**Comment by simonchilton** [comment]
Thanks Ryan for the quick fix, sorry it was all our fault! 

Brilliant service, as always :)

**Comment by Mesuva** [comment]
No worries at all, happy to help

(for anyone who stumbles across this issue, it was just that the cart page had been moved around the sitemap, it has to be left where is site location wise)
