### ISSUE TITLE
Email Notifications suddenly not working

### ISSUE THREAD

**Issue by onestone2023** [concrete5-community-store/community_store#535]
As of this morning the cart has suddenly stopped sending email notifications of orders and receipts. I'm actually wondering if its an issue with PayPal reporting the completed transaction. We get the transaction notification from PayPal but not the cart itself. I can login and manually resend the notices, but they aren't happening automatically.

**Comment by Mesuva** [comment]
Over the years I've seen Paypal do all sorts of unexplained things with it's IPN callback...

- First thing to look at is the concrete5's logs, the Paypal method does have a bunch of logging lines for when things go wrong (and extra commented out ones for further investigation)
- Check the actual webserver access logs for a request to /checkout/paypalresponse
- Within Paypal, check their IPN logs: https://www.paypal.com/ie/cgi-bin/webscr?cmd=_display-ipns-history&nav=0.3.2  (I often find it hard to actually get to those through the menu, hence the link)

I've seen cases where Paypal just fails to send the messages for a period of time. I've also had cases where IPN has simply been turned off in Paypal too.
