### ISSUE TITLE
Making Sale Price and Quantity Based Pricing work together

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#536]
Where a product uses Quantity Based Pricing and then has a Sale Price applied all quantity price tiers are overridden by the Sale Price.

This really stops Sale Prices being useful for products with price tiers.

Would a PR that extended ProductPriceTier to add a Sale Price value be an acceptable addition to Community Store?

**Comment by Mesuva** [comment]
Sure, anything that makes those options more flexible and useful is certainly welcomed.

I've not used the price tiers on a project myself, but I think I struggled to think of where you'd use them and then enter a sale price.. can you give an example?

**Comment by katalysis** [comment]
I'm building a wine store that provides options to purchase quantities including cases...

![wine-example](https://user-images.githubusercontent.com/4235012/81317334-9f3ed780-9084-11ea-9d4e-ac1333790444.png)

I'll use the Special price to show a headline discount single bottle price and then the tiered prices to for quantity selection.

In some ways I don't really need the special prices in the tiers I just need setting the special price not to override the tiers.

**Comment by katalysis** [comment]
I had considered the attribute option but it felt a bit clunky.

I'm thinking the discount really _shouldn't_ override the tierred pricing, it's a signpost for a bargain but doesn't need to override the price tiers - they can be adjusted as needed to follow the price reduction.

**Comment by Mesuva** [comment]
I agree. 

Also, I very much doubt anyone is using the store and relying on using a sale price to override the tiered pricing, so 'fixing' this isn't going to be a backwards compatibility issue.

Feel free to do a PR if you can see a quick solution to this, otherwise I'm happy to look at this soon.

**Comment by Mesuva** [comment]
Apologies for overlooking this one - I've pushed up something to address this issue, it's pretty simple: https://github.com/concrete5-community-store/community_store/commit/9969dad3c67ab944941d2dfde539e2dc86f5d372
