### ISSUE TITLE
change url /cart

### ISSUE THREAD

**Issue by webmeier** [concrete5-community-store/community_store#538]
accidently added a canonical url to cart. now i do not find a way to treat it back

**Comment by Mesuva** [comment]
I didn't think there was a way to add additional urls to single pages.

Can you post some screenshots?

**Comment by webmeier** [comment]
![Bildschirmfoto 2020-05-18 um 13 38 20](https://user-images.githubusercontent.com/33833382/82209076-f490a980-990c-11ea-89a8-bcfe946c50b2.png)
i changed it in the composer

**Comment by Mesuva** [comment]
I really don't know how you changed it!

You may need to do it manually in the database, look for the `PagePaths` database table, and update the cPath value.

**Comment by webmeier** [comment]
Thank You for your highspeed answering. 
This is was i have already looked for but unfortunatly there is no entry
![Bildschirmfoto 2020-05-18 um 13 47 14](https://user-images.githubusercontent.com/33833382/82209812-3110d500-990e-11ea-84f4-97f3053e87da.png)
shoul i add one manually

**Comment by Mesuva** [comment]
I think so - there really should be entry - easy to remove if it doesn't fix it.

**Comment by webmeier** [comment]
Thank You Ryan, I added it manually in the database. that's fixed now. The main problem is i installed the community store on an Installation which' sitemap is a mess due to core updates.
Multilingual and I have two kind of home/
i will try to fix.
