### ISSUE TITLE
Option Stock Levels not working as anticipated

### ISSUE THREAD

**Issue by RayGan0303** [concrete5-community-store/community_store#539]
I have a number of products each having 3 options. I've set the stock level quantity for each in their individual option sections, but the displayed stock levels seem stuck (and maxed out) at one no matter what I put in the UI. I've just installed Community Store 2.2 to see if that fixes things, but no joy.

Stock control works fine for items without options (i.e stock control setting in the body of the UI)

Any guidance would be much appreciated (even if it's RTFM ;o)

Many thanks and stay safe.

**Comment by Mesuva** [comment]
What do you have set as the 'Offer quantity selection' option?

**Comment by RayGan0303** [comment]
Offer Quantity Selection is set to "yes"

**Comment by Mesuva** [comment]
In the cart, does it actually offer you the ability to change the quantity, or does it simply show 1, with no field?

When you say you updated, from what version did you update from?

It might be something I can't really tell any more without being able to look at the site - feel free to email me at ryan@mesuva.co.uk

**Comment by RayGan0303** [comment]
Looks like it's fixed itself with th eupgrade....I had a few products I entered with the previous build (sorry don't recall the version) and the odd performance continued even after upgrading. I've just created a new test product cloned from one of the originals, changed the stock levels and it's all working as expected.

Thanks for your help

**Comment by Mesuva** [comment]
That's great - it may have been some sort of caching to do with the product fields.
Does it now work if you go back and view/edit one of the original products?

**Comment by RayGan0303** [comment]
No, not unless I make a change and save it, then it does.

**Comment by RayGan0303** [comment]
For completeness, the old version of CS I had was 2.1.7

**Comment by Mesuva** [comment]
Interesting - that option has been there for quite some time, perhaps since version 1.
Let me know if you hit further issues
