### ISSUE TITLE
Sales and Discounts

### ISSUE THREAD

**Issue by WesDowney** [concrete5-community-store/community_store#547]
I'm assuming this is intended behavior but just in case it's a bug, I wanted to double check.

If there is a discount set and a product has a sale price, the product gets sold for the sale price. No additional discounts are applied to the sale product.

**Comment by Mesuva** [comment]
Yes, from memory that's the intended behaviour.

The think was based on how more often than not a shop will do something like '20% storewide^"
And then have a disclaimer: 
^ excludes sale items and other promotions

Having something on sale, and then applying a further discount seems potentially dangerous to me, so safer to just stick to the sale price.

**Comment by WesDowney** [comment]
Thank you for confirming! 👍

The rationale makes sense and sounds like the safe way to be.
