### ISSUE TITLE
Error installing Mollie payment gateway package 

### ISSUE THREAD

**Issue by Mesign** [concrete5-community-store/community_store#548]
I got two webshops where I can't install the Latest Mollie payment gateway. Any ideas what the problem could be? And if it is a problem related to the latest C5CS version, is it possible/easy to downgrade without losing products / data?

View the problem:
https://github.com/concrete5-community-store/community_store_mollie/issues/3#issue-641984198

**Works:** (C5: 8.5.2   C5CS:2.1.10   Molli:0.0.8)
**Does not work:** (C5: 8.5.3  C5CS: 2.2.7  Mollie: 1.0.0)
**Does not work:** (C5: 8.5.2  C5CS: 2.2.2  Mollie: 1.0.0)

Also tried to install old version of mollie (0.0.8) (wanted to know if old version maybe work). Gives me an error:
`An exception occurred while executing 'DROP INDEX IDX_C0DB918CECC024CA ON molStoreOrderTransactions': SQLSTATE[HY000]: General error: 1553 Cannot drop index 'IDX_C0DB918CECC024CA': needed in a foreign key constraint`

**Comment by Mesuva** [comment]
I don't use Mollie myself, but I'll give this a test today myself and see what I can find.
