### ISSUE TITLE
Setting pSalePrice to null resets it to 0 in the new version

### ISSUE THREAD

**Issue by evgk** [concrete5-community-store/community_store#549]
When importing the product data in PHP, I do the following:
```
                 $dbProductData = [
                     'pName' => $productData['name'],
                     'pDesc' => $productData['description'],
                     'pSKU' => $productData['id'],
                     'pPrice' => $productData['price'],
                     'pSalePrice' => null,
                     'pNoQty' => false,
                     'pAllowDecimalQty' => false,
                     'pQtyLabel' => '',
                     'pMaxQty' => 0,
                     'pfID' => $fID,
                     'pActive' => $is_active,
                     'pQty' => $productData['pQty'],
                     'pBackOrder' => $productData['pBackOrder'],
                     'pShippable' => 1,
                     'pTaxable' => 1,
                     'pTaxClass' => $taxClassId
                     //'pBackOrder' => $productData['pBackOrder']
                 ];
```

When saving that data with saveProduct, pSalePrice gets set to 0. It wasn't a problem in earlier versions. I've narrowed down the problem to this commit:

https://github.com/concrete5-community-store/community_store/commit/00d7bd69147c6407b1040185278f674486b431db

setSalePrice function was changed from:
```
    public function setSalePrice($price)
    {
        $this->pSalePrice = ('' != $price ? (float)$price : null);
    }
```
to 
```
    public function setSalePrice($price)
    {
        $this->pSalePrice = ($price !== '' ? (float)$price : null);
    }	    
```

Since null is not empty string, it gets converted to float, which sets it to 0. I guess the idea behind that fix is to try to make it accept 0 as a valid value? I think isBlank function might be a better fit for this:
```
function isBlank($value) {
    return empty($value) && !is_numeric($value);
}
```

since I think it shouldn't interpret null or a missing pSalePrice value as 0.

**Comment by Mesuva** [comment]
I see what you mean here, the setSalePrice function was coded directly to handle the product edit page in the dashboard, but I can how that's not the only context where it would be used.

I'll review this soon for the most appropriate solution.

**Comment by Mesuva** [comment]
Does this fix work for what you are doing with your import?
https://github.com/concrete5-community-store/community_store/commit/87538bf79aaac74a54946974a0459379c27ebc8f#diff-38304138b8c50b9d00b25f35812a2451R596

**Comment by evgk** [comment]
Hi,
  Yes, it should solve the problem. Thanks, nice to have that fixed.
