### ISSUE TITLE
Feature: Comments on client and admin side

### ISSUE THREAD

**Issue by appliculture** [concrete5-community-store/community_store#55]
It would be great to have the ability to add a comment to the order status in the admin (with timestamp like the status change) and also a the ability for the customer to let a comment about his order on checkout

What do you think ?

**Comment by Mesuva** [comment]
Having the ability to add notes is certainly useful.

With the ability for customers being able to add notes on the checkout, I think these might be covered by 'order attributes. @TheNorthman has been having a look at those, he might be able to confirm if that's something it'll be able to handle.

**Comment by MichaelMaar** [comment]
That is what 'order attrbutes' is all about. To add custom attributes to the checkout page! It will hopefully be merged in the near future!
