### ISSUE TITLE
Sort order field for product groups

### ISSUE THREAD

**Issue by evgk** [concrete5-community-store/community_store#554]
We're heavily using the product groups feature on our sites. One issue with the current implementation is that there is no sort order field on the ProductGroup model. I know there is a sort order field for the categorization through product pages, but we're not using those - product groups give much more flexibility to the content manager as to how the products from point of sale should be displayed on the site. I think that might be something that is useful in general - should we do a PR for that? So adding a pSortOrder field on ProductGroup, making it editable in backend group-edit screen, and adding a "Sort by group order" field to the sort-by list of the product-list block.

**Comment by Mesuva** [comment]
That sounds very useful, it sounds similar to how you can re-order files in file sets.

A PR would be very welcome.  Thank you for your contributions to date, they are very appreciated!

**Comment by evgk** [comment]
Included it in PR#552, commit:

https://github.com/concrete5-community-store/community_store/pull/552/commits/54f304e8ed5c455e90a39a784bea5d4fce8860e3
