### ISSUE TITLE
Duplicate id's in productlists

### ISSUE THREAD

**Issue by WebmakersJaap** [concrete5-community-store/community_store#566]
When having multiple product lists on a page (like "newest", "top selling" and "on sale" on the homepage) a product can appear multiple times in these lists.
In that case there will be multiple <form-tags with duplicate id-attributes.
This will:
- invalidate the html
- throw warnings on chromium browsers
- **and most of all:** give problems with filled in quantity when adding a product to cart (it might pick the quantity of the wrong form)

**Comment by Mesuva** [comment]
This sounds like it can be solved by pre-pending the block ID when generating ID tags and attributes, will take a look when I can.
