### ISSUE TITLE
\Database::connection()->getEntityManager() deprecated

### ISSUE THREAD

**Issue by Mesuva** [concrete5-community-store/community_store#58]
With 5.7.5.7 the way to fetch the doctrine entity manage, \Database::connection()->getEntityManager() has been deprecated.

I believe this needs to be replaced with:
ORM::entityManager();

(there is also $pkg->getEntityManager() for packages, but I don't think this is used on community store)

**Comment by MichaelMaar** [comment]
@Mesuva Andrew Aembler returned some code yesterday to the 5.8 branch and tagged is as depricated -  it might make a difference for Community-Store - I will test something today.

**Comment by Mesuva** [comment]
Unless Concrete\Core\Attribute\Value\Value has been put back in, I think you might hit an error immediately after install. 
https://github.com/concrete5/concrete5/issues/3808

**Comment by MichaelMaar** [comment]
You are probably right. I have some issues to merge the git version of C5.8a3 with my local build (can't install C5). So I have to wait for Mnkras to make a build to use.

**Comment by Mesuva** [comment]
Addressed by https://github.com/concrete5-community-store/community_store/commit/7ce0adc82c98546334dd568be62aa43639a2416e
