### ISSUE TITLE
Tax-Settings assigend to multiple countries causes error "Provided index 1 does not exist in plural array"

### ISSUE THREAD

**Issue by webpresso-ch** [concrete5-community-store/community_store#585]
Steps to reproduce:

- Install Concrete5 8.5.4 with sample content
- Install Community Store Release 2.3.1 and activate it
- Set Language to German / Country Germany
- Copy the translated german version from translate.concrete5.org to /applications/languages/de_DE/LC_MESSAGES/messages.mo

Now add a tax-rate and assign this to two countries like in the screenshot:
![CleanShot 2020-11-15 at 17 33 05@2x](https://user-images.githubusercontent.com/51955596/99192978-355f6300-2776-11eb-8dbf-3d67f04bbefa.png)

Save the setting. This error appears:
`Provided index 1 does not exist in plural array`

The relevant part in community store seems community_store/single_pages/dashboard/store/settings/tax.php on line 215

The same procedure without language (leaving en_US) setting works. 
So I'm not sure if it's a community store issue or a concrete5 issue. Still wanted to post it here, perhaps someone has an idea how to deal with that or how to fix.

**Comment by Mesuva** [comment]
I've pushed up a fix for this. My understanding is that the German translation doesn't have the string for 'Countries'. 
I wouldn't have though that would have thrown an error, perhaps the t2 function in concrete5 itself needs looking at.
This change though should address the error though.
