### ISSUE TITLE
ShippingMethod::getActiveShipmentID() in Order.php

### ISSUE THREAD

**Issue by wimbouter** [concrete5-community-store/community_store#586]
In Src\CommunityStore\Order\Order on line 550 there is this method:
$sShipmentID = ShippingMethod::getActiveShipmentID();

The method is registered in Src\CommunityStore\Shipping\Method on line 359.
There the method calls "getShipmentID" on the current Offer.
The method "getShipmentID" doens't exist in the class ShippingMethodOffer.

It should be "getID" or "getOfferKey".

**Comment by Mesuva** [comment]
I'm seeing getShipmentID here:
https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Shipping/Method/ShippingMethodOffer.php#L129
