### ISSUE TITLE
Product Page Variation Quantity Issue

### ISSUE THREAD

**Issue by Mattydor** [concrete5-community-store/community_store#589]
I'm developing a website with Community Store and it's looking great so far. I just have one issue and I couldn't see it flagged anywhere else so I thought I'd put it out here. 

I noticed that the quantity field in the product page is limited by the first variation of an item. For example, I have 3 different size variations and the 1st size has only 1 item in stock, 2nd has 5 and 3rd has 20. It doesn't matter which size the customer chooses, the quantity field is limited to the first variation. I've tried select menu and radio buttons and various settings. It's always the same. If I add two or more variations of the item to the cart, their quantities can be changed to the limit of each perfectly well. This issue only seems to occur on product pages and product list pages.

Apologies if I'm posting in the wrong place. This is my first time here. Thanks in advance for any help.

**Comment by Mesuva** [comment]
You may have just come across a bug/oversight, I'll investigate this one soon. 

Certainly the right place to post this report, I appreciate the detail.

**Comment by Mattydor** [comment]
Thanks! I'm glad I finally took the plunge with CS. I've been hand-building shopping cart solutions to run alongside C5 sites in the past. CS is exactly what I needed all along.

**Comment by Mesuva** [comment]
I've pushed a fix for via https://github.com/concrete5-community-store/community_store/commit/fe0316ac193f11525f0d01e1c46dfb1e663b9377
If you have the ability to apply these changes and test it out on your end, that would be appreciated

**Comment by Mattydor** [comment]
Awesome. I'll implement it and let you know.

**Comment by Mesuva** [comment]
Any luck testing this change on your end?  I'm thinking of putting out another release, so any feedback you have at this point would be appreciated.

**Comment by Mesuva** [comment]
I've pushed up a further update to address the issue you flagged:
https://github.com/concrete5-community-store/community_store/commit/7b25e9fea14a3f9b15eba390e66cb4f69bcec4c5

It also will update the quantity field when you try to change it directly, instead of having to hit submit. 
That actually wasn't my intention from my change, it was an accidental side effect, but I think it might be worth keeping!
