### ISSUE TITLE
[Proposal] Option for Discounts on Sales Price

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#590]
We have a wine store where we use discounts to provide half case and case discounts on any 6 or 12 bottles selected. This works well and allows a mixed case to be chosen.

We've been trying to discount certain bottles using Sale Price and our normal quantity discounts are then ignored in preference to the Sale Price.

I can see this would be an intended behaviour in many instances.  However, I wonder if it would be possible to add an option to discounts to allow them to be applied to Sales Prices where appropriate?

**Comment by Mesuva** [comment]
I reckon I went back and forth with this one originally, trying to decide what way to go with it - it never occurred to me to just make it an option.

Would the option be on the product, or on the discount rule do you think?

**Comment by katalysis** [comment]
I'd think the option should go on the Discount.  If there were products that needed to behave differently when combining Sale Price and Discount it would be pretty straightforward to create two discounts each associated with a separate Product Group.

**Comment by SpatialAnomaly** [comment]
We were also just looking at this and a checkbox on the discount rule itself that would allow it to apply to sale items would solve it for our purposes. I was actually on my way here to post this exact issue and was surprised to see it sitting here already!

**Comment by Mesuva** [comment]
I've pushed up https://github.com/concrete5-community-store/community_store/issues/590 to provide this option - if anyone has a chance to test and confirm this is working as expected, that would be great.
