### ISSUE TITLE
Orders using Stripe Checkout addon not showing in Dashboard > Store > Orders page

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#602]
Hi

Orders using Stripe Checkout addon not showing in Dashboard > Store > Orders page
If I place the order using Invoice it works.
Other than this, Stripe checkout is working and orders are completing.  The webhook has been added too.
I can see the order details in the Database table: CommunityStoreOrders

Community Store v2.1.7
Stripe Checkout Payment Method v.1.0.1

**Comment by Mesuva** [comment]
That sounds like the webhook isn't working correctly to mark the order is paid:
- check Stripe's dashboard for the responses you are getting from the webhook
- check that the webhook is configured to send the correct event
- check the the signing key is correct
- check the concrete5 logs, I think there's some debugging in place if the webhook fails in some cases (maybe)

**Comment by madesimplemedia** [comment]
Thanks for the quick reply, looks like I somehow got my webhooks muddled up, all working now

**Comment by Mesuva** [comment]
Excellent, good when it's an easy to resolve issue!
