### ISSUE TITLE
Modal Cart

### ISSUE THREAD

**Issue by sampago** [concrete5-community-store/community_store#603]
My apologies if this issue has been answered elsewhere, I've done my best to locate an answer.

How does one open the cart as modal/slide from edge of window - as an alternative to visiting the single page Cart?

So, for example for the following product, clicking Add to Cart causes the modal Cart dialog to slide to the right of the window.
https://www.pago.wine/index.php/shop/malavara-2019-raul-calle

I would like the same behaviour to occur when the Cart link on the navigation menu is clicked.

**Comment by Mesuva** [comment]
That sounds like you have a link to the Cart _page_ in your navigation, so by default that's just going to act as a normal link.

The Utility Links block is intended to be use to trigger the cart (and show other details), so perhaps that's what you are missing from your layout. 

But if you're wanting to leave your Cart link on the main menu and have that trigger the cart, you'll need to find a way to attach the same kind of javascript that is used for the utility block.

That javascript (jquery) is this:

```
    $('.store-cart-link-modal').click(function(e) {
        communityStore.displayCart(false, true);
        e.preventDefault();
    });
```

So one option is to add to your menu item the same class that triggers the menu, .store-cart-link-modal
There is a way to use/create an `nav_item_class` attribute, and make a small change to the autonav template to achieve this. 

The only caveat is that you need to ensure that the javascript for Community Store are loaded in, and that's only going to happen on pages where there is a cart block or a product/list block. So if you did it this way, you'd perhaps still want to include a Utility Links block on your site in a global area, but adjust it so it doesn't output anything. That at least ensures that the scripts get loaded.

You could also add your own javascript that triggers the cart, really just be calling the same function that the snippet above does.

**Comment by sampago** [comment]
Many thanks for your help, now functioning as reequired
