### ISSUE TITLE
Express Entity attribute type doesn't show picker while in product attributes edit screen

### ISSUE THREAD

**Issue by SpatialAnomaly** [concrete5-community-store/community_store#604]
I have a custom attribute for products that allows for picking a Express Entity. In this case, it's a category of testimonials. For the life of me I can't figure out why the picker isn't showing.
![image](https://user-images.githubusercontent.com/1445491/108427059-9762b500-720a-11eb-8a15-189643856a3c.png)

I can see the title of the attribute (Show a Random Testimonial From Category) but as you can see the blue button that would normally be there and allow you to pick an entry from that entity is not there. There's no errors in my console to suggest it failed.

I thought maybe it was permissions but I don't have advanced permissions turned on. Nothing I can see suggests that I wouldn't have permission, especially considering I am logged in as the super user.

I have entries in that express entity so there is definitely content there.

Here's the attribute settings itself. I did have to check off the box to allow this attribute type to be used with products.
![image](https://user-images.githubusercontent.com/1445491/108427462-31c2f880-720b-11eb-9309-403a04b4524d.png)

I know I have set this up before in the far distant past now but I don't recall having any trouble.

Thoughts / Suggestions would be appreciated.

**Comment by Mesuva** [comment]
I've had a look at this but I'm not sure of the solution for this on the Community Store side yet.

Looking at /concrete/attributes/express/form.php, there's an if statement in there:
```
if (isset($entity, $entry) && $entity instanceof Entity && $entry instanceof Entry) {
    echo $entrySelector->selectEntry($entity, $this->field('value'), $entry);
}
```
If I remove that if statement and just echo the $entrySelector, the picker appears.
Then if I save it down, it works, no issue.
Then if I put back the if statement and refresh, it continues to show the selector.
If I clear the express entry and save, it clear it, but then goes back to not showing the selector.

So it sort of seems like this is a core thing, as all other attribute types appear to be working.

**Comment by Mesuva** [comment]
@mnakalay has kindly pointed out to me that this is in fact a core bug, something that has been fixed in V9, but not yet in V8.

The fix for `/concrete/attributes/express/form.php` would be to change it to 

```
if (isset($entity) && $entity instanceof Entity && (is_null($entry) || $entry instanceof Entry)) {
    echo $entrySelector->selectEntry($entity, $this->field('value'), $entry);
}
```
I don't believe there's a way around this apart from this hotfix of the core.

**Comment by SpatialAnomaly** [comment]
Thanks a bunch, I will give that a shot!

**Comment by biplobice** [comment]
Leaving it as a reference-
https://github.com/concrete5/concrete5/pull/8749
