### ISSUE TITLE
Upgrading from 2.1.7 to 2.3.4

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#608]
Hi

Upgrading in Add Functionality I get this error:

An exception occurred while executing 'ALTER TABLE CommunityStoreOrders ADD memberCreated TINYINT(1) DEFAULT NULL, ADD sTrackingEstimatedDate LONGTEXT DEFAULT NULL, ADD oNotes LONGTEXT DEFAULT NULL, ADD userAgent VARCHAR(255) DEFAULT NULL, CHANGE cID cID INT DEFAULT NULL, CHANGE pmID pmID INT DEFAULT NULL, CHANGE pmName pmName VARCHAR(255) DEFAULT NULL, CHANGE smName smName VARCHAR(255) DEFAULT NULL, CHANGE sShipmentID sShipmentID VARCHAR(255) DEFAULT NULL, CHANGE sRateID sRateID VARCHAR(255) DEFAULT NULL, CHANGE sCarrier sCarrier VARCHAR(255) DEFAULT NULL, CHANGE sTrackingID sTrackingID VARCHAR(255) DEFAULT NULL, CHANGE oShippingTotal oShippingTotal NUMERIC(10, 2) DEFAULT NULL, CHANGE oTax oTax VARCHAR(255) DEFAULT NULL, CHANGE oTaxIncluded oTaxIncluded VARCHAR(255) DEFAULT NULL, CHANGE oTaxName oTaxName VARCHAR(255) DEFAULT NULL, CHANGE transactionReference transactionReference VARCHAR(255) DEFAULT NULL, CHANGE oPaid oPaid DATETIME DEFAULT NULL, CHANGE oPaidByUID oPaidByUID INT DEFAULT NULL, CHANGE oCancelled oCancelled DATETIME DEFAULT NULL, CHANGE oCancelledByUID oCancelledByUID INT DEFAULT NULL, CHANGE oRefunded oRefunded DATETIME DEFAULT NULL, CHANGE oRefundedByUID oRefundedByUID INT DEFAULT NULL, CHANGE externalPaymentRequested externalPaymentRequested DATETIME DEFAULT NULL, CHANGE locale locale VARCHAR(255) DEFAULT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by madesimplemedia** [comment]
Using v8.5.5 on PHP7.4

**Comment by Mesuva** [comment]
I wouldn't have thought that the CommunityStoreOrders table has field types to any notable size.

I'm sure we can adjust the table definition to use more text types, or reduce the size of several of the fields, but it doesn't seem anywhere big enough to warrant that yet. I'm wondering if it's some other issue that is reporting as this error.

What's the database/version and what engine is being used for the table(s)?

**Comment by madesimplemedia** [comment]
Using MariaDB 10.3.28 and InnoDB

However on another server running the same DB and engine, it seems ok.

**Comment by Mesuva** [comment]
From what I've read, this can be fixed by running
ALTER TABLE `CommunityStoreOrders` ROW_FORMAT=DYNAMIC;

**Comment by madesimplemedia** [comment]
That has fixed it, thank you very much :)
