### ISSUE TITLE
Cart and Checkout pages are down

### ISSUE THREAD

**Issue by craigmarcussen** [concrete5-community-store/community_store#613]
Hello,

I developed a site running c5 v8.5.4, and Community Store v2.3.4, and PHP 7.4. Today I was informed that the Cart and Checkout pages are down. I am getting a 500 error on the pages, and when I turn on detailed Debugging, I get the following error:

`Illegal length modifier specified 'f' in s[np]printf call`

This has come up before, but seemed to resolve after an hour or two, but this time it is not resolving (it's been a few hours). The site has plenty of memory assigned (1024MB), so I don't think that is the issue. 

I could use some help with this... my client is quite concerned, and is currently taking orders over the phone.

The site is: jmanporscheparts.com

Thank you,
Craig

**Comment by Mesuva** [comment]
Hi Craig,

I've seen this issue before on a site, and it ended up being some obscure PHP bug, not actually related to the code as such.
Everything I've read about this error message suggests it's some internal PHP bug.
I believe a 'solution' is to change the PHP version, i.e. changing from 7.4 back to 7.3, something like that.

I'm assuming you've tried clearing and turning on and off caches, etc?

If that doesn't work, feel free to drop me an email, I'm happy to take a look.

**Comment by craigmarcussen** [comment]
Ryan,

Thanks for tracking this issue down, and working with me further through email. As you mentioned, it seems to be a problem with the Host (InMotion Hosting), and their particular PHP implementation. I think the best solution will be to change hosts, and I am going to recommend that my client use your suggestion of Veerotech.

Again, I appreciate the time and research you put into this. Above and beyond!

Craig
