### ISSUE TITLE
Price changes no longer shown when switch varation selector

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#619]
The js and associated div id that used to allow prices to change when a different variation was selected in the product block has been removed.

Is this deliberate or an oversight?

**Comment by Mesuva** [comment]
I recall there was some re-working of the javascript at some point, so it didn't depend on an ID to reference the product block. I think this was to avoid having to have custom javascript on the page for each block, and instead shift that scripting to a common JS file.

Could this explain what you are seeing?  Some older javascript perhaps?

I'm using the latest release right this moment, with products with variations that change the price, and that's working as expected on the product block.

**Comment by katalysis** [comment]
Just tested this on a clean install and it works fine - we obviously have some old and new code mixed in our custom template.
