### ISSUE TITLE
Best Sellers Exception - Integrity constraint violation

### ISSUE THREAD

**Issue by redi-bpage** [concrete5-community-store/community_store#621]
I have an error occurring that's appearing when I sort by "Best Sellers" using the Product List Block. It occurs with the latest version of C5 and Community Store.  

The odd thing is it seems to be related to the table CommunityStoreOrderItems.

I've discovered if I remove a certain number of items from this table the problem goes away. If I add one more order the fatal error returns.

I have deleted various product IDs and can confirm it is not related to a specific ID. It might be related to the number of `p.pID = ? DESC` conditions. When remove a handful of the `p.pID = ? DESC` conditions, the exception goes away.

I’ve made database adjustments by increasing tmp_table_size, max_heap_table_size, max_allowed_packet, sort_buffer_size, join_buffer_size, innodb_temp_data_file_path, and also the tmpdir path, but the problem persists. I’m not certain what could be causing this. 

Stack Trace Output:
`Exception Occurred: /home/site-data/default/public_html/concrete/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115 An exception occurred while executing 'SELECT p.pID FROM CommunityStoreProducts p INNER JOIN CommunityStoreProductGroups g ON p.pID = g.pID and g.gID in (21) LEFT JOIN CommunityStoreProductSearchIndexAttributes csi ON p.pID = csi.pID WHERE (pQty > 0 OR pQtyUnlim = 1) AND (pActive = 1) GROUP BY p.pID, p.pName, p.pPrice, p.pActive, p.pDateAdded HAVING count(g.gID) = 1 ORDER BY p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC, p.pID = ? DESC LIMIT 1000 OFFSET 0' with params [152, 245, 44, 86, 78, 319, 273, 205, 190, 24, 211, 39, 272, 297, 252, 276, 313, 191, 189, 74, 175, 217, 306, 8, 206, 6, 281, 262, 242, 100, 249, 292, 25, 75, 267, 255, 192, 204, 302, 239, 201, 17, 315, 248, 104, 275, 41, 310, 266, 19, 90, 35, 246, 85, 327, 244, 231, 102, 21, 58, 330, 286, 270, 247, 166, 238, 50, 215, 309, 320, 233, 33, 193, 261, 229, 304, 312, 277, 258, 70, 311, 65, 82, 202, 234, 287, 274, 225, 226, 23, 93, 290, 30, 136, 203, 216, 278, 259, 271, 227, 328, 314, 254, 77, 28, 303, 243, 251, 167, 56, 87, 92, 173, 71, 268, 38, 14, 63, 329, 316, 291, 282, 228, 60, 235, 42, 9, 294, 168, 137, 55, 230, 52, 10, 237, 126, 269, 326, 80, 298, 236, 103, 84, 214, 317, 283, 142, 299, 95, 256, 40, 250, 154, 98, 51, 11, 27, 89, 222, 125, 285, 16, 68, 289, 212, 130, 83, 49, 280, 96, 288, 321, 72, 69, 221, 296, 219, 147, 322, 62, 15, 73, 64, 91, 79, 160, 127, 143, 129, 213, 13, 46, 300, 43, 307, 81, 121, 150, 45, 99, 144, 26, 253, 318, 134, 94, 128, 120, 101, 97, 53, 105, 308, 111, 124, 161, 188, 210, 301, 279, 181, 232, 48, 187, 32, 140, 139, 149, 122, 257, 37, 138, 169, 116, 109, 113, 117, 163, 162, 108, 114, 133, 148, 47, 131, 57, 151, 54, 158, 224, 260, 325, 115, 185, 153, 106, 171, 145, 132, 146]: SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '/tmp/#sql1_8_3' (0)`

**Comment by Mesuva** [comment]
Try this update here: 
https://github.com/concrete5-community-store/community_store/commit/407205a2e86e1146df068781076e1116537d26b1
