### ISSUE TITLE
Community store - Product details page - Assigning Custom template not working

### ISSUE THREAD

**Issue by zen2nad** [concrete5-community-store/community_store#625]
Dear Team,

Greetings. I am using Concrete 5 - V 8.5.5 and installed community store add-on for ecommerce. The products list are uploaded via automated excel and I coded to create the product page via custom program. 

By default, the community store product details page works with full page template. Instead of that, I want to load the information via my custom template “product details” in the front end. The product details didn’t load correctly if am using my custom template id in the program.

$templateID = 12; [New Template ID instead of Full page]
Product::getByID($pId)->generatePage($templateID);
Product::getByID($pId)->updateUrlSlug($newurl);

![PRODUCT-DETAILS](https://user-images.githubusercontent.com/534525/126114605-17d1a6a4-f332-49f8-88a3-1fe1e462334f.jpg)
![Product-info-missing](https://user-images.githubusercontent.com/534525/126114611-5c4edf4c-da77-400f-87cd-33f7f45e9f83.jpg)

Do let me know what is the solution for this issue.

Thanks,
Lindy

**Comment by Mesuva** [comment]
This sounds like you need to add the default Product block to your page template.
Community Store's code that creates the product page doesn't add any blocks programatically, it simply creates a new page of the 'Product' page type, of the template selected, and it's up to the template to define what blocks are included on the new page.

You would go to Dashboard->Page Types and select Output next to the Product page type.
Then you'd select your page template and add to that a default Product block, select 'Product associated with this page' in the Product selector dropdown.

**Comment by zen2nad** [comment]
Dear Mesuva, 

Thank you for sharing the details. It is helpful. As per your instruction, i tried to reach that "output" section of the page type, but i couldn't see the Edit Header option to pull the product block into the template. Can you let me know how to grant permission for the template to allow edit ? Sorry, it may be silly question, since this is my first C5 development. Have to learn more...

Thanks
Lindy

**Comment by Mesuva** [comment]
You may need to log in as the 'super' admin, rather than a user in the administrators group.
I recall that those page template defaults are only editable as the super admin.

**Comment by Mesuva** [comment]
(the super admin being the first user account created, has an ID of 1)

**Comment by zen2nad** [comment]
Dear Mesuva, 

Thank you for the information that shared. It is helpful.. Will check that method and share my findings..

**Comment by zen2nad** [comment]
The given solution works well, assigned the block as default via super account.. Thanks mr. mesuva
