### ISSUE TITLE
Issue with filtering order list by status

### ISSUE THREAD

**Issue by evgk** [concrete5-community-store/community_store#627]
This piece of code:
```
            $matchingOrders = $db->query("SELECT oID FROM CommunityStoreOrderStatusHistories t1
                                            WHERE oshStatus = ? and
                                                t1.oshDate = (SELECT MAX(t2.oshDate)
                                                             FROM CommunityStoreOrderStatusHistories t2
                                                             WHERE t2.oID = t1.oID)", [$this->status]);
```

from 
https://github.com/concrete5-community-store/community_store/blob/master/src/CommunityStore/Order/OrderList.php

has an issue with filtering by status when the timestamp of the status entries is from the same second, e.g.:

MariaDB [bbpizza]> select * from CommunityStoreOrderStatusHistories where oID='1778';
+-------+------------+---------------------+------+------+
| oshID | oshStatus  | oshDate             | uID  | oID  |
+-------+------------+---------------------+------+------+
|  3580 | incomplete | 2021-08-09 23:14:03 | NULL | 1778 |
|  3581 | processing | 2021-08-09 23:14:03 | NULL | 1778 |
|  3582 | processing | 2021-08-09 23:14:03 | NULL | 1778 |
|  3583 | processing | 2021-08-09 23:14:03 | NULL | 1778 |
|  3584 | processing | 2021-08-09 23:14:03 | NULL | 1778 |
+-------+------------+---------------------+------+------+
5 rows in set (0.00 sec)

With the code above, filtering by 'processing' and 'incomplete' statuses will return the same order.
Wouldn't it make sense to change the 
t1.oshDate = (SELECT MAX(t2.oshDate)

line to
t1.oshID = (SELECT MAX(t2.oshID)

in order to always filter by the last status?

**Comment by Mesuva** [comment]
Yes, pretty sure you're right here.

Out of interest, why are you ending up with CommunityStoreOrderStatusHistories entries for the same order with exactly the same timestamp?

**Comment by evgk** [comment]
> Out of interest, why are you ending up with CommunityStoreOrderStatusHistories entries for the same order with exactly the same timestamp?

Integration transferred the order the same second the user submitted it. It's one-out-of-thousands case, but it happens.
