### ISSUE TITLE
V2.4 Shipping

### ISSUE THREAD

**Issue by SB1955** [concrete5-community-store/community_store#637]
Don't seem to be able to set a shipping method. Clicking 'Add Shipping Method' does nothing, apart from refresh page and when going to checkout there isn't any error showing about shipping method not set. 
Not getting 'Use these details for shipping' button.

Local setup with MAMP, PHP 7.4.21, C5 V9.0.1  and elemental theme.

**Comment by Mesuva** [comment]
I'll certainly investigate this issue, but you're perhaps a bit premature with using version 2.4 and version9 of Concrete. 

Whilst I've done the majority of the work to make it V9 ready, I haven't put out a release yet as there are still a handful of minor things to address. I've also been waiting for some of the minor point releases of Concrete to occur, just to let things settle down a bit.

I generally recommend using releases of Community Store for production sites and not the master branch. 
I should however, have time in the next week to finish things up and get a proper release for V9 out.

**Comment by Mesuva** [comment]
This has been fixed within a bunch of V9 related fixes, so will be included in the upcoming release:
https://github.com/concrete5-community-store/community_store/commit/dc93da89e46e882026789f5c978637e57063f52a
