### ISSUE TITLE
Product name size

### ISSUE THREAD

**Issue by penbox-ad** [concrete5-community-store/community_store#640]
I noticed that if you pick one product to page (using Product block) the store product name is h1 style, but if you list several products (using Product List block) all product names are smaller h2 style.

Is there a reason why one product name is bigger than listing names?
For me it looks better if both will be as h2 style. 
Is there a simple way to change product name style from h1 to h2?

**Comment by Mesuva** [comment]
Yes, the reason for this is to do with SEO and page semantics.

Normally, you'd use a single product block on a product page, and therefore the H1 of the block becomes the main H1 for that page. That's good for SEO, as the main heading of the page directly relates to the product.

But a product list is going to output multiple products, and for SEO purposes you don't want to output multiple H1 headings on a page. Instead, you're more likely to have something like a category name as the H1 at the top of such a page, with the product list underneath it.

But as they are blocks, you're free to override the block templates as you see fit, perhaps creating some custom templates to give you the choice.
Or, you can apply some custom styling to make your H1s in those blocks the same style as your H2s.

**Comment by penbox-ad** [comment]
Thanks Mesuva, SEO is a good reason :) 
I'll try using custom style to make names look similar in this case.
