### ISSUE TITLE
Filter does not work with ( ) or [ ].

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#642]
I am using Store version 2.3.6
I made attribute filters and  several have a ( ) in them, I changed it to [ ] and still doesn't work. I even tried `&#40;` and `&#41;`
None of them worked.

The / and - and even the µ all work.

https://www.mdius.com/liquid-level-controls

**Comment by Mesuva** [comment]
I see what you've described, it looks like the escaping of the characters isn't good enough - I will try to look at this soon.

**Comment by mdius** [comment]
Tried a few more characters.
& and # do work.
But ; does not. So the ASCII will not work do to the ;

**Comment by Mesuva** [comment]
I've pushed up a fix for this - https://github.com/concrete5-community-store/community_store/commit/bc3ba4c957c2f4bf9cf3d58eee18a1638e3d6df8

To apply the change, the easiest thing to do is just replace the entire processUrlFilters function in the ProductList.php file, from here:
https://github.com/concrete5-community-store/community_store/blob/bc3ba4c957c2f4bf9cf3d58eee18a1638e3d6df8/src/CommunityStore/Product/ProductList.php#L131

**Comment by mdius** [comment]
This fix worked perfectly. Thank you!
