### ISSUE TITLE
SKU Ascending is not working on the product_list form.php

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#643]
I could not get the page to accend. The noticed you have:
`'sku' => t("SKU Alphabetical"),`
it seems to work if:
`'sku_asc' => t("SKU Alphabetical"),`

**Comment by Mesuva** [comment]
I'm not seeing this, I'm able to sort by SKU alphabetically, and the code in the product list block looks correct to me.
This section here sets the default sort direction of ascending when 'sku' is used,
https://github.com/concrete5-community-store/community_store/blob/master/blocks/community_product_list/controller.php#L122

It is that you have some products without SKUs?  Those will appear first in this case.

**Comment by mdius** [comment]
I see what I did.
Should have known it was something on my end. I'm sorry.

**Comment by Mesuva** [comment]
No worries at all!
