### ISSUE TITLE
unpaid download product -> link sent in mail

### ISSUE THREAD

**Issue by calibal** [concrete5-community-store/community_store#658]
payment method: Order - left unpaid
product type: downloadable product

when an order is done, the mail is sent to the customer with the download link exactly like it's paid.

**Comment by Mesuva** [comment]
Try the changes in https://github.com/concrete5-community-store/community_store/commit/6bbaa3510fe95ef5d2d5fced644616bf3eb196d0  (you should be able to manually apply them, they're small)
