### ISSUE TITLE
Multilingual Translation Page Layout for multiple languages

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#659]
We have a scenario where we are setting up multiple languages for products, but the page to input the translations seems to have a layout bug where it moves the columns over by one column for new languages after the first translation. 

This is on version 2.4.6 of Community Store and the latest version of concrete 9.0.2 and the latest development version 9.0.3.a1.

Here's a screenshot of what we're seeing:
![communitystore_multilingual_translate_page](https://user-images.githubusercontent.com/4235012/160590554-062311f7-9ba0-4a7f-9715-cdfe6a604046.png)

Is this a known issue?

**Comment by Mesuva** [comment]
I've not seen this one before - it may have been a bug introduced from the BS5 work for V9.
If you can spot the issue, let me know, otherwise I'll take a look soon.

**Comment by katalysis** [comment]
Thank you @Mesuva
