### ISSUE TITLE
Issue: Product option Base Weight gets saved as Width

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#66]
1) Add an Option Group under a product
2) Tick "Options have different prices, SKUs or stock levels"
3) Under one of your option variations, click "more options"
4) Enter a number for base weight
5) Update Product
6) Check back and you'll see the number wasn't saved under base weight, but appears in width instead

**Comment by Mesuva** [comment]
Nicely spotted!

Fixed by https://github.com/concrete5-community-store/community_store/commit/56b7c1e7b9fdd5260be369c08b325cd524993c51
