### ISSUE TITLE
Autonav Breadcrumb Template Exception with Concrete CMS 9.1.0

### ISSUE THREAD

**Issue by JeRoNZ** [concrete5-community-store/community_store#674]
In version concrete cms version 9.1.0 the cID variable in the autonav block controller class is protected, thus using this template as is throws an exception.

I got around it by overriding the block controller and adding a method to set cID, but that's maybe not so useful for most folks. 

Is there a need for an actual product breadcrumb block to work around this, or is it something that might be solved with a PR on the concrete cms core (adding the setCID method)?

https://github.com/concrete5-community-store/community_store/blob/63d07362aee85ad412432fbc9b8be269af918cb2/blocks/autonav/templates/product_breadcrumb.php#L32

**Comment by Mesuva** [comment]
Well that's a bit annoying!
Probably a fair bit of work just to create a breadcrumb specific block, but on the other hand it might open up some other potentials.. will give it some thought, but I think the easiest is probably to do a PR for the core.

**Comment by JeRoNZ** [comment]
Yup - I reckon what happened is that in v8 cID was an undeclared variable, and in v9 it got marked as protected when updates for PHP8/8.1 were rolled out. I'll raise an issue on the core and see what the opinion is.

**Comment by JeRoNZ** [comment]
https://github.com/concretecms/concretecms/issues/10665
