### ISSUE TITLE
Increase product variation quantity

### ISSUE THREAD

**Issue by JeRoNZ** [concrete5-community-store/community_store#677]
There's a hard coded limit of 50 variations per product which is I guess a sanity check to stop large numbers of options giving rise to a huge number of variations. I've a case where 50 is too small. 150 would likely do it. However, raising the value past 50 raises the prospect of hitting the default value for max_input_vars which is by default 1,000. That leads to loss of data and the failure to save some of the variation data.

I'm wondering about adding a config setting to allow the varations to be pushed up to 150, but with a warning about setting max_input_vars correctly. 

I did some experiments to try and figure out whether that limit has been hit, using count($_POST,COUNT_RECURSIVE), but it seems to be a little inaccurate, but not hugely. I was wondering whether it's wise to put a check at the top of the save() method in the dashboard product page controller and refuse to save any data if that limit gets hit. Even allowing for a bit of inaccuracy, there will come a point where the number of POST vars is close to the lmiit, maybe with additional attributes etc. being added and it seems prudent to try and catch this before data starts getting truncated.

**Comment by Mesuva** [comment]
The actual solution to this is to not send the variation data as individual fields, but to bundle it up into some json and send that through instead. It's still pretty unwieldy to have a large number of combinations to process.

I've often said though that if you need more than 50 variations, that you _probably_ need to split products into multiple, or reduce the number of options from impacting the variations. Out of interest, what's the use-case you're needing more than 50 for?

**Comment by JeRoNZ** [comment]
Agree about the JSON. I was thinking something along the same lines, but I'd considered pushing all the variations into a single POST field, a multi dimensional array, but JSON makes more sense.

I'd tend to agree that over 50 variations is a bit nuts, but in the case I have before me (jewellery components) there are six types of metal and probably 15+ sizes in 0.5mm increments for what is fundamentally the same product, e.g. an earring stud. I guess if I was starting from scratch I would likely go with separate products for each metal but in this case it's a migration from another platform so there's something of a precedent.

I have an update that adds the higher capacity setting, but I think I might have a crack at turning the post request into json as that is a better solution.
