### ISSUE TITLE
Export in CSV Broken - Concrete v9

### ISSUE THREAD

**Issue by f6cm** [concrete5-community-store/community_store#684]
Hi,

After updating to concrete 9.1 and Community Store 2.4.7.2, I get the following when trying to export Sales in CSV :

Unresolvable dependency resolving [Parameter #0 [ <required> $filename ]] in class Concrete\Package\CommunityStore\Src\CommunityStore\Report\CsvReportExporter

Is there something I could do to fix it ?

Everything else is working flawlessly !
Thank you !

![Screenshot 2022-08-29 at 11 03 48](https://user-images.githubusercontent.com/26539969/187166062-d9763bb7-45cf-449d-8a90-2712d97f55dd.png)

**Comment by Mesuva** [comment]
Try this single line fix here:
https://github.com/concrete5-community-store/community_store/commit/515621c525e3648f4756bc182783334e1b293455#diff-27f6a052b5a4242d43fa32a5c5d7769f2b08410ffb029426cbd618d63c517953L126

(just change build to make)

**Comment by f6cm** [comment]
And it works!

Thank you so much for your help!
