### ISSUE TITLE
SQL exception on package install

### ISSUE THREAD

**Issue by ob7** [concrete5-community-store/community_store#72]
The following error on unmodified install on 5.7.5.8:

An exception occurred while executing 'INSERT INTO CommunityStoreOrderStatuses (osHandle, osName, osInformSite, osInformCustomer, osIsStartingStatus) VALUES (?, ?, ?, ?, ?)' with params ["incomplete", "Awaiting Processing", 1, 0, 1]: SQLSTATE[HY000]: General error: 1364 Field 'osSortOrder' doesn't have a default value

**Comment by ob7** [comment]
Another when trying to add product options:

An exception occurred while executing 'INSERT INTO CommunityStoreProductVariations (pID, pvPrice, pvSKU, pvSalePrice, pvfID, pvQty, pvQtyUnlim, pvWidth, pvHeight, pvLength, pvWeight, pvNumberItems) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, null, "", null, "", "", "", null, null, null, null, null]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'pvfID' at row 1

**Comment by ob7** [comment]
Adding product list causes more exceptions:

An exception occurred while executing 'INSERT INTO btCommunityStoreProductList (bID, sortOrder, filter, filterCID, groupMatchAny, maxProducts, showOutOfStock, productsPerRow, showPagination, showFeatured, showSale, showDescription, showPrice, showQuickViewLink, showPageLink, pageLinkText, showAddToCart, btnText) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["41", "alpha", "all", "0", "0", "", 0, "1", 0, 0, 0, 1, 1, 0, 1, "", 1, ""]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'maxProducts' at row 1

When can I use this in production?

**Comment by Mesuva** [comment]
I think all these errors are from a particular MySQL version, or at least the strictness of the settings.
I installed a fresh copy of the store into 5.7.5.8 yesterday and didn't hit any of these issues (and we've got two shops in production)

I'll look to resolve these today.

**Comment by Mesuva** [comment]
Specifically I think you are running MySQL in strict mode:
http://stackoverflow.com/questions/25865104/field-id-doesnt-have-a-default-value

Although the code should be updated to run with either setting, I get the impression that strict mode is not actually the common setting to have on mysql.

**Comment by Mesuva** [comment]
I've made a bunch of tweaks to handle strict mode, in this commit here:
https://github.com/concrete5-community-store/community_store/commit/25aceaf6999f3542cb1b9cadf1e28fa4f20858ab
(to address the errors you've listed above, plus a few other spots)

I've tested a fresh install with strict mode on - it installed cleanly and I was able to add products with variations, as well as add product list blocks.

I'll close this now, but obviously reply if you test it and find further issues.

**Comment by ob7** [comment]
New errors, this time when saving settings in backend:

An exception occurred while executing 'UPDATE CommunityStorePaymentMethods SET pmButtonLabel = ?, pmSortOrder = ? WHERE pmID = ?' with params ["", "", 2]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'pmSortOrder' at row 1

**Comment by Mesuva** [comment]
I've fixed this addition error with the payment methods.

For issues like this, it's best to open a new issue here on github, and avoid posting reports of bugs on the forums.
