### ISSUE TITLE
V5.8 (beta 5) - Get error when i click on "product" page

### ISSUE THREAD

**Issue by Siton-Design** [concrete5-community-store/community_store#73]
I get this error when i click on "**setting**" or "**products**" and also same error when i try to "unistall" the package.

![error](https://cloud.githubusercontent.com/assets/16711871/16716941/730a953c-4713-11e6-98f5-9d5922b453eb.jpg)

Also when i try to uninstall the package i get this error:
`The class 'Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method' was not found in the chain configured namespaces Concrete\Core, Application\Src`

When i add block and publish i get again same error:
`The class 'Concrete\Package\CommunityStore\Src\CommunityStore\Tax\TaxRate' was not found in the chain configured namespaces Concrete\Core, Application\Src`

**Comment by Mesuva** [comment]
This is a strange one. Are you able to install other packages and run them without such issues? (specifically packages with a src directory and classes)

**Comment by Siton-Design** [comment]
mmm maybe this is related to this "issue":
https://github.com/concrete5/concrete5/issues/3950

I struggle with this bug (This bug is general to V8) - mabye i change something in  database.php" files. 

I will check this in other packages and give you an answer.

**Comment by Mesuva** [comment]
I think you're right, from reading about that bug I think further fixes have been put in place since v8.0.0a5.  So we'd need to test with a more recent version of v8

**Comment by Siton-Design** [comment]
OK. You have idea how to solve this issue? Or even uninstall the package for now (i get the same error when i uninstall).

**Comment by Mesuva** [comment]
As v8 is all beta, I think it's important to treat all these kinds of tests as throwaway. It might be a bit early to expect it all to work yet. There are a few further v8 issues I need to raise as issues for concrete5 itself first.

**Comment by Siton-Design** [comment]
**UPDATE**: I test this package in the new **C5. 8 beta 1**. Works **perferct** without this error! :) 

Thanks for you time.
