### ISSUE TITLE
When duplicating a product with options that have different prices, the prices are not copied over....

### ISSUE THREAD

**Issue by ob7** [concrete5-community-store/community_store#75]
I'm duplicating products changing just name and picture, but the option prices are not copying over, which is time consuming.

**Comment by ob7** [comment]
Also, even if you freshly copied a product, the options are blank right, well if you fill in the options and click save, they will not be saved the first time.  You have to update the product atleast once before adding the options for them to save.  So even if you didn't want options carrying over during product duplication, the options is still buggy concerning the data not being saved first time around.

**Comment by grimm192** [comment]
+1

**Comment by arquus15** [comment]
+1

**Comment by Mesuva** [comment]
I've created a fix for this with PR #93, which seems to be _almost_ there.. but I'm finding that sometimes I can add/remove options from the newly copied product and have that clear all the existing values. Not sure if it's to do with the duplicate, or if it's just a broader bug with the variations saving and options.

I'll keep working on it, but if anyone can spot what might be happening that would be appreciated.

**Comment by Mesuva** [comment]
I've made another commit to the PR, a silly line left in was causing the bug, so I think this is good to go.

If someone could test it and give it the thumbs up that would be great.
