### ISSUE TITLE
Option prices are not sanatized of dollar symbol

### ISSUE THREAD

**Issue by ob7** [concrete5-community-store/community_store#76]
If someone types in the dollar symbol before the amount under option pricing ( and maybe other places I dont know ), there will be an SQL error:

An exception occurred while executing 'UPDATE CommunityStoreProductVariations SET pvPrice = ?, pvQtyUnlim = ? WHERE pvID = ?' with params ["$20", "1", 27]: SQLSTATE[HY000]: General error: 1366 Incorrect decimal value: '$20' for column 'pvPrice' at row 1

I think this can be fixed by sanitizing the $ from any if those inputs just incase.

**Comment by Mesuva** [comment]
I've pushed up a few fixes to address this sort of saving issue with variations and products.
