### ISSUE TITLE
SQL Error When Saving Settings From Dashboard

### ISSUE THREAD

**Issue by ob7** [concrete5-community-store/community_store#79]
This error continues to persist, whenever trying to make a change to settings in the dashboard, there is an SQL exception and nothing gets saved:

An exception occurred while executing 'UPDATE CommunityStorePaymentMethods SET pmSortOrder = ? WHERE pmID = ?' with params ["", 3]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'pmSortOrder' at row 1

So I can't add payment processor with this error, and the site is finished except for adding payment processor, client wants it launched asap, and there's this error. AHHHHHH! -  Ok a little dramatic but why am I still getting this error?

**Comment by ob7** [comment]
To get rid of error type in a number for sort, but seriously that info should be defaulted or input if user leaves it blank.

**Comment by Mesuva** [comment]
Have you updated your codebase with the most recent commits to master?

Specifically this line here should be addressing this bug:https://github.com/concrete5-community-store/community_store/commit/2e798a34c02cf958f2a310960e4807636c833724#diff-d2f06553cb77b590786ae0f65cce076dL98

(I can't replicate it with this in place, I can leave the sort fields blank)

**Comment by ob7** [comment]
Lol yes I also see your comment on concrete5.org thanks for fixing.  This addon is really great.  Any word of an authorize.net plugin in the works?

**Comment by Mesuva** [comment]
Good to hear you're finding it useful - it's a lot of work!

I'm personally unlikely to be creating an Authorize.net add-on anytime soon, as I just don't have a business case at the moment to do so. (There are easier/cheaper gateways available in Australia).
I could end up with a project in the future where it's a requirement, but I don't have any non-Australian shops on the cards.

**Comment by ob7** [comment]
I'm in US and some of our clients sell guns or gun parts, currently only authorize.net will process these payments.

**Comment by Mesuva** [comment]
That's interesting, I have a client here that wanted to sell hand made crossbows, but no bank (or payment gateway here) will handle such payments because they're restricted items.
