### ISSUE TITLE
reports are not working any more

### ISSUE THREAD

**Issue by rii-J** [concrete5-community-store/community_store#82]
just seen, we could fix tomorrow it if you want

**Comment by Mesuva** [comment]
This would be great if you could put in a fix, much appreciated.
(I'm currently travelling so I'm not able to do more than check things out)

**Comment by Mesuva** [comment]
When you say this isn't working, what are you experiencing? I'm not seeing errors in the reports myself.

**Comment by Mesuva** [comment]
I'm going to close this as I'm not seeing broken reports myself in the latest master
