### ISSUE TITLE
Actualizing messages.pot file for translation

### ISSUE THREAD

**Issue by typoman76** [concrete5-community-store/community_store#84]
Im doing some translation work an recognized that in the messages.pot file not all strings are present. i.e. newly added text "Include Delivery Instructions field in checkout".
It would be helpfull to have an updated messages.pot - so i can add the new translations with poedit.

best regards, Roland

**Comment by Mesuva** [comment]
I've updated the translation files (including the .pot file), with this commit here:
https://github.com/concrete5-community-store/community_store/commit/4cb53ec3ba4604102ccfa3a5d42a462889281501

I just used the instructions from here:
http://documentation.concrete5.org/developers/concepts/localization
I ran from the command line:   concrete5 c5:package-translate community_store

I'm pretty sure this should have brought everything up to date - I don't regularly handle translation activities, so I'm hoping I haven't missed anything.
