### ISSUE TITLE
[enhancement] Best Sellers product list

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#86]
Is there a way of making a Best Sellers product list.

**Comment by Mesuva** [comment]
The Product List block has a sort by option of 'Most Popular'.
Does that achieve what you are after?

(I've not used it myself on a project, so I can't say how reliable it is)

**Comment by midhun1993** [comment]
Hi Mesuva 
Thanks for the information,  it's working correctly :).
