### ISSUE TITLE
0.9.8.7 Issues

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store#87]
We upgraded to latest version but have 2 errors

1) SQL error when setting product list options like this:
http://my.jetscreenshot.com/demo/20160812-ppdz-70kb.jpg

2) When trying to add a product getting this error: 
ReflectionException
…/­vendor/­doctrine/­common/­lib/­Doctrine/­Common/­Persistence/­Mapping/­RuntimeReflectionService.php line 80
Concrete\Package\CommunityStore\Src\CommunityStore\Product\ProductVariation\ProductVariation::$pvColor does not exist

**Comment by Mesuva** [comment]
What's the sql error you get for number 1?

With number 2, this looks like it just didn't upgrade cleanly. Try clearing
your cache first, then forcing the package to re-check the ORM objects
through a minor upgrade - just increment the package number a bit and run
the upgrade.

**Comment by madesimplemedia** [comment]
Managed to get it working, we can remove this.
