### ISSUE TITLE
[enhancement]  "My Orders": page for customers 

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#92]
Hi,

I think this functionality will helps the customers to show there entire orders from there login.

thanks
midhun

**Comment by midhun1993** [comment]
close

**Comment by midhun1993** [comment]
Hi  
I checked the  "communitystoreorders" table

oID,
cID,
oDate,
pmID,
pmName,
smName,
sInstructions,
oShippingTotal,
oTax,
oTaxIncluded,
oTaxName,
oTotal,
transactionReference,
oPaid,
oPaidByUID,
oCancelled,
oCancelledByUID,
oRefunded,
oRefundedByUID,
oRefundReason,
externalPaymentRequested.

in which column i can get the uID of user who added the order ?

any idea ?

**Comment by Mesuva** [comment]
It's cID

(it probably should be called uID like what is used across other tables in concrete5, might be worth changing)

**Comment by midhun1993** [comment]
Hi
Thanks for your info   :)

**Comment by Mesuva** [comment]
I'm going to close this for now, it's something better added to the roadmap instead of being left as an issue
