### ISSUE TITLE
Complete status on payment method

### ISSUE THREAD

**Issue by Jozzeh** [concrete5-community-store/community_store#96]
First of all, nice package! 
I have a suggestion which might improve the payment gateways and the order processing. 

Let's say I have a webshop with 2 payment methods enabled:
1. Invoice
2. Online payment gateway

An order with invoice is not paid immediately so the status after the order should be 'Pending Payment'.
An order with the online payment gateway is paid immediately, so the status on this payment method should be 'Processing'.

So being able to set the complete status for each payment gateway would solve this situation. The owner of the webshop will not have to check if a payment is made for order placed using the online payment gateway.

**Comment by Mesuva** [comment]
Hey there, what version of Community Store are you testing/running?

What you've described is already in place, payments have a markPaid() function which returns true or false to mark whether it actually is a completed payment. The Invoice method won't actually mark an order as paid:

![screen shot 2016-09-16 at 8 19 17 pm](https://cloud.githubusercontent.com/assets/1079600/18583637/e65b314c-7c4a-11e6-905a-07a2db10dd46.png)
![screen shot 2016-09-16 at 8 19 22 pm](https://cloud.githubusercontent.com/assets/1079600/18583638/e65b4cfe-7c4a-11e6-9600-baeb0b3b50c5.png)
![screen shot 2016-09-16 at 8 19 25 pm](https://cloud.githubusercontent.com/assets/1079600/18583639/e65d7678-7c4a-11e6-8ad6-f657a712753e.png)

A payment method like Stripe on the other hand will immediately mark an order as paid, with a timestamp and some sort of transaction reference:
![screen shot 2016-09-16 at 8 20 11 pm](https://cloud.githubusercontent.com/assets/1079600/18583657/0aa66580-7c4b-11e6-8533-c069a0a2671f.png)
![screen shot 2016-09-16 at 8 20 13 pm](https://cloud.githubusercontent.com/assets/1079600/18583658/0aa8cf3c-7c4b-11e6-9977-f7fede456d5f.png)

For invoice style orders, to actually mark it as paid you can go to the order and manually add a record of payment.

If I've misunderstood what you've described please let me know!

**Comment by Jozzeh** [comment]
I'm running the latest version, but I overlooked the markPaid function.
This is indeed a viable solution. Thanks!
