### ISSUE TITLE
Adding Products to cart via code is not working properly

### ISSUE THREAD

**Issue by midhun1993** [concrete5-community-store/community_store#98]
Hi,

i have added some products to cart via code but it was not working properly
here is my code
`<?php `
`namespace Application\Controller\OrderOnline;`

`use \Concrete\Package\CommunityStore\Src\CommunityStore\Cart\Cart as StoreCart;`

`use Concrete\Core\Controller\Controller;`

`class ProcessJson extends Controller {`

               public function addTocart(){
                             $pIDs = array(198,197);
                                    foreach($pIDs as $pID){
                                      `$data = array();
			                           $data['pID'] = $pID;
			                           $data['quantity'] = 1;
			                           $response = StoreCart::add($data);
                                                  }
                                   }
                 }
when executing the "addTocart" function i got response that the two products are added to the cart, When visiting the cart page there is only one last product

any one have idea about this?

**Comment by Mesuva** [comment]
Sorry for the delay, I think I've worked out a cause for this.

For your products 198 and 197, do either of them have the 'Options have different prices, SKUs or stock levels' checkbox ticked?  This is pVariations in the database.

If so, that's going to stop them from being added, as the cart expects to receive variation information as well. I tried pretty much the same code as you and hit the same problem. Unchecking that option for the products (even if they have no options defined) solved the issue for me.

**Comment by Mesuva** [comment]
Actually, that's not quite correct. I also found that I needed to add in a line to Cart.php.

See this commit for the change: https://github.com/concrete5-community-store/community_store/commit/2a1336f3cfdeb2c152616dc69ae93fa6ac985707

**Comment by Mesuva** [comment]
@midhun1993 Have you had success with the change I've linked to?

**Comment by midhun1993** [comment]
Hi Mesuva,

Sorry for being late in answering you, 
Yeah thats worked for me

Thanks 
Midhun +1

**Comment by Mesuva** [comment]
Awesome, thanks!
