### ISSUE TITLE
 You must have at least one Order Status.

### ISSUE THREAD

**Issue by katalysis** [concrete5-community-store/community_store#99]
When trying to save settings I get the error message 'You must have at least one Order Status.' 

Yet in the Order Statuses sections there is no way to create these?

**Comment by katalysis** [comment]
I uninstalled and reinstalled the package and all is well, presumably the upgrade from 0.9.8.6 to 0.9.8.7 caused this problem, not sure if really an issue at this point?

**Comment by Mesuva** [comment]
I reckon this could still be a problem with the update. 
But it's a bit strange that they'd disappear, the only place where they are wiped is during install (incase there was a previous install), they shouldn't have been touched during upgrade...
